// ##
//lang code =zh_cn, form locale = zh_CN
var translateState = {
  AA: "武装部队美国",
  Aargau: "阿尔高",
  AB: "阿尔伯塔",
  Aberdeenshire: "阿伯丁",
  "Abu Dhabi": "阿布扎比",
  Acre: "英亩",
  ACT: "奥斯特资本TERR",
  Adana: "阿达纳",
  "ADGCID Campo": "ADGCID坎普",
  Adiyaman: "阿德亚曼",
  AE: "武装部队欧洲",
  Afyon: "阿菲永",
  "AGIN-BURYAT": "AGIN，布里亚特",
  Agri: "农业",
  Aguascalientes: "阿瓜斯卡连特斯",
  "AGUSAN DEL NORTE": "AGUSAN城北",
  "AGUSAN DEL SUR": "南阿古桑",
  Ain: "艾因",
  "AISEN DEL GENERAL CA": "艾森DEL，一般CA",
  Aisne: "埃纳",
  Ajman: "阿吉曼",
  AK: "阿拉斯加州",
  "Akershus Fylke": "阿克斯胡斯郡",
  AKLAN: "阿卡兰",
  Aksaray: "阿克萨拉伊",
  AL: "阿拉巴马州",
  "Al Fujayrah": "铝Fujayrah",
  Alagoas: "阿拉戈阿斯",
  Alava: "阿拉瓦",
  Alba: "阿尔巴",
  Albacete: "阿尔巴塞特",
  ALBAY: "阿尔拜",
  "Alentejo Litoral": "阿连特茹Litoral",
  Alessandra: "亚历山德拉",
  Alexandria: "亚历山德里亚",
  Alicante: "阿利坎特",
  Allier: "阿列",
  Almeria: "阿尔梅里亚",
  "Alpes (Hautes)": "阿尔卑斯（Hautes）",
  "Alpes (Hte-Provence)": "阿尔卑斯（HTE-普罗旺斯）",
  "Alpes-Maritimes": "阿尔卑斯滨海省",
  ALTAY: "阿勒泰",
  Amapa: "阿马帕",
  Amasya: "阿马西亚",
  AMAZONAS: "亚马孙",
  AMAZONAS: "亚马孙",
  "Amnat Charoen": "amnat卜蜂",
  AMUR: "阿穆尔",
  AN: "安达曼群岛/尼科巴",
  Ancash: "安卡什",
  Ancona: "安科纳",
  Anegada: "阿内加达",
  "Anenii Noi": "anenii河内",
  "Ang Thong": "Ang皮带",
  Angus: "安格斯",
  Anhui: "安徽",
  Ankara: "安卡拉",
  Antalya: "安塔利亚",
  ANTIQUE: "古董",
  Antofagasta: "安托法加斯塔",
  Antrim: "安特里姆",
  Antwerp: "安特卫普",
  Anzoategui: "安索阿特吉",
  Aosta: "奥斯塔",
  AP: "安得拉邦",
  AP: "武装部队太平洋",
  "Appenzell Ausserrh.": "阿彭策尔Ausserrh。",
  "Appenzell Innerrh": "阿彭策尔Innerrh",
  Apure: "阿普雷",
  Apurimac: "阿普里马克",
  AR: "阿肯色州",
  AR: "阿鲁纳恰尔邦",
  Arad: "阿拉德",
  Aragua: "阿拉瓜州",
  Arauca: "阿劳卡",
  Araucania: "阿劳卡尼亚",
  Ardahan: "阿尔达罕",
  Ardeche: "阿尔代什",
  Ardennes: "阿登",
  Ards: "阿兹",
  Arequipa: "阿雷基帕",
  Arezzo: "阿雷佐",
  Arges: "阿尔杰什",
  Argyll: "阿盖尔",
  "Århus amt": "奥胡斯AMT",
  Ariege: "阿列日省",
  ARKHANGELSK: "阿尔汉格尔斯克",
  Armagh: "阿马",
  Artvin: "阿尔特温",
  AS: "美属萨摩亚",
  AS: "阿萨姆邦",
  "Ascoli Piceno": "阿斯科利皮切诺",
  Asti: "阿斯蒂",
  ASTRAKHAN: "阿斯特拉罕",
  Asturias: "阿斯图里亚斯",
  Aswan: "阿斯旺",
  Atacama: "阿塔卡马",
  ATHENS: "雅典",
  Atlantico: "大西洋",
  Aube: "奥布",
  Auckland: "奥克兰",
  Aude: "奥德",
  AURORA: "震旦",
  "Aust-Agder Fylke": "AUST-Agder的郡",
  Ave: "大道",
  AVEIRO: "阿威罗",
  Avellino: "阿韦利诺",
  Aveyron: "阿韦龙",
  Avila: "阿维拉",
  Avon: "雅芳",
  Ayacucho: "阿亚库乔",
  Aydin: "艾登",
  Ayrshire: "艾尔郡",
  AZ: "亚利桑那",
  Bacau: "巴克乌",
  "Bacs-Kiskun": "巴奇 - 基什孔",
  Badajoz: "巴达霍斯",
  "Baden-Württemberg": "巴登 - 符腾堡州",
  Bahia: "巴伊亚",
  "Baja California Nort": "南下加利福尼亚州NORT",
  "Baja California Sur": "南下加利福尼亚州",
  Baleares: "巴利阿里",
  "Bali Bali": "巴厘岛",
  Balikesir: "巴勒克埃西尔",
  Ballymena: "巴利米纳",
  Ballymoney: "巴利马尼",
  Balti: "巴蒂",
  Baluchistan: "俾路支",
  Banbridge: "班布里奇",
  Bangkok: "曼谷",
  Baranya: "巴兰尼亚州",
  Barcelona: "巴塞罗那",
  Bari: "巴里",
  Barinas: "巴里纳斯",
  Bartin: "巴尔腾",
  "Bas-Rhin": "下莱茵省",
  "Basel (city)": "巴塞尔（市）",
  "Basel (regional)": "巴塞尔（地区）",
  BASHKORTOSTAN: "巴什科尔托斯坦",
  BASILAN: "巴西兰岛",
  BATAAN: "巴丹",
  BATANES: "巴丹",
  BATANGAS: "八打雁",
  "Bath&NthEstSomerset": "浴缸及NthEstSomerset",
  Batman: "蝙蝠侠",
  "Bay of Plenty": "丰盛湾",
  Bayburt: "巴伊布尔特",
  Bayern: "拜仁",
  BC: "不列颠哥伦比亚省",
  Bedfordshire: "贝德福德",
  Beijing: "北京",
  "Beira Interior Norte": "贝拉内政部北",
  BEJA: "贝雅",
  Bekescsaba: "贝凯什乔包",
  Belfast: "贝尔法斯特",
  BELGOROD: "别尔哥罗德",
  Belluno: "贝卢诺",
  Bender: "德尔",
  Benevento: "贝内文托",
  BENGAL: "孟加拉",
  "Bengkulu Bengkulu": "明古鲁明古鲁",
  BENGUET: "本格特",
  Bergamo: "贝加莫",
  Bergen: "卑尔根",
  Berkshire: "伯克希尔",
  Berlin: "柏林",
  Bern: "伯尔尼",
  Berwickshire: "贝里克希尔",
  Bialystok: "比亚韦斯托克",
  Bicol: "比科尔",
  Biella: "比耶拉",
  Bihor: "比霍尔",
  Bilecik: "比莱吉克",
  BILIRAN: "比利兰",
  BINGOL: "宾格尔",
  "Bio-Bio": "比奥比奥",
  "Bistrita-Nasaud": "比斯特里察 -  Nasaud",
  Bitlis: "比特利斯",
  "Bjelovar-Bilogora": "别洛瓦尔-Bilogora",
  Blackburn: "布莱克本",
  Blackpool: "黑泽",
  "Blekinge Län": "布莱金厄兰",
  Bogota: "波哥大",
  BOHOL: "波荷",
  Bolivar: "玻利瓦尔",
  Bologna: "博洛尼亚",
  Bolu: "波鲁",
  Bolzano: "博尔扎诺",
  Borders: "边界",
  "Bornholm amt": "博恩霍尔姆AMT",
  "Borsod-Abauj-Zemplen": "尔绍德 -  Abauj  - 曾普伦",
  Botosani: "博托沙尼",
  "Bouches-du-Rhone": "bouches度，罗纳",
  Bournemouth: "伯恩茅斯",
  Boyaca: "博亚卡",
  BR: "比哈尔邦",
  Brabant: "布拉邦",
  "Bracknell Forest": "布拉克内尔森林",
  BRAGA: "布拉加",
  "BRAGAN¦A": "布拉干萨",
  Braila: "布勒伊拉",
  Brandenburg: "勃兰登堡",
  Brasov: "布拉索夫",
  Bratislava: "布拉迪斯拉发",
  Bremen: "不来梅",
  Brescia: "布雷西亚",
  "Brighton & Hove": "布赖顿",
  Brindisi: "布林迪西",
  Bristol: "布里斯托尔",
  "Brod-Posavina": "布罗德 - 波萨维纳",
  BRYANSK: "布良斯克",
  Buckinghamshire: "白金汉",
  Bucuresti: "布加勒斯特",
  Budapest: "布达佩斯",
  "Buenos Aires": "布宜诺斯艾利斯",
  BUKIDNON: "布基农",
  BULACAN: "布拉干",
  Burdur: "布尔杜尔",
  Burgas: "布尔加斯",
  Burgenland: "布尔根兰州",
  Burgos: "布尔戈斯",
  Bursa: "囊",
  BURYATIYA: "布里亚特",
  "Buskerud Fylke": "布斯克吕郡",
  Buzau: "布泽乌",
  Bydgoszcz: "比得哥什",
  CA: "加州",
  Caceres: "卡塞雷斯",
  Cadiz: "加迪斯",
  CAGAYAN: "卡加延",
  "Cagayan Valley": "卡加延河谷",
  Cagliari: "卡利亚里",
  Cahul: "卡胡尔",
  Cairo: "开罗",
  Caithness: "凯斯内斯",
  Cajamarca: "卡哈马卡",
  Calarasi: "克勒拉希",
  Caldas: "卡尔达斯",
  Calvados: "卡尔瓦多斯",
  "CAMARINES NORTE": "卡马里内斯NORTE",
  "CAMARINES SUR": "卡马里内斯SUR",
  Cambridgeshire: "剑桥",
  CAMIGUIN: "甘米银",
  Campeche: "坎佩切",
  Campobasso: "坎波巴索",
  Canakkale: "恰纳卡莱",
  Cankiri: "昌克勒",
  Cantabria: "坎塔布里亚",
  Cantal: "康塔尔",
  Canterbury: "坎特伯雷",
  Capetown: "开普敦",
  CAPIZ: "卡皮斯",
  Caqueta: "卡克塔",
  Carabobo: "卡拉沃沃",
  Caracas: "加拉加斯",
  "Caras-Severin": "卡拉什 - 塞维林",
  Carlow: "卡洛",
  Carrickfergus: "卡里克弗",
  Casanare: "卡萨纳雷",
  Caserta: "卡塞塔",
  Castellon: "卡斯特利翁",
  "CASTELO BRANCO": "布朗库堡",
  Castlereagh: "卡斯尔雷",
  Catamarca: "卡塔马卡",
  CATANDUANES: "卡坦端内斯",
  Catania: "卡塔尼亚",
  Catanzaro: "卡坦扎罗",
  Cauca: "考卡",
  CAVITE: "甲米地",
  "Ceadir-Lunga": "ceadir-伦加",
  Ceara: "塞阿拉",
  CEBU: "宿务",
  Celje: "采列",
  Central: "中央",
  "Central Luzon": "吕宋岛中部",
  "Central Visayas": "中部米沙鄢",
  Cesar: "塞萨尔",
  CH: "昌迪加尔",
  Chachoengsao: "北柳",
  Chaco: "查科",
  "Chai Nat": "湾仔纳特",
  "Chakassky Republic": "chakassky共和国",
  "Changhua County": "彰化县",
  Chanthaburi: "尖竹汶府",
  "Chanti-Mansyjsky Aut": "阐提-Mansyjsky AUT",
  Charente: "夏朗德",
  "Charente-Maritime": "滨海夏朗德",
  "CHECHENO-INGUSHETIA": "CHECHENO  - 印古什",
  CHECHNYA: "车臣",
  CHELYABINSK: "车里雅宾斯克",
  Cher: "雪儿",
  Cheshire: "柴",
  "Chiang Mai": "清迈",
  "Chiang Rai": "清莱",
  Chiapas: "恰帕斯州",
  "Chiayi City": "嘉义市",
  "Chiayi County": "嘉义县",
  Chieti: "基耶蒂",
  CHIOU: "陈郁秀",
  Chisinau: "基希讷乌",
  Choco: "乔科",
  "Chon Buri": "春武里",
  Chongqing: "重庆",
  Chubut: "丘布特",
  CHUKOT: "楚克奇",
  "Chukotka Auton. dist": "楚科奇王文浩。区",
  Chumphon: "春蓬",
  CHUVASHIA: "楚瓦什",
  "Ciudad Real": "雷阿尔城",
  Clare: "克莱尔",
  Cleveland: "克利夫兰",
  Cluj: "克卢日",
  Clwyd: "克卢伊德",
  "Cntrl Mindanao": "CNTRL棉兰老岛",
  CO: "科罗拉多州",
  Coahuila: "科阿韦拉",
  COIMBRA: "科英布拉",
  Cojedes: "科赫德斯",
  Coleraine: "科尔雷恩",
  Colima: "科利马",
  Como: "科莫",
  Constanta: "康斯坦察",
  Cookstown: "库克斯敦",
  Copenhagen: "哥本哈根",
  Coquimbo: "科金博",
  Cordoba: "科尔多瓦",
  Corinthia: "科林西亚",
  Cork: "软木",
  Cornwall: "康沃尔",
  Correze: "科雷兹",
  Corrientes: "科连特斯",
  "Corse-du-Nord": "科西嘉 - 杜北",
  "Corse-du-Sud": "科西嘉 - 杜 - 南基",
  Corum: "昆仑",
  Cosenza: "科森扎",
  COTABATO: "哥打巴托",
  "Cote-d Or": "科特迪瓦-D或",
  "Cotes-d Armor": "柯特斯-ð护甲",
  "Cova da Beira": "科瓦达贝拉",
  Craigavon: "克雷加文",
  Cremona: "克雷莫纳",
  Creuse: "克勒兹",
  Crotone: "克罗托",
  CT: "康涅狄格",
  CT: "恰蒂斯加尔邦",
  Cuenca: "昆卡",
  Cumbria: "坎布里亚",
  Cundinamarca: "昆迪纳马卡",
  Cuneo: "库尼奥",
  Cuzco: "库斯科",
  Czestochowa: "琴斯托霍瓦",
  DAGESTAN: "达吉斯坦",
  "Dalarnas Län": "达拉纳兰",
  "Dar-es-Salaam": "达ES-达累斯萨拉姆",
  Darlington: "达灵顿",
  DAVAO: "达沃",
  "DAVAO DEL NORTE": "达沃城北",
  "DAVAO DEL SUR": "达沃DEL，起动率",
  "DAVAO ORIENTAL": "达沃东方",
  DC: "哥伦比亚特区",
  DD: "达曼和第乌",
  DE: "特拉华州",
  Debrecen: "德布勒森",
  "Delta Amacuro": "阿马库罗三角洲",
  Denizli: "代尼兹利",
  Derbyshire: "德比郡",
  Devon: "德文",
  "DI Aceh Aceh": "迪亚齐省亚齐",
  "DI Yogyakarta Yogyak": "迪日惹Yogyak",
  "Distrito Especial": "distrito特",
  "Distrito Federal": "联邦区",
  Diyarbakir: "迪亚巴克尔",
  "DKI Jakarta Jakarta": "DKI的雅加达雅加达",
  DL: "新德里",
  DN: "达德拉和纳加尔哈维有",
  Dolj: "多尔日",
  Donegal: "多尼戈尔",
  Dordogne: "多尔多涅",
  Dorset: "赛特",
  Doubs: "杜省",
  Douro: "杜罗",
  Down: "向下",
  DRAMAS: "电视剧",
  Drenthe: "德伦特",
  Drome: "德龙",
  Dubasari: "杜伯萨里",
  Dublin: "都柏林",
  "Dubrovnik-Neretva": "杜布罗夫尼克 - 内雷特瓦",
  "Dumfries a. Galloway": "邓弗里斯1。加洛韦",
  Dumfriesshire: "邓弗里斯郡",
  Dunaujvaros: "多瑙新城",
  Dunbartonshire: "邓巴顿郡",
  Dungannon: "邓甘嫩",
  Durango: "杜兰戈",
  Durham: "达勒姆",
  "East Lothian": "东洛锡安",
  "East Riding": "东部骑马",
  "East Sussex": "东萨塞克斯",
  "Eastern Cape": "东开普省",
  "EASTERN SAMAR": "东萨马",
  "Eastern Visayas": "东米沙鄢",
  Edirne: "埃迪尔",
  Eger: "埃格尔",
  Elazig: "埃拉泽",
  Elblag: "埃尔布隆格",
  Enna: "恩纳",
  "Entre Douro e Vouga": "恩特雷里奥斯杜罗éVouga",
  "Entre Rios": "恩特雷里奥斯",
  Erzincan: "埃尔津詹",
  Erzurum: "埃尔祖鲁姆",
  Eskisehir: "埃斯基谢希尔",
  "Espirito Santo": "圣埃斯皮里图州",
  Essex: "埃塞克斯",
  Essonne: "埃松",
  "Estado de Mexico": "墨西哥州",
  "Etelä-Suomi": "etelä，芬兰语",
  Eure: "厄尔",
  "Eure-et-Loir": "厄尔 -  ET-卢瓦尔",
  EVORA: "埃武拉",
  Falcon: "鹘",
  FARO: "法如国际贸易",
  Fejer: "的Fejer",
  Fermanagh: "弗马纳",
  Ferrara: "费拉拉",
  Fife: "法伊夫",
  Finistere: "菲尼斯泰尔",
  "Finnmark Fylke": "芬马克郡",
  Firenze: "佛罗伦萨",
  FL: "佛罗里达",
  Flevoland: "弗莱福兰",
  Foggia: "福贾",
  Forli: "弗利",
  Formosa: "台塑",
  "Frederiksborg amt": "菲德烈AMT",
  Fribourg: "弗里堡",
  Friesland: "弗里斯兰",
  Frosinone: "费辛隆尼",
  Fujian: "福建",
  "Fyn amt": "菲英岛AMT",
  GA: "果阿",
  GA: "格鲁吉亚",
  Galati: "加拉茨",
  Galway: "戈尔韦",
  Gansu: "甘肃",
  Gard: "加尔",
  "Garonne (Haute)": "加龙河（高级）",
  Gauteng: "电话",
  "Gävleborgs Län": "耶夫勒堡省",
  Gaziantep: "加济安泰普",
  Gdansk: "格但斯克",
  Gelderland: "海尔德兰",
  Geneva: "日内瓦",
  Genova: "热那亚",
  Gerona: "赫罗纳",
  Gers: "蒙古包",
  Giresun: "吉雷松",
  Gironde: "吉伦特",
  Giurgiu: "久尔久",
  GJ: "古吉拉特邦",
  Glarus: "格拉鲁斯",
  Gloucestershire: "格洛斯特",
  Goias: "戈亚斯",
  Gorizia: "戈里齐亚",
  Gorj: "戈尔日",
  "Gotlands Län": "gotlands兰",
  Grampian: "嘉林",
  Granada: "格拉纳达",
  Graubuenden: "格劳宾登州",
  "Greater London": "大伦敦",
  "Greater Manchester": "大曼彻斯特",
  Groningen: "格罗宁根",
  "Grønlands amt": "grønlandsAMT",
  Grosseto: "格罗塞托",
  GU: "关岛",
  Guadalajara: "瓜达拉哈拉",
  Guanajuato: "瓜纳华托",
  Guangdong: "广东",
  Guangxi: "广西",
  GUARDA: "瓜尔达",
  Guarico: "瓜里科",
  Guaviare: "瓜维亚雷",
  Guerrero: "格雷罗",
  GUIMARAS: "吉马拉斯",
  Guipuzcoa: "吉普斯夸",
  Guizhou: "贵州",
  GUMUSHANE: "居米什哈内",
  Guyane: "圭亚那",
  Gwent: "格温特",
  Gwynedd: "圭内斯",
  Gyor: "杰尔",
  "Gyor-Moson-Sopron": "杰尔的Moson-索普隆",
  Haifa: "海法",
  Hainan: "海南",
  Hainaut: "埃诺",
  "Hajdu-Bihar": "豪伊杜 - 比哈尔",
  Hakkari: "哈卡里",
  "Hallands Län": "哈兰兰",
  Halton: "哈尔顿",
  Hamburg: "汉堡",
  Hampshire: "新罕布什尔州",
  Hanoi: "河内",
  Hartlepool: "哈特尔普尔",
  Hatay: "哈塔伊",
  "Haut-Rhin": "上莱茵省",
  "HAUTE-CORSE": "上科西嘉",
  "Hauts-de-Seine": "hauts德塞纳",
  "Hawke´s Bay": "霍克斯湾",
  Hebei: "河北",
  "Hedmark Fylke": "海德马克郡",
  Heilongjiang: "黑龙江",
  Henan: "河南",
  Herault: "埃罗",
  "Hereford and Worcs.": "Hereford和Worcs。",
  Herefordshire: "赫里福德",
  Hertfordshire: "赫特福德郡",
  Hessen: "黑森州",
  Heves: "赫维什",
  HI: "夏威夷",
  Hidalgo: "伊达尔戈",
  Highland: "高原",
  "Highlands-Altay Rep.": "阿尔泰共和国高地",
  "Hong Kong Island": "香港岛",
  "Hordaland Fylke": "霍达兰郡",
  "Hors-France": "开胃法国",
  HP: "喜马偕尔邦",
  HR: "哈里亚纳邦",
  "Hrastnik Lasko": "hrastnik洛什科",
  "Hsinchu City": "新竹市",
  "Hsinchu County": "新竹县",
  "Hualien County": "花莲县",
  Huancavelica: "万卡维利卡",
  HUANUCO: "瓦努科",
  Hubei: "湖北",
  Huelva: "韦尔瓦",
  Huesca: "韦斯卡",
  Huila: "威拉",
  Humberside: "亨伯赛德",
  Hunan: "湖南",
  Hunedoara: "胡内多阿拉",
  IA: "爱荷华州",
  Ialomita: "雅洛米察",
  Iasi: "雅西",
  Ica: "伊卡",
  ID: "爱达荷州",
  IFUGAO: "伊富高",
  IL: "伊利诺伊州",
  "ILHA DA GRACIOSA": "伊利亚的DA格拉西奥萨",
  "ILHA DA MADEIRA": "伊利亚的DA马德拉",
  "ILHA DAS FLORES": "伊利亚DAS的弗洛雷斯",
  "ILHA DE PORTO SANTO": "青洲德圣港",
  "ILHA DE SANTA MARIA": "青洲德桑塔玛丽亚",
  "ILHA DE SAO JORGE": "青洲德圣乔治",
  "ILHA DE SAO MIGUEL": "青洲德圣米格尔",
  "ILHA DO CORVO": "伊利亚DO的Corvo矿",
  "ILHA DO FAIAL": "伊利亚溶解氧法亚尔",
  "ILHA DO PICO": "伊利亚溶解氧笔克",
  "ILHA TERCEIRA": "伊利亚特塞拉",
  "Ilirska Bistrica": "ilirska比斯特里察",
  "Ille-et-Vilaine": "伊勒 - 维莱讷省",
  Ilocos: "伊罗戈",
  "ILOCOS NORTE": "北伊罗戈",
  "ILOCOS SUR": "南伊罗戈",
  ILOILO: "伊洛伊洛",
  Imperia: "因佩里亚",
  IN: "印地安那",
  Indre: "安德尔",
  "Indre-et-Loire": "安德尔 - 卢瓦尔省",
  "Ingushetija Republic": "ingushetija共和国",
  "Inverness-Shire": "因弗内斯郡",
  "Irian Jaya Irian Jay": "伊里安查亚伊里安查周杰伦",
  Irkutsk: "伊尔库茨克",
  ISABELA: "伊莎贝拉",
  Isere: "伊泽尔",
  Isernia: "伊塞尔尼亚",
  Islamabad: "伊斯兰堡",
  "Isle Of Arran": "远祖艾伦",
  "Isle Of Barra": "远祖巴拉",
  "Isle Of Benbecula": "远祖的本贝丘拉岛",
  "Isle Of Bute": "远祖弼",
  "Isle Of Canna": "远祖的美人蕉",
  "Isle Of Coll": "远祖的科尔",
  "Isle Of Colonsay": "远祖的Colonsay",
  "Isle Of Cumbrae": "远祖的Cumbrae",
  "Isle Of Eigg": "远祖的Eigg",
  "Isle Of Gigha": "远祖的Gigha",
  "Isle Of Harris": "远祖哈里斯",
  "Isle Of Iona": "远祖的艾奥娜",
  "Isle Of Islay": "远祖的艾莱",
  "Isle Of Jura": "远祖汝拉",
  "Isle Of Lewis": "远祖刘易斯",
  "Isle Of Mull": "远祖马尔",
  "Isle Of North Uist": "岛的北部Uist",
  "Isle Of Rum": "远祖的朗姆酒",
  "Isle Of Scalpay": "远祖的Scalpay",
  "Isle Of Skye": "斯凯岛",
  "Isle Of South Uist": "岛南Uist",
  "Isle Of Tiree": "远祖的Tiree",
  "Isle of Wight": "怀特岛",
  "Isles Of Scilly": "岛的锡利",
  Isparta: "伊斯帕尔塔",
  Istanbul: "伊斯坦布尔",
  "Itä-Suomi": "ITA-芬兰语",
  "IVANO-FRANKIVSKA": "伊万诺 -  FRANKIVSKA",
  IVANOV: "伊万诺夫",
  Izmir: "伊兹密尔",
  Izola: "伊佐拉",
  Jaen: "哈恩",
  Jalisco: "哈利斯科",
  "Jambi Jambi": "占碑占碑",
  "Jämtlands Län": "jämtlands兰",
  "Jasz-Nagykun-Szolnok": "亚斯 - 纳杰孔 - 索尔诺克",
  "Jawa Barat West Java": "西爪哇爪哇巴拉",
  "Jawa Tengah Central": "爪哇登加中",
  "Jawa Timur East Java": "东爪哇爪哇帖木儿",
  Jerusalem: "耶路撒冷",
  JH: "贾坎德邦",
  Jiangsu: "江苏",
  Jiangxi: "江西",
  Jihocesky: "南捷克",
  Jilin: "吉林",
  JK: "查谟和克什米尔",
  Johannesburg: "约翰内斯堡",
  Johor: "柔佛",
  "Jönköpings Län": "延雪平岚",
  "Jost Van Dyke": "约斯特范",
  Jujuy: "胡胡伊",
  JUNIN: "胡宁",
  Jura: "朱拉",
  KA: "卡纳塔克邦",
  "KABARDINO-BALKARIA": "卡巴尔达 - 巴尔卡尔",
  "KAHRAMAN MARAS": "KAHRAMAN马拉什",
  Kalasin: "加拉信",
  "Kalimantan Barat Wes": "加里曼丹巴拉韦斯",
  "Kalimantan Selatan S": "加里曼丹Selatan小号",
  "Kalimantan Tengah Ce": "加里曼丹登加CE",
  "Kalimantan Timur Eas": "加里曼丹帖木儿大通",
  KALINGA: "卡林加",
  KALININGRAD: "加里宁格勒",
  Kalisz: "卡利什",
  "Kalmar Län": "卡尔马兰",
  KALMYKIYA: "卡尔梅克",
  KALUGA: "卡卢加",
  KALUZHSKAYA: "卡卢加州",
  Kamnik: "卡姆尼克",
  "Kamphaeng Phet": "甘烹碧",
  Kanchanaburi: "北碧府",
  "Kaohsiung City": "高雄市",
  "KARACHAY-CHERKESSIA": "卡拉恰伊 - 切尔克斯",
  Karaman: "卡拉曼",
  KARELIA: "卡累利阿",
  Karlovac: "卡尔洛瓦茨",
  Kars: "卡尔斯",
  Kashmir: "克什米尔",
  Kastamonu: "卡斯塔莫努",
  Katowice: "卡托维兹",
  Kavan: "扬·卡万",
  Kayseri: "开塞利",
  Kecskemet: "凯奇凯梅特",
  Kedah: "吉打州",
  "Keelung City": "基隆市",
  Kelantan: "吉兰丹州",
  Kent: "肯特",
  Kerry: "黑色的小乳牛",
  Khabarovsk: "哈巴罗夫斯克",
  "Khon Kaen": "孔敬",
  Khyber: "开伯尔",
  Kildare: "基尔代尔",
  KILIS: "基利斯",
  Kilkenny: "基尔肯尼",
  Kilkis: "基尔基斯",
  "Kingston-Upon-Hull": "金斯敦 - 赫尔",
  "Kinmen County": "金门县",
  Kirikkale: "克里卡尔",
  Kirklareli: "克尔克拉雷利",
  KIROV: "基洛夫",
  KL: "喀拉拉邦",
  "København amt": "哥本哈根AMT",
  Kocaeli: "科贾埃利",
  "Komarom-Esztergom": "科马罗姆 - 埃斯泰尔戈姆",
  Konya: "科尼亚",
  Koper: "科佩尔",
  "Koprivnica-Krizevci": "科普里夫尼察，Krizevci",
  Kowloon: "九龙",
  Krabi: "喀比",
  Krakow: "克拉科夫",
  Kranj: "克拉尼",
  KRASNODAR: "克拉斯诺达尔",
  KRASNOYARSK: "克拉斯诺亚尔斯克",
  "Kronobergs Län": "kronobergs兰",
  "Krung Thep": "泰京银行Thep",
  KS: "堪萨斯",
  "Kuala-Lumpur": "吉隆坡 - 吉隆坡",
  KURGAN: "库尔干",
  KURSK: "库尔斯克",
  KUTAHYA: "屈塔希亚",
  "Kwazulu/Natal": "夸祖鲁/纳塔尔",
  KY: "肯塔基州",
  "L Aquila": "大号拉奎拉",
  LA: "路易斯安那州",
  "La Coruña": "拉科鲁尼亚",
  "La Guajira": "拉瓜希拉",
  "La Libertad": "拉利伯塔德",
  "La Pampa": "拉潘帕",
  "La Rioja": "拉里奥哈",
  "La Spezia": "拉斯佩齐亚",
  "LA UNION": "拉乌尼翁",
  Labuan: "纳闽",
  LAD: "拉达克",
  LAGUNA: "丽",
  Lambayeque: "兰巴耶克",
  Lampang: "南邦",
  Lamphun: "南奔",
  "Lampung Lampung": "楠榜省楠榜",
  "LANAO DEL NORTE": "北拉瑙",
  "LANAO DEL SUR": "南拉瑙",
  Lanarkshire: "拉纳克",
  Lancashire: "兰开夏郡",
  Landes: "兰德斯",
  "Länsi-Suomi": "蓝丝，芬兰语",
  Laois: "崂",
  Lara: "拉拉",
  Larne: "拉恩",
  "Las Palmas": "拉斯帕尔马斯",
  Latina: "拉提纳",
  LD: "拉克沙群岛",
  Lecce: "莱切",
  Lecco: "莱科",
  Legnica: "莱格尼察",
  "Leicester City": "莱切斯特城",
  Leicestershire: "莱斯特",
  LEIRIA: "莱里亚",
  Leitrim: "利特里姆",
  Lendava: "伦达瓦",
  LENINGRADSKAYA: "列宁格勒",
  Leon: "莱昂",
  Lerida: "莱里达",
  LEYTE: "莱特",
  "Lianjiang County": "连江县",
  Liaoning: "辽宁",
  Libertador: "解放者",
  Liege: "列日",
  "Lika-Senj": "利卡-Senj",
  Lillehammer: "利勒哈默尔",
  LIMA: "利马",
  Limavady: "利马瓦迪",
  Limburg: "林堡",
  Limerick: "五行打油诗",
  Lincolnshire: "林肯郡",
  LIPETSK: "利佩茨克",
  Lisboa: "葡京",
  Lisburn: "利斯",
  Livorno: "利沃诺",
  "Ljubljana-Bezigrad": "卢布尔雅那 -  Bezigrad",
  "Ljubljana-Center": "卢布尔雅那的中心",
  "Ljubljana-Moste-Polj": "的卢布尔雅那-Moste-Polj",
  "Ljubljana-Siska": "卢布尔雅那 -  Siska",
  "Ljubljana-Vic-Rudnik": "卢布尔雅那-VIC-鲁德尼克",
  Lodi: "洛迪",
  LODZKIE: "罗兹",
  Loei: "黎",
  "Loir-et-Cher": "卢瓦尔 - 谢尔",
  Loire: "卢瓦尔河",
  "Loire (Haute)": "卢瓦尔（高级）",
  "Loire-Atlantique": "卢瓦尔河 - 大西洋",
  Loiret: "卢瓦雷",
  London: "伦敦",
  Londonderry: "伦敦德里",
  Longford: "朗福德",
  "Lop Buri": "华富里",
  Loreto: "洛雷托",
  "Los Lagos": "洛斯拉戈斯",
  Lot: "很多",
  "Lot-et-Garonne": "很多-ET-龙河",
  Lothian: "洛锡安",
  Louth: "劳斯",
  "Lower Austria": "下奥地利州",
  Lozere: "洛泽尔",
  LUBELSKIE: "卢布林",
  Lublin: "卢布林",
  Lucca: "卢卡",
  LUCENA: "卢塞纳",
  Lucerne: "卢塞恩",
  Lugo: "卢戈",
  Luton: "卢顿",
  Luxembourg: "卢森堡",
  MA: "美国马萨诸塞州",
  Macerata: "马切拉塔",
  "MADRE DE DIOS": "马德雷德迪奥斯",
  Madrid: "马德里",
  "Mae Hong Son": "湄宏顺",
  MAGADAN: "马加丹",
  Magdalena: "马格达莱纳",
  Magherafelt: "马拉费尔特",
  MAGUINDANAO: "马京达瑙省",
  "Maha Sarakham": "玛哈Sarakham",
  "Maine-et-Loire": "缅因州卢瓦尔省",
  Malaga: "马拉加",
  Malatya: "马拉蒂亚",
  "Maluku Maluku": "马鲁古省马鲁古",
  "Malvinas/Falkland Is": "马尔维纳斯/福克兰",
  "Manawatu-Wanganui": "玛纳瓦图旺格努伊",
  Manche: "芒",
  MANILA: "新华社马尼拉",
  Manisa: "马尼萨",
  Mantova: "曼托瓦",
  Maramures: "马拉穆列什",
  Maranhao: "马拉尼昂州",
  Mardin: "马尔丁",
  "MARI EL": "MARI的EL",
  Maribor: "马里博尔",
  "Marijskaya Republic": "marijskaya共和国",
  MARINDUQUE: "马林杜克",
  Marne: "马恩",
  "Marne (Haute)": "马恩（高级）",
  "Masa Carrara": "马萨卡拉拉",
  Matera: "马泰拉",
  "Mato Grosso": "马托格罗索",
  "Mato Grosso do Sul": "南马托格罗索",
  Maule: "马乌莱",
  Mayenne: "马耶讷",
  Mayo: "梅奥",
  MB: "马尼托巴",
  MD: "马里兰",
  ME: "缅因州",
  Meath: "米斯",
  "Mecklenburg-Vorpommern": "梅克伦堡 - 前波莫瑞",
  "Médio Tejo": "Medio的特茹",
  Melaka: "马六甲",
  Mendoza: "门多萨",
  Merida: "梅里达",
  Merseyside: "默西塞德郡",
  Messina: "墨西拿",
  Meta: "元",
  "Metro Manila": "马尼拉",
  "Meurthe-et-Moselle": "默尔特 - 摩泽尔省",
  Meuse: "默兹",
  MH: "马哈拉施特拉邦",
  MI: "密歇根",
  "Miaoli County": "苗栗县",
  Michoacan: "米却肯",
  "Mid Glamorgan": "中旬Glamorgan的",
  Middlesbrough: "米德尔斯堡",
  Middlesex: "米德尔塞克斯",
  Midlothian: "洛锡安",
  MILANO: "米兰",
  "Milton Keynes": "米尔顿凯恩斯",
  "Minas Gerais": "米纳斯吉拉斯州",
  "MINDORO OCCIDENTAL": "民都洛西洋",
  "MINDORO ORIENTAL": "民都洛东方",
  Miranda: "米兰达",
  "MISAMIS OCCIDENTAL": "西米萨米斯",
  "MISAMIS ORIENTAL": "东米萨米斯",
  Misiones: "米西奥内斯",
  Miskolc: "米什科尔茨",
  ML: "梅加拉亚邦",
  MN: "明尼苏达州",
  MN: "曼尼普尔邦",
  MO: "密苏里州",
  Modena: "摩德纳",
  Monagas: "莫纳加斯",
  Monaghan: "莫纳汉",
  Montana: "蒙大拿",
  Montevideo: "蒙得维的亚",
  Moquegua: "莫克瓜",
  Morbihan: "莫尔比昂",
  MORDOVIYA: "莫尔多维亚",
  "Møre og Romsdal F.": "更多OG鲁姆斯达尔楼",
  Morelos: "莫雷洛斯",
  Moscow: "莫斯科",
  Moselle: "摩泽尔",
  MOSKVA: "莫斯科",
  MOUNTAIN: "山",
  Moyle: "莫伊尔",
  MP: "中央邦",
  Mpumalanga: "姆普马兰加",
  MS: "密西西比河",
  Mugla: "穆拉",
  Mukdahan: "穆达汉",
  Murcia: "穆尔西亚",
  Mures: "穆列什",
  Murmansk: "摩尔曼斯克",
  "Murska Sobota": "murska博塔",
  MUS: "毛里求斯",
  MZ: "米佐拉姆",
  Nagykanizsa: "瑙吉考尼饶",
  Nairn: "奈伦",
  "Nakhon Nayok": "那空那育",
  "Nakhon Pathom": "佛统",
  "Nakhon Phanom": "那空拍侬",
  "Nakhon Ratchasima": "呵叻",
  "Nakhon Sawan": "那空沙旺",
  "Nakhon Si Thammarat": "洛坤府",
  Namur: "那慕尔",
  Nan: "南",
  "Nantou County": "南投县",
  Naples: "那不勒斯",
  Narathiwat: "那拉提瓦",
  Narino: "纳里尼奥",
  "NATIONAL CAPITAL REG": "国家资本金章第",
  Navarra: "纳瓦拉",
  Nayarit: "纳亚里特",
  NB: "新不伦瑞克省",
  NC: "北卡罗莱纳州",
  ND: "北达科他州",
  NE: "内布拉斯加州",
  Neamt: "亚姆茨",
  "Negeri Sembilan": "森美兰",
  "NEGROS OCCIDENTAL": "西内格罗斯",
  "NEGROS ORIENTAL": "内格罗斯东方",
  "Nei Mongol": "内蒙古",
  NENETS: "涅涅茨",
  Neuchatel: "纳沙泰尔",
  Neuquen: "内乌肯",
  NEVSEHIR: "内夫谢希尔",
  "New TaipeiCity": "新北市",
  "New Territories": "新界",
  Newbury: "纽伯里",
  "Newry and Mourne": "纽里和莫恩",
  Newtownabbey: "纽敦阿比",
  NH: "新罕布什尔州",
  Nidwalden: "瓦尔登",
  Niedersachsen: "下萨克森州",
  Nievre: "涅夫勒",
  Nigde: "尼代",
  Ningxia: "宁夏",
  NIZHEGORODSKAYA: "下诺夫哥罗德",
  NJ: "新泽西",
  NL: "纽芬兰",
  NL: "那加兰邦",
  NM: "新墨西哥",
  Nograd: "诺格拉德",
  "Nong Bua Lamphu": "农布阿欣欣向荣",
  "Nong Khai": "农凯",
  Nonthaburi: "暖武里府",
  "Noord-Brabant": "北布拉邦",
  "Noord-Holland": "北荷兰省",
  Nord: "诺德",
  "Nord-Trøndelag Fylk": "北特伦德拉格Fylk的",
  "Nordjylland amt": "北日德兰AMT",
  "Nordland Fylke": "诺尔兰郡",
  "Nordrhein-Westfalen": "北莱茵 - 威斯特法伦州",
  Norfolk: "诺福克",
  "Norrbottens Län": "norrbottens兰",
  "Norte de Santander": "北桑坦德",
  "NORTH COTABATO": "北哥打巴托",
  "North Down": "北唐",
  "North Humberside": "北亨伯赛德",
  "North Lincolnshire": "北林肯郡",
  "North Somerset": "北萨默塞特",
  "North Yorkshire": "北约克郡",
  "North-Osetiya Republ": "北Osetiya Republ的",
  "North-West": "西北",
  Northamptonshire: "北安普敦郡",
  Northern: "北方",
  "Northern Cape": "北开普省",
  "Northern Mindanao": "北棉兰老岛",
  "Northern Province": "北方省",
  "NORTHERN SAMAR": "北方SAMAR",
  Northland: "北国",
  Northumberland: "诺森伯兰",
  "Nottingham City": "诺丁汉市",
  Nottinghamshire: "诺丁汉",
  "Nova Gorica": "新戈里察",
  Novara: "诺瓦拉",
  NOVGOROD: "诺夫哥罗德",
  "Novo Mesto": "新梅斯托",
  NOVOSIBIRSK: "新西伯利亚",
  "Nowy Sacz": "的Nowy松奇",
  NS: "新斯科舍省",
  NSW: "新南威尔士州",
  NT: "北领地",
  NT: "西北地区",
  "NthEast Lincolnshire": "NthEast林肯郡",
  NU: "努纳武特地区",
  "NUEVA ECIJA": "新怡诗夏",
  "Nueva Esparta": "新埃斯帕塔",
  "NUEVA VIZCAYA": "新比斯开",
  "Nuevo Leon": "新莱昂州",
  Nuoro: "努奥罗",
  "Nusa Tenggara Barat": "努沙登加拉巴拉",
  "Nusa Tenggara Timur": "东努沙登加拉",
  NV: "内华达州",
  NY: "纽约",
  Nyiregyhaza: "尼赖吉哈佐",
  Oaxaca: "瓦哈卡",
  Obwalden: "瓦尔登",
  Oeste: "的Oeste",
  Offaly: "奥法利",
  OH: "俄亥俄州",
  Oise: "瓦兹",
  OK: "俄克拉何马",
  OLONGAPO: "加波",
  Olsztyn: "奥尔什丁",
  Omagh: "奥马",
  ON: "安大略省",
  OPOLSKIE: "奥波莱",
  "Oppland Fylke": "奥普兰郡",
  OR: "俄勒冈州",
  Ordu: "奥尔杜",
  "Örebro Län": "厄勒布鲁",
  ORENBURG: "奥伦堡",
  Orense: "奥伦塞",
  Oristano: "奥里斯塔诺",
  Orkney: "奥克尼",
  ORLOVSKAYA: "奥廖尔",
  Orne: "奥恩",
  "Osijek-Baranja": "奥西耶克 - 巴拉尼亚",
  Oslo: "奥斯陆",
  "Östergötlands Län": "东约特兰",
  "Østfold Fylke": "东福尔郡",
  Otago: "奥塔哥",
  Oulu: "奥卢",
  Overijssel: "上艾瑟尔",
  Oxfordshire: "牛津",
  PA: "宾夕法尼亚州",
  Padova: "帕多瓦",
  Pahang: "彭亨",
  PALAWAN: "巴拉望",
  Palencia: "帕伦西亚",
  Palermo: "巴勒莫",
  PAMPANGA: "邦板牙",
  PANGASINAN: "邦阿西楠",
  Para: "第",
  Paraiba: "帕拉伊巴",
  Parana: "巴拉那",
  Paris: "巴黎",
  Parma: "帕尔马",
  "Pas-de-Calais": "PAS-DE-加莱",
  Pasco: "帕斯科",
  "Pathum Thani": "巴吞他尼",
  Pattani: "北大",
  Pavia: "帕维亚",
  PB: "旁遮普",
  PE: "爱德华王子岛",
  Pecs: "佩奇",
  "Penghu County": "澎湖县",
  PENZA: "奔萨",
  Perak: "霹雳",
  Perlis: "玻璃市",
  PERM: "烫发",
  Pernambuco: "伯南布哥",
  Perthshire: "佩思",
  Perugia: "佩鲁贾",
  Pesaro: "佩萨罗",
  Pescara: "佩斯卡拉",
  Pest: "害虫",
  Peterborough: "彼得伯勒",
  Phangnga: "攀牙",
  Phatthalung: "好在Phatthalung",
  Phayao: "帕尧",
  Phetchabun: "碧差汶",
  Phetchaburi: "碧武里",
  Phichit: "披集府",
  Phitsanulok: "彭世洛",
  "PHRA NAKHON SI AYUTT": "帕那空司AYUTT",
  Phrae: "帕府",
  Phuket: "普吉岛",
  Piacenza: "皮亚琴察",
  Piaui: "皮奥伊",
  Pila: "皮拉",
  "Pingtung County": "屏东县",
  "Pinhal Interior N.": "皮尼亚尔内政部N.",
  "Pinhal Interior Sul": "皮尼亚尔内政部扎",
  Piran: "皮兰",
  Pisa: "比萨",
  Pistoia: "皮斯托亚",
  Piura: "皮乌拉",
  Plock: "普沃茨克",
  Plymouth: "普利茅斯",
  Pontevedra: "庞特维德拉",
  Poole: "普尔",
  Pordenone: "波代诺",
  PORTALEGRE: "波塔莱格雷",
  PORTO: "波尔图",
  Portsmouth: "朴茨茅斯",
  Portuguesa: "波图格萨",
  Postojna: "波斯托伊纳",
  Potenza: "波坦察",
  Powys: "波伊斯",
  Poznan: "波兹南",
  PR: "波多黎各",
  "Prachin Buri": "巴真武里",
  "PRACHUAP KHIRI KHAN": "巴蜀KHIRI汗",
  Praha: "布拉格",
  Prahova: "普拉霍瓦",
  Prato: "普拉托",
  "Primorje-Gorski Kot.": "Primorje的Gorski葛",
  PRIMORSKIY: "滨海",
  Przemysl: "普热梅希尔",
  PSKOV: "普斯科夫",
  Puebla: "普埃布拉",
  "Pulau Pinang": "槟城",
  Puno: "普诺",
  Putumayo: "普图马约",
  "Puy-de-Dôme": "多姆德圆顶",
  PW: "帕劳",
  PY: "Pondicherry的",
  "Pyrenees (Hautes)": "比利牛斯省（Hautes）",
  "Pyrenees-Atlantiques": "比利牛斯 - 大西洋",
  "Pyrenees-Orientales": "比利牛斯 -  Orientales",
  QC: "魁北克",
  Qinghai: "青海",
  QLD: "昆士兰",
  "Quarry Bay": "鲗鱼涌",
  Queretaro: "克雷塔罗",
  QUEZON: "奎松",
  Quindio: "金迪奥",
  QUIRINO: "基里诺",
  Quito: "基多",
  "Ra's al Khaymah": "RA的人Khaymah",
  Radom: "拉多姆",
  Ragusa: "拉古萨",
  RANONG: "拉廊",
  Ravenna: "拉韦纳",
  "Ravne Na Koroskem": "ravne娜Koroskem",
  RAYONG: "罗勇",
  Reading: "阅读",
  "Redcar and Cleveland": "雷德卡和克利夫兰",
  "Reggio Calabria": "雷焦卡拉布里亚",
  "Reggio Emilia": "瑞吉欧",
  "Region Metropolitana": "地区大都会",
  Renfrewshire: "伦弗鲁",
  "Rep di San Marino": "声望迪圣马力诺",
  Réunion: "留尼汪",
  "Rheinland-Pfalz": "莱茵兰 - 普法尔茨州",
  Rhone: "罗纳",
  RI: "罗德岛",
  "Riau Riau": "廖内里奥",
  Rimini: "里米尼",
  "Ringkøbing amt": "灵克宾AMT",
  "Rio De Janeiro": "里约热内卢",
  "Rio Grande de Norte": "德北里奥格兰德",
  "Rio Grande do Sul": "南里奥格兰德州",
  "Rio Negro": "里奥内格罗",
  Risaralda: "里萨拉尔达",
  RIZAL: "黎刹",
  Rize: "里泽",
  RJ: "拉贾斯坦邦",
  "Rochester Up. Medway": "罗切斯特最多。梅德韦",
  "Rogaland Fylke": "罗加兰郡",
  "ROI ET": "投资回报率的ET",
  ROMBLON: "朗布隆",
  Rome: "罗马",
  Rondonia: "朗多尼亚",
  Roraima: "罗赖马",
  "Roskilde amt": "罗斯基勒AMT",
  "Ross-Shire": "罗斯郡",
  ROSTOV: "罗斯托夫",
  Rovigo: "罗维戈",
  Ruse: "骗术",
  Rutland: "拉特兰",
  RYAZAN: "梁赞",
  Rzeszow: "热舒夫",
  SA: "南澳大利亚",
  "Sa Kaeo": "沙缴",
  Saarland: "萨尔",
  Sabah: "沙巴",
  Sachsen: "萨克森",
  "Sachsen-Anhalt": "萨克森 - 安哈尔特州",
  Sakarya: "萨卡里亚",
  SAKHA: "萨哈",
  SAKHALIN: "萨哈林",
  "SAKON NAKHON": "左近呵",
  Salamanca: "萨拉曼卡",
  Salerno: "萨莱诺",
  Salta: "萨尔塔",
  Salzburg: "萨尔茨堡",
  SAMARA: "萨马拉",
  Samsun: "萨姆松",
  "SAMUT PRAKAN": "北榄",
  "SAMUT SAKHON": "沙木沙空",
  "SAMUT SONGKHRAM": "沙木堪",
  "San Anders de Provi:": "圣安德斯·Provi：",
  "San Juan": "圣胡安",
  "San Luis": "圣路易斯",
  "San Luis Potosi": "圣路易斯波托西",
  "San Martín": "圣马丁",
  SANLIURFA: "桑尼乌法",
  "Santa Catarina": "圣卡塔琳娜",
  "Santa Cruz": "圣克鲁斯",
  "Santa Fe": "圣达菲",
  Santander: "桑坦德",
  SANTAREM: "圣塔伦",
  Santiago: "圣地亚哥",
  "Santiago Del Estero": "圣地亚哥 - 德尔埃斯特罗",
  "Sao Paulo": "圣保罗",
  "Saone (Haute)": "索恩（高级）",
  "Saone-et-Loire": "索恩 - 卢瓦尔省",
  "SARA BURI": "萨拉武里",
  SARANGANI: "萨兰加尼",
  SARATOV: "萨拉托夫",
  Sarawak: "沙捞越",
  Sarthe: "萨尔特",
  Sassari: "萨萨里",
  "Satu Mare": "萨图马雷",
  SATUN: "沙敦",
  Savoie: "萨瓦",
  "Savoie (Haute)": "萨瓦（高级）",
  Savona: "萨沃纳",
  SC: "南卡罗来纳州",
  Schaffhausen: "沙夫豪森",
  "Schleswig-Holstein": "石勒苏益格 - 荷尔斯泰因",
  Scotland: "苏格兰",
  SD: "南达科他州",
  Segovia: "塞哥维亚",
  "Seine-et-Marne": "塞纳 - 马恩省",
  "Seine-Maritime": "滨海塞纳",
  "Seine-Saint-Denis": "塞纳 - 圣德尼",
  Selangor: "雪兰莪州",
  Select: "请选择",
  "Sentjur Pri Celju": "sentjur小学Celju",
  Sergipe: "塞尔希培",
  SETUBAL: "塞图巴尔",
  "Severo-Kazakhstansk": "北-Kazakhstansk",
  "SEVERO-OSETINSKAYA": "北-OSETINSKAYA",
  Sevilla: "塞维利亚",
  "Sevres (Deux)": "塞弗尔（德塞夫勒）",
  Shaanxi: "陕西",
  Shandong: "山东",
  Shanghai: "上海",
  Shanxi: "山西",
  Sharjah: "沙迦",
  Shetland: "设得兰群岛",
  Shropshire: "什罗普",
  Sibenik: "希贝尼克",
  Sibiu: "锡比乌",
  Sichuan: "四川",
  Siena: "锡耶纳",
  Siirt: "锡尔特",
  Sinaloa: "锡那罗亚",
  Sind: "信德",
  "SING BURI": "信武里",
  Singapore: "新加坡",
  Sinop: "锡诺普",
  SIQUIJOR: "锡基霍尔",
  Siracusa: "锡拉库萨",
  SIRNAK: "舍尔纳克",
  "Sisak-Moslavina": "西萨克-Moslavina",
  Sivas: "锡瓦斯",
  SK: "萨斯喀彻温省",
  SK: "锡金",
  "Skåne Län": "斯科纳",
  "Skofja Loka": "skofja洛卡",
  SLASKIE: "西里西亚",
  Slavonski: "斯拉沃尼亚",
  Sligo: "斯莱戈",
  Slough: "泥沼",
  "Slovenska Bistrica": "slovenska比斯特里察",
  Slupsk: "斯武普斯克",
  "Smarje Pri Jelsah": "smarje小学Jelsah",
  SMOLENSK: "斯摩棱斯克",
  "Södermanlands Län": "södermanlands兰",
  "Sogn og Fjordane F.": "松恩OG Fjordane楼",
  Solothurn: "索洛图恩",
  Somerset: "萨默塞特",
  Somme: "索姆",
  Somogy: "绍莫吉",
  "Sønderjylland amt": "南日德兰AMT",
  Sondrio: "松德里奥",
  SONGKHLA: "宋卡",
  Sonora: "索诺拉",
  Sopron: "索普隆",
  "Sør-Trøndelag Fylk": "SOR-拉格Fylk",
  Soria: "索里亚",
  SORSOGON: "索索贡",
  "SOUTH COTABATO": "南哥打巴托",
  "South Glamorgan": "南格拉摩根",
  "South Humberside": "南亨伯赛德",
  "South Luzon": "南吕宋岛",
  "South Mindanao": "南部棉兰老岛",
  "South Yorkshire": "南约克郡",
  Southampton: "南安普敦",
  Southend: "绍森德",
  Southern: "南部的",
  "SOUTHERN LEYTE": "南莱特",
  Southland: "南国",
  "Split-Dalmatia": "分裂的达尔马提亚",
  "St. Gallen": "圣加仑",
  "St. Petersburg": "圣彼得堡",
  "Sta. Cruz Tenerife": "站圣克鲁斯特内里费",
  "Stadt Zagreb": "STADT萨格勒布",
  Staffordshire: "斯塔福德",
  STAVROPOL: "斯塔夫罗波尔",
  "Stefan-Voda": "斯蒂芬 - 沃达",
  "Sth. Gloucestershire": "某物。格洛斯特",
  Stirlingshire: "斯特灵",
  "Stockholms Län": "斯德哥尔摩兰",
  "Stockton-on-Tees": "斯托克顿，T恤",
  "Storstrøm amt": "斯托AMT",
  Strabane: "斯特拉班",
  Strathclyde: "斯特拉斯克莱德",
  Styria: "施蒂利亚州",
  Suceava: "苏恰瓦",
  Sucre: "苏克雷",
  Suffolk: "萨福克",
  SUKHOTHAI: "素可泰",
  "Sulawesi Selatan Sou": "南苏拉威西叟",
  "Sulawesi Tengah Cent": "苏拉威西登加美分",
  "Sulawesi Tenggara So": "苏拉威西Tenggara所以",
  "Sulawesi Utara North": "北苏拉威西省Utara",
  "SULTAN KUDARAT": "苏丹库达拉",
  SULU: "苏鲁",
  "Sumatera Barat West": "西苏门答腊巴拉",
  "Sumatera Selatan Sou": "苏门答腊Selatan叟",
  "Sumatera Utara North": "北苏门答腊Utara",
  "SUPHAN BURI": "素攀武里",
  "SURAT THANI": "素叻他尼",
  SURIGAO: "苏里高",
  "SURIGAO DEL NORTE": "苏里高城北",
  "SURIGAO DEL SUR": "苏里高DEL，起动率",
  SURIN: "苏林",
  Surrey: "萨里",
  Sussex: "苏塞克斯",
  Sutherland: "萨瑟兰",
  Suwalki: "苏瓦乌基",
  SVERDLOV: "斯维尔德洛夫",
  SWIETOKRZYSKIE: "圣十字",
  Switzerland: "瑞士",
  "Szabolcs-Szat.-Bereg": "的索博尔奇-Szat.-Bereg",
  Szczecin: "什切青",
  Szeged: "塞格德",
  Szekesfehervar: "塞克希费黑瓦尔",
  Szolnok: "索尔诺克",
  Szombathely: "松博特海伊",
  Tabasco: "塔巴斯科",
  Tachira: "塔奇拉",
  Tacna: "塔克纳",
  "Taichung City": "台中市",
  "Tainan City": "台南市",
  "Taipei City": "台北市",
  "Taitung County": "台东县",
  TAK: "德",
  Tamaulipas: "塔毛利帕斯",
  TAMBOV: "坦波夫",
  "Taoyuan City": "桃园市",
  Taranaki: "塔拉纳基",
  Taranto: "塔兰托",
  Tarapaca: "塔拉帕卡",
  TARLAC: "塔拉克",
  Tarn: "塔恩",
  "Tarn-et-Garonne": "塔恩-等加龙省",
  Tarnow: "塔尔努夫",
  Tarragona: "塔拉戈纳",
  TAS: "塔斯马尼亚",
  Tatabanya: "陶陶巴尼奥",
  TATARSTAN: "鞑靼斯坦",
  "TAWI-TAWI": "塔威 - 塔威",
  Tayside: "泰赛德",
  Tekirdag: "泰基尔达",
  "Tel Aviv": "特拉维夫",
  "Telemark Fylke": "泰勒马克郡",
  Teramo: "泰拉莫",
  Terengganu: "丁加奴",
  Terni: "特尔尼",
  "Territ.-de-Belfort": "territ.-DE-贝尔福",
  Teruel: "特鲁埃尔",
  TG: "特伦甘纳邦",
  THA: "临屋区",
  "The Jewish Auton.are": "犹太Auton.are",
  "The Nizhniy Novgorod": "下诺夫哥罗德",
  "The Taymir Auton.dis": "Taymir Auton.dis",
  Thurgau: "高州",
  Thüringen: "图林根",
  Thurrock: "瑟罗克",
  Tianjin: "天津",
  Ticino: "提契诺州",
  "Tierra Del Fuego": "火地岛",
  Timis: "蒂米什",
  "Timor Timur East Tim": "东帝汶帖木儿东添",
  Tipperary: "蒂珀雷",
  Tiraspol: "蒂拉斯波尔",
  TN: "泰米尔纳德邦",
  TN: "田纳西州",
  Tocantins: "托坎廷斯",
  Tokat: "托卡特",
  Toledo: "托莱多",
  TOLIMA: "托利马",
  Tolna: "托尔瑙",
  TOMSK: "托木斯克",
  Torbay: "托贝",
  Tortola: "托尔托拉",
  Torun: "托伦",
  TR: "特里普拉邦",
  Trabzon: "特拉布宗",
  Transvaal: "德兰士瓦",
  Trapani: "特拉帕尼",
  TRAT: "达勒",
  Trbovlje: "的Trbovlje",
  Trento: "特伦托",
  Treviso: "特雷维索",
  Trieste: "的里雅斯特",
  "Troms Fylke": "特罗姆斯郡",
  Trujillo: "特鲁希略",
  Tucuman: "图库曼",
  TULA: "图拉",
  Tulcea: "图尔恰",
  Tumbes: "通贝斯",
  Tunceli: "通杰利",
  Turin: "都灵",
  "Tuva Republic": "图瓦共和国",
  TVER: "特维尔",
  TX: "得克萨斯州",
  "Tyne and Wear": "泰恩河和磨损",
  Tyrol: "蒂罗尔",
  Tyrone: "泰隆",
  TYUMEN: "秋明",
  TYVA: "图瓦",
  "UBON RATCHATHANI": "乌汶",
  Ucayali: "乌卡亚利",
  Udine: "乌迪内",
  "UDON THANI": "乌隆",
  ULYANOVSK: "乌里扬诺夫斯克州",
  "Umm al Qaywayn": "乌姆盖万",
  UP: "北方邦",
  "Upper Austria": "上奥地利",
  "Uppsala Län": "乌普萨拉",
  Uri: "乌里",
  USAK: "乌沙克",
  "Ust-Ordinsky Buryat": "乌斯Ordinsky布里亚特",
  UT: "北阿坎德邦",
  UT: "犹他州",
  "UTHAI THANI": "乌泰他尼",
  Utrecht: "乌得勒支",
  UTTARADIT: "程逸",
  VA: "弗吉尼亚州",
  "Val-d Oise": "VAL-ð瓦兹",
  "Val-de-Marne": "瓦尔 - 德 - 马恩省",
  Valais: "瓦莱州",
  Valencia: "瓦伦西亚",
  Valladolid: "巴利亚多利德",
  "Valle del Cuaca": "巴耶德尔Cuaca",
  Valparaiso: "瓦尔帕莱索",
  Van: "货车",
  Var: "瓦尔",
  Varese: "瓦雷泽",
  Vargas: "巴尔加斯",
  "Värmlands Län": "värmlands兰",
  Varna: "瓦尔纳",
  Vas: "输精管",
  Vaslui: "瓦斯卢伊",
  "Västerbottens Län": "västerbottens兰",
  "Västernorrlands Län": "西诺尔兰",
  "Västmanlands Län": "västmanlands兰",
  "Västra Götalands Län": "西哥Götalands局域网",
  Vaucluse: "沃克吕兹",
  Vaud: "沃",
  Vaupes: "沃佩斯",
  "Vejle amt": "瓦埃勒AMT",
  Vendee: "买受人",
  Venice: "威尼斯",
  Veracruz: "韦拉克鲁斯",
  Verbania: "韦尔巴尼亚",
  Vercelli: "韦尔切利",
  Verona: "维罗纳",
  "Vest-Agder Fylke": "背心阿格德郡",
  "Vestfold Fylke": "西福尔郡",
  "Vestsjælland amt": "vestsjællandAMT",
  Veszprem: "维斯普雷姆",
  VI: "美国维尔京群岛，",
  "VIANA DO CASTELO": "维亚纳堡",
  "Vibo Valentia": "维博瓦伦蒂亚",
  "Viborg amt": "维堡AMT",
  VIC: "维多利亚",
  Vicenza: "维琴察",
  Vichada: "比查达",
  Vienna: "维也纳",
  Vienne: "维埃纳省",
  "Vienne (Haute)": "维埃纳省（高级）",
  "VILA REAL": "雷阿尔",
  "Virgin Gorda": "维尔京戈达",
  VISEU: "维塞乌",
  Viterbo: "维泰博",
  Vizcaya: "比斯开",
  VLADIMIR: "弗拉基米尔",
  Vladivostok: "符拉迪沃斯托克",
  VOLGOGRAD: "伏尔加格勒",
  Vorarlberg: "福拉尔贝格州",
  VORONEZH: "沃罗涅日",
  Vosges: "孚日",
  "Vostochno-Kazakhstan": "vostochno，哈",
  Vrancea: "弗朗恰",
  VT: "佛蒙特",
  "Vukovar-Srijem": "武科瓦尔，Srijem",
  WA: "华盛顿",
  WA: "西澳大利亚州",
  Waikato: "怀卡托",
  Walbrzych: "瓦乌布日赫",
  Warrington: "灵顿",
  Warszawa: "华沙",
  Warwickshire: "沃里克",
  Waterford: "沃特福德",
  WB: "西孟加拉邦",
  Wellington: "惠灵顿",
  "West Coast": "西海岸",
  "West Glamorgan": "西Glamorgan的",
  "West Lothian": "西洛锡安",
  "West Midlands": "西米德兰",
  "West Sussex": "西萨塞克斯",
  "West Visayas": "西维萨亚斯",
  "West Yorkshire": "西约克郡",
  "West-Vlaanderen": "西-Vlaanderen",
  "Western Cape": "西开普省",
  "Western Isles": "西部群岛",
  "Western Mindanao": "西棉兰老岛",
  "WESTERN SAMAR": "西部SAMAR",
  Westmeath: "西米斯",
  Wexford: "韦克斯福德",
  WI: "威斯康星州",
  Wicklow: "威克洛",
  Wiltshire: "威尔特",
  "Windsor & Maidenhead": "温莎和梅登黑德",
  Wloclawek: "弗沃茨瓦韦克",
  Wokingham: "沃金厄姆",
  Worcestershire: "伍斯特郡",
  Wroclaw: "弗罗茨瓦夫",
  WV: "西弗吉尼亚州",
  WY: "怀俄明州",
  Xinjiang: "新疆",
  Xizang: "西藏",
  "Yakutiya-Saha Rrepub": "yakutiya-萨哈Rrepub",
  Yakutsk: "雅库茨克",
  YALA: "亚拉",
  Yalova: "亚洛瓦",
  "YAMALO-NENETS": "亚马尔 - 涅涅茨",
  YAROSLAV: "雅罗斯拉夫",
  YASOTHON: "耶梭通",
  Yekaterinburg: "叶卡捷琳堡",
  "Yilan County": "宜兰县",
  Yonne: "约讷",
  York: "纽约",
  Yorkshire: "约克郡",
  Yozgat: "约兹加特",
  YT: "育空地区",
  Yucatan: "尤卡坦半岛",
  "Yunlin County": "云林县",
  Yunnan: "云南",
  Yvelines: "伊夫林",
  Zacatecas: "萨卡特卡斯",
  "Zadar-Knin": "扎达尔 - 克宁",
  "Zagorje Ob Savi": "zagorje OB萨维",
  Zagreb: "萨格勒布",
  Zala: "砸落",
  Zalaegerszeg: "佐洛埃格塞格",
  ZAMBALES: "三描礼士",
  "ZAMBOANGA DEL NORTE": "北三宝颜",
  "ZAMBOANGA DEL SUR": "三宝颜",
  Zamora: "萨莫拉",
  Zamosc: "扎莫希奇",
  Zaragoza: "萨拉戈萨",
  Zeeland: "泽兰",
  Zhejiang: "浙江",
  "Zielona Gora": "锡隆纳葛拉",
  Zonguldak: "宗古尔达克",
  Zug: "楚格",
  "Zuid-Holland": "南荷兰",
  Zulia: "苏利亚",
  Zurich: "苏黎世",
  佐賀県: "佐贺県",
  兵庫県: "兵库県",
  千葉県: "千叶県",
  岡山県: "冈山県",
  島根県: "岛根県",
  徳島県: "徳岛県",
  新潟県: "新泻県",
  東京都: "东京都",
  滋賀県: "滋贺県",
  福岡県: "福冈県",
  福島県: "福岛県",
  群馬県: "群马県",
  長崎県: "长崎県",
  長野県: "长野県",
  静岡県: "静冈県",
  鳥取県: "鸟取県",
  鹿児島県: "鹿児岛県",
};