/**
 * Two-language strings for the form engine demo.
 * Keys: form field labelKey/placeholderKey, configurator labels, debug labels, validation, buttons.
 */

export const STRINGS = {
  en: {
    appTitle: 'Form Engine Demo',
    configuratorTitle: 'Configurator',
    formPreviewTitle: 'Form preview',
    resetActionsTitle: 'Reset actions',
    debugTitle: 'Debug view',

    locale: 'Language',
    formLanguage: 'Form language',
    template: 'Template',
    templateFlexContact: 'Full',
    templateFlexEvent: 'Expanded',
    templateFlexContent: 'Essential',
    subtype: 'Subtype',
    subtypeRequestForInformation: 'Request for information',
    subtypeStrategyWebinar: 'Strategy Webinar',
    subtypeWhitepaperForm: 'Whitepaper Download',
    multiStep: 'Multi-step',
    progressiveProfiling: 'Progressive profiling',
    companyEnrichment: 'Company enrichment',
    privacyByCountry: 'Privacy by country',
    conditionalVisibility: 'Conditional visibility',
    successType: 'Success type',
    successTypeMessage: 'Message',
    successTypeRedirect: 'Redirect',
    successContent: 'Success content',
    artificialDelay: 'Artificial delay (s)',
    resetKnownUser: 'Reset known user',
    preset: 'Preset',
    presetShort: 'Short form',
    presetMultiStepPP: 'Multi-step with PP',
    presetMultiStep3: 'Multi-step (3 steps)',
    presetAllFeatures: 'All features',

    labelFirstName: 'First name',
    labelLastName: 'Last name',
    labelEmail: 'Email',
    labelBusinessEmail: 'Business email',
    labelBusinessPhone: 'Business phone',
    labelJobTitle: 'Job title or role',
    labelDepartment: 'Department',
    labelCompany: 'Company',
    labelCompanyName: 'Organization name',
    labelCountry: 'Country',
    labelState: 'State',
    labelPostCode: 'ZIP/postal code',
    labelPrimaryProductOfInterest: 'Primary product of interest',
    labelComments: 'Comments',
    placeholderFirstName: 'Enter first name',
    placeholderLastName: 'Enter last name',
    placeholderEmail: 'Enter email',
    placeholderBusinessEmail: 'Enter business email',
    placeholderBusinessPhone: 'Enter business phone',
    placeholderJobTitle: 'Enter job title or role',
    placeholderDepartment: 'Enter department',
    placeholderCompany: 'Enter company',
    placeholderCompanyName: 'Enter company name',
    placeholderCountry: 'Select country',
    placeholderState: 'Select state',
    placeholderPostCode: 'Enter post code',
    placeholderPrimaryProductOfInterest: 'Select primary product of interest',
    placeholderComments: 'Enter comments',
    optionUS: 'United States',
    optionDE: 'Germany',
    optionCA: 'Canada',
    optionCAState: 'California',
    optionNYState: 'New York',

    buttonNext: 'Next',
    buttonBack: 'Back',
    buttonSubmit: 'Submit',

    formHeadingStrategyWebinar: 'Please share your contact information to get the report.',
    formHeadingRequestForInformation: 'Please share your contact information to get the report.',
    formHeadingWhitepaperForm: 'Please share your contact information to get the report.',

    validationRequired: 'This field is required.',

    successThankYou: 'Thank you for submitting.',

    debugConfigState: 'Config & state',
    debugConfig: 'Render config',
    debugConfigMuted: 'Enable “Show full module code” above to display.',
    debugState: 'Form state',
    debugEventLog: 'Event log',
    debugCopySnapshot: 'Copy state snapshot',
    debugCopyLog: 'Copy event log',
    debugResetForm: 'Reset form',
    debugCollapse: 'Collapse',
    debugExpand: 'Expand',
    showFullModuleCode: 'Show full module code',
    runModuleMultiStep: 'Run multi-step module',
    runModuleProgressiveProfiling: 'Run progressive profiling module',
    runModuleCompanyEnrichment: 'Run company enrichment module',
    runModulePrivacyByCountry: 'Run privacy-by-country module',
    runModuleConditionalVisibility: 'Run conditional visibility module',
  },
  de: {
    appTitle: 'Formular-Engine-Demo',
    configuratorTitle: 'Konfigurator',
    formPreviewTitle: 'Formularvorschau',
    resetActionsTitle: 'Zurücksetzen',
    debugTitle: 'Debug-Ansicht',

    locale: 'Sprache',
    formLanguage: 'Formularsprache',
    template: 'Vorlage',
    templateFlexContact: 'Vollständig',
    templateFlexEvent: 'Erweitert',
    templateFlexContent: 'Essenziell',
    subtype: 'Untertyp',
    subtypeRequestForInformation: 'Informationsanfrage',
    subtypeStrategyWebinar: 'Strategie-Webinar',
    subtypeWhitepaperForm: 'Whitepaper-Download',
    multiStep: 'Mehrstufig',
    progressiveProfiling: 'Progressive Profilierung',
    companyEnrichment: 'Firmen-Anreicherung',
    privacyByCountry: 'Datenschutz nach Land',
    conditionalVisibility: 'Bedingte Sichtbarkeit',
    successType: 'Erfolgstyp',
    successTypeMessage: 'Nachricht',
    successTypeRedirect: 'Weiterleitung',
    successContent: 'Erfolgsinhalt',
    artificialDelay: 'Verzögerung (s)',
    resetKnownUser: 'Bekannten Benutzer zurücksetzen',
    preset: 'Voreinstellung',
    presetShort: 'Kurzes Formular',
    presetMultiStepPP: 'Mehrstufig mit PP',
    presetMultiStep3: 'Mehrstufig (3 Schritte)',
    presetAllFeatures: 'Alle Funktionen',

    labelFirstName: 'Vorname',
    labelLastName: 'Nachname',
    labelEmail: 'E-Mail',
    labelBusinessEmail: 'Geschäftliche E-Mail',
    labelBusinessPhone: 'Geschäftliche Telefonnummer',
    labelJobTitle: 'Berufsbezeichnung oder Rolle',
    labelDepartment: 'Abteilung',
    labelCompany: 'Unternehmen',
    labelCompanyName: 'Organisation',
    labelCountry: 'Land',
    labelState: 'Bundesland',
    labelPostCode: 'PLZ/Postleitzahl',
    labelPrimaryProductOfInterest: 'Hauptprodukt von Interesse',
    labelComments: 'Anmerkungen',
    placeholderFirstName: 'Vorname eingeben',
    placeholderLastName: 'Nachname eingeben',
    placeholderEmail: 'E-Mail eingeben',
    placeholderBusinessEmail: 'Geschäftliche E-Mail eingeben',
    placeholderBusinessPhone: 'Geschäftliche Telefonnummer eingeben',
    placeholderJobTitle: 'Berufsbezeichnung eingeben',
    placeholderDepartment: 'Abteilung eingeben',
    placeholderCompany: 'Unternehmen eingeben',
    placeholderCompanyName: 'Firmenname eingeben',
    placeholderCountry: 'Land auswählen',
    placeholderState: 'Bundesland auswählen',
    placeholderPostCode: 'Postleitzahl eingeben',
    placeholderPrimaryProductOfInterest: 'Hauptprodukt auswählen',
    placeholderComments: 'Anmerkungen eingeben',
    optionUS: 'Vereinigte Staaten',
    optionDE: 'Deutschland',
    optionCA: 'Kanada',
    optionCAState: 'Kalifornien',
    optionNYState: 'New York',

    buttonNext: 'Weiter',
    buttonBack: 'Zurück',
    buttonSubmit: 'Absenden',

    formHeadingStrategyWebinar: 'Bitte teilen Sie Ihre Kontaktdaten, um den Bericht zu erhalten.',
    formHeadingRequestForInformation: 'Bitte teilen Sie Ihre Kontaktdaten, um den Bericht zu erhalten.',
    formHeadingWhitepaperForm: 'Bitte teilen Sie Ihre Kontaktdaten, um den Bericht zu erhalten.',

    validationRequired: 'Dieses Feld ist erforderlich.',

    successThankYou: 'Vielen Dank für Ihre Angaben.',

    debugConfigState: 'Konfiguration & Zustand',
    debugConfig: 'Render-Konfiguration',
    debugConfigMuted: 'Aktivieren Sie oben „Vollständigen Modulcode anzeigen“, um die Konfiguration anzuzeigen.',
    debugState: 'Formularzustand',
    debugEventLog: 'Ereignisprotokoll',
    debugCopySnapshot: 'Zustand kopieren',
    debugCopyLog: 'Protokoll kopieren',
    debugResetForm: 'Formular zurücksetzen',
    debugCollapse: 'Einklappen',
    debugExpand: 'Aufklappen',
    showFullModuleCode: 'Vollständigen Modulcode anzeigen',
    runModuleMultiStep: 'Mehrstufen-Modul ausführen',
    runModuleProgressiveProfiling: 'Progressive-Profiling-Modul ausführen',
    runModuleCompanyEnrichment: 'Firmen-Anreicherungs-Modul ausführen',
    runModulePrivacyByCountry: 'Datenschutz-nach-Land-Modul ausführen',
    runModuleConditionalVisibility: 'Bedingte-Sichtbarkeits-Modul ausführen',
  },
};

/**
 * Resolve a label or placeholder key for a locale.
 * Falls back to key if missing, then to en.
 * @param {string} locale - e.g. 'en', 'de'
 * @param {string} key - e.g. 'labelFirstName', 'placeholderEmail'
 * @returns {string}
 */
export function getString(locale, key) {
  const loc = STRINGS[locale] || STRINGS.en;
  return loc[key] ?? STRINGS.en[key] ?? key;
}
