// ##
//lang code =nl, form locale = nl_NL, form language = Dutch (Netherlands)
var translateState = {
  AA: "Armed Forces-Amerika",
  ACT: "Aust Hoofdstad Terr",
  Alexandria: "Alexandrië",
  AN: "Andaman / Nicobar",
  Antwerp: "Antwerpen",
  Ardennes: "Ardennen",
  AS: "Amerikaans-Samoa",
  Asturias: "Asturië",
  ATHENS: "ATHENE",
  "Basel (city)": "Bazel (stad)",
  "Basel (regional)": "Basel (regionale)",
  "Bath&NthEstSomerset": "Bath & NthEstSomerset",
  BENGAL: "Bengalen",
  Berlin: "Berlijn",
  BINGOL: "Bingöl",
  "Borsod-Abauj-Zemplen": "Borsod-Abaúj-Zemplen",
  Budapest: "Boedapest",
  CA: "Californië",
  Capetown: "Kaapstad",
  Central: "Centraal",
  "Central Luzon": "Centraal Luzon",
  "Chakassky Republic": "Chakassky Republiek",
  "CHECHENO-INGUSHETIA": "CHECHENO-Ingoesjetië",
  CHECHNYA: "TSJETSJENIË",
  CHUVASHIA: "Tsjoevasjië",
  Ciechanow: "Ciechanów",
  Copenhagen: "Kopenhagen",
  Cork: "Kurk",
  Crnomelj: "Črnomelj",
  "DI Aceh Aceh": "DI Atjeh Atjeh",
  DN: "DADRA EN NAGAR HEBBEN",
  DOLNOSLASKIE: "Dolnośląskie",
  Down: "Beneden",
  Dubasari: "Dubassari",
  Dubayy: "Dubai",
  "Dumfries a. Galloway": "Dumfries een. Galloway",
  Falcon: "Valk",
  Fife: "Fluit",
  GA: "Georgië",
  Gauteng: "Noord-Holland",
  Geneva: "Genève",
  "Greater London": "Groot-Londen",
  GUMUSHANE: "Gümüşhane",
  "Hallands Län": "Halland",
  "Hawke´s Bay": "Hawke's Bay",
  "Hereford and Worcs.": "Hereford en Worcs.",
  Highland: "Hoogland",
  "Highlands-Altay Rep.": "Highlands-Altay Rep",
  "Hors-France": "Hors-Frankrijk",
  HUANUCO: "Huánuco",
  "ILHA DE SAO JORGE": "ILHA DE SÃO JORGE",
  "ILHA DE SAO MIGUEL": "ILHA DE SÃO MIGUEL",
  "Ingushetija Republic": "Ingushetija Republiek",
  "Isles Of Scilly": "Scilly-eilanden",
  "Jawa Barat West Java": "Jawa Barat West-Java",
  "Jawa Timur East Java": "Jawa Timur Oost-Java",
  Jerusalem: "Jeruzalem",
  "KABARDINO-BALKARIA": "Kabardino-Balkarië",
  "KARACHAY-CHERKESSIA": "Karatsjaj-Tsjerkessië",
  Kashmir: "Kasjmier",
  KAVALAS: "Kavala",
  KIRSEHIR: "Kırşehir",
  KURSK: "KOERSK",
  "Kwazulu/Natal": "Kwazulu / Natal",
  Liege: "Leenheer",
  LODZKIE: "Łódzkie",
  London: "Londen",
  "Lower Austria": "Neder-Oostenrijk",
  Lucerne: "Luzern",
  Luxembourg: "Luxemburg",
  MANILA: "MANILLA",
  "Marijskaya Republic": "Marijskaya Republiek",
  "Médio Tejo": "Medio Tejo",
  "Milton Keynes": "Leeds",
  Moscow: "Moskou",
  Moselle: "Moezel",
  Murmansk: "Moermansk",
  Namur: "Namen",
  Naples: "Napels",
  "NATIONAL CAPITAL REG": "NATIONALE CAPITAL REG",
  NEVSEHIR: "Nevşehir",
  "Newry and Mourne": "Newry en Mourne",
  "Nordjylland amt": "Noord-Jutland amt",
  "North Yorkshire": "Noord-Yorkshire",
  "North-Osetiya Republ": "Noord-Osetiya Republ",
  "North-West": "Noord-West",
  Northern: "Noordelijk",
  "Northern Cape": "Noord-Kaap",
  "Northern Mindanao": "Noord-Mindanao",
  "NORTHERN SAMAR": "NOORD-SAMAR",
  Northland: "Noordelijke gebieden",
  Paris: "Parijs",
  Pest: "Plaag",
  Piotrkow: "Piotrków",
  "Pozega-Slavonija": "Pozega-Slavonië",
  "Pyrenees (Hautes)": "Pyreneeën (Hautes)",
  Reading: "Lezing",
  "Region Metropolitana": "Regio Metropolitana",
  Réunion: "Reunion",
  Ruse: "List",
  SA: "Zuid-Australië",
  "Schleswig-Holstein": "Sleeswijk-Holstein",
  Scotland: "Schotland",
  Select: "Selecteren",
  Shanghai: "Sjanghai",
  Slough: "Moeras",
  "Smarje Pri Jelsah": "Šmarje Pri Jelsah",
  "Södermanlands Län": "Södermanland",
  "Sønderjylland amt": "Zuid-Jutland amt",
  "SOUTH COTABATO": "ZUID-COTABATO",
  "South Humberside": "Zuid-Humberside",
  "South Luzon": "Zuid-Luzon",
  "South Mindanao": "Zuid-Mindanao",
  "South Yorkshire": "Zuid-Yorkshire",
  Southern: "Zuidelijk",
  "Split-Dalmatia": "Split-Dalmatië",
  "St. Petersburg": "Sint-Petersburg",
  Styria: "Stiermarken",
  "Sulawesi Tenggara So": "Sulawesi Tenggara dus",
  "Sulawesi Utara North": "Sulawesi Utara Noord",
  "Sumatera Utara North": "Sumatera Utara Noord",
  SWIETOKRZYSKIE: "Świętokrzyskie",
  Switzerland: "Zwitserland",
  Tarn: "Bergmeertje",
  TAS: "Tasmanië",
  "The Jewish Auton.are": "De Joodse Auton.are",
  "The Nizhniy Novgorod": "De Nizhniy Novgorod",
  "The Taymir Auton.dis": "De Taymir Auton.dis",
  "Timor Timur East Tim": "Timor Timur Oost Tim",
  Turin: "Turijn",
  Tyrol: "Tirol",
  UDMURTIA: "Oedmoertië",
  ULYANOVSK: "Oeljanovsk",
  "Upper Austria": "Opper-Oostenrijk",
  Valais: "Wallis",
  "Västmanlands Län": "Västmanland",
  "Västra Götalands Län": "Västra Götaland",
  Venice: "Venetië",
  VI: "Amerikaanse Maagdeneilanden",
  Vienna: "Wenen",
  Vosges: "Vogezen",
  "Vostochno-Kazakhstan": "Vostochno-Kazachstan",
  WA: "West-Australië",
  WB: "West-Bengalen",
  "Western Cape": "West-Kaap",
  "Western Mindanao": "West-Mindanao",
  Zurich: "Zürich",
  三重県: "三重 県",
  京都府: "京都 府",
  佐賀県: "佐贺 県",
  兵庫県: "兵 库 県",
  千葉県: "千叶 県",
  和歌山県: "和 歌 山 県",
  埼玉県: "埼 玉 県",
  大分県: "大分 県",
  大阪府: "大阪 府",
  奈良県: "奈良 県",
  富山県: "富山 県",
  山口県: "山口 県",
  山形県: "山形 県",
  山梨県: "山 梨 県",
  岐阜県: "岐阜 県",
  岡山県: "冈山 県",
  岩手県: "岩手 県",
  島根県: "岛 根 県",
  広島県: "広 島 県",
  徳島県: "徳 岛 県",
  新潟県: "新泻 県",
  東京都: "东京 都",
  栃木県: "栃 木 県",
};