// ##
//lang code =no, form locale = no_NO, form language = Norwegian (Norway)
var translateState = {
  ADYGEA: "Adygia",
  AN: "Andamans / Nicobar",
  Antwerp: "Antwerpen",
  AS: "Amerikansk Samoa",
  "Bali Bali": "Bali",
  "Basel (city)": "Basel (by)",
  "Basel (regional)": "Basel (regionalt)",
  BASHKORTOSTAN: "Basjkortostan",
  "Bath&NthEstSomerset": "Bath &amp; NthEstSomerset",
  BINGOL: "Bingöl",
  Borders: "Grenser",
  "BRAGAN¦A": "Bragança",
  "Brighton & Hove": "Brighton &amp; Hove",
  BURYATIYA: "Burjatia",
  Cairo: "Kairo",
  "Changhua County": "Changhua",
  "CHECHENO-INGUSHETIA": "CHECHENO-Ingusjetia",
  CHECHNYA: "Tsjetsjenia",
  "Chiayi City": "Chiayi",
  "Chiayi County": "Chiayi fylke",
  "Chukotka Auton. dist": "Tsjukotka Auton. dist",
  CHUVASHIA: "Tsjuvasjia",
  Copenhagen: "København",
  Cork: "Kork",
  "D.O.M.T.O.M": "DOMTOM",
  DD: "Diu",
  "DKI Jakarta Jakarta": "DKI Jakarta",
  DN: "Dadra og Nagar HAR",
  Down: "Ned",
  DRAMAS: "Dramaer",
  "Dumfries a. Galloway": "Dumfries en. Galloway",
  Falcon: "Falk",
  Gyor: "Györ",
  "Hawke´s Bay": "Hawkes Bay",
  "Hereford and Worcs.": "Hereford og Worcs.",
  "Highlands-Altay Rep.": "Highlands-Altay Rep",
  "Hors-France": "Hors-Frankrike",
  "Hsinchu City": "Hsinchu",
  "Hsinchu County": "Hsinchu fylke",
  "Hualien County": "Hualien",
  JK: "Jammu og Kashmir",
  KALUZHSKAYA: "Kaluga",
  "Kaohsiung City": "Kaohsiung",
  "Keelung City": "Chilung",
  "Kinmen County": "Kinmen",
  KUTAHYA: "Kütahya",
  "Kwazulu/Natal": "Kwazulu / Natal",
  "Lianjiang County": "Lianjiang",
  "Lower Austria": "Niederösterreich",
  "Malvinas/Falkland Is": "Malvinas / Falkland Er",
  "Miaoli County": "Miaoli",
  Moscow: "Moskva",
  "Nantou County": "Nantou",
  Naples: "Napoli",
  "New TaipeiCity": "Ny-Taipei",
  "Newry and Mourne": "Newry og Mourne",
  "NORTH COTABATO": "Nord-Cotabato",
  "North-Osetiya Republ": "Nord-Osetija Republ",
  "North-West": "Nord-Vest",
  Northern: "Nordlige",
  "Northern Mindanao": "Nord-Mindanao",
  Ormoz: "Ormož",
  "Penghu County": "Penghu",
  "Pingtung County": "Pingtung",
  "Pinhal Interior N.": "Pinhal Interiør N.",
  "Pinhal Interior Sul": "Pinhal Interiør Sul",
  PRIMORSKIY: "Primorskij",
  "Pyrenees-Orientales": "Pyrénées-Orientales",
  "Ra's al Khaymah": "Ras al Khaymah",
  "Ravne Na Koroskem": "Ravne na Koroškem",
  "Redcar and Cleveland": "Redcar og Cleveland",
  "Riau Riau": "Riau",
  Rome: "Roma",
  SANLIURFA: "Şanlıurfa",
  SANTAREM: "Santarém",
  Scotland: "Skottland",
  Select: "Velg",
  SIRNAK: "Şırnak",
  SLASKIE: "Śląskie",
  "South Humberside": "Sør Humberside",
  "South Luzon": "Sør Luzon",
  "South Mindanao": "Sør Mindanao",
  "Sulawesi Tenggara So": "Sulawesi Tenggara Så",
  SWIETOKRZYSKIE: "Świętokrzyskie",
  Switzerland: "Sveits",
  "Taichung City": "Taichung",
  "Tainan City": "Tainan",
  "Taipei City": "Taipei",
  "Taitung County": "Taitung",
  "Taoyuan City": "Taoyuan",
  "The Jewish Auton.are": "Den jødiske Auton.are",
  "The Nizhniy Novgorod": "Den Nizhniy Novgorod",
  "The Taymir Auton.dis": "Den Taymir Auton.dis",
  "Tuva Republic": "Tuva republikk",
  TYVA: "Tuva",
  "Upper Austria": "Øvre Østerrike",
  Venice: "Venezia",
  Vienna: "Wien",
  Vilcea: "Valcea",
  "Vostochno-Kazakhstan": "Vostochno-Kasakhstan",
  WB: "Vest-Bengal",
  "Windsor & Maidenhead": "Windsor &amp; Maidenhead",
  "YAMALO-NENETS": "Jamalo-Nenets",
  Yekaterinburg: "Jekaterinburg",
  "Yilan County": "Yilan",
  "Yunlin County": "Yunlin",
  Zurich: "Zürich",
  三重県: "三重 県",
  京都府: "京都 府",
  佐賀県: "佐贺 県",
  兵庫県: "兵 库 県",
  千葉県: "千叶 県",
  和歌山県: "和 歌 山 県",
  埼玉県: "埼 玉 県",
  大分県: "大分 県",
  大阪府: "大阪 府",
  奈良県: "奈良 県",
  富山県: "富山 県",
  山口県: "山口 県",
  山形県: "山形 県",
  山梨県: "山 梨 県",
  岐阜県: "岐阜 県",
  岡山県: "冈山 県",
  岩手県: "岩手 県",
  島根県: "岛 根 県",
  広島県: "広 島 県",
  徳島県: "徳 岛 県",
  新潟県: "新泻 県",
  東京都: "东京 都",
  栃木県: "栃 木 県",
  滋賀県: "滋 贺 県",
  熊本県: "熊 本 県",
  石川県: "石川 県",
  神奈川県: "神奈川 県",
  福井県: "福井 県",
  福岡県: "福冈 県",
  福島県: "福岛 県",
  秋田県: "秋田 県",
  群馬県: "群 马 県",
  茨城県: "茨城 県",
  長崎県: "长崎 県",
  長野県: "长野 県",
  青森県: "青森 県",
  静岡県: "静冈 県",
  香川県: "香 川 県",
  高知県: "高 知 県",
  鳥取県: "鸟取 県",
  鹿児島県: "鹿 児 岛 県",
};