// ##
//lang code = da, form locale = da-DK,  form language = Dansk, form country = Danmark
var translateState = {
  AA: "Armed Forces USA",
  "Alpes (Hte-Provence)": "Alpes (adlrig-Provence)",
  AN: "Andamans / Nicobar",
  Antwerp: "Antwerpen",
  Ardennes: "Ardennerne",
  AS: "Amerikansk Samoa",
  ATHENS: "ATHEN",
  "Bali Bali": "Bali",
  "Basel (city)": "Basel (by)",
  "Bath&NthEstSomerset": "Bad & NthEstSomerset",
  Borders: "Grænser",
  "BRAGAN¦A": "Bragança",
  BURYATIYA: "Buryatia",
  CA: "Californien",
  Cankiri: "Çankırı",
  "Chakassky Republic": "Chakassky Republik",
  "Changhua County": "Changhua amt",
  "CHECHENO-INGUSHETIA": "CHECHENO-Ingusjetien",
  CHECHNYA: "TJETJENIEN",
  "Chiayi City": "Chiayi by",
  "Chiayi County": "Chiayi amt",
  "Chukotka Auton. dist": "Tjukotka Auton. dist",
  CHUVASHIA: "Tjuvasien",
  Copenhagen: "København",
  Correze: "Corrèze",
  DD: "Daman og Diu",
  DN: "Dadra og Nagar HAVE",
  "Dumfries a. Galloway": "Dumfries en. Galloway",
  Dunaujvaros: "Dunaújváros",
  "EASTERN SAMAR": "ØSTLIGE SAMAR",
  GA: "Georgien",
  Gauteng: "Midtjylland",
  Geneva: "Geneve",
  GUMUSHANE: "Gümüşhane",
  "Hawke´s Bay": "Hawke 's Bay",
  Herault: "Hérault",
  "Hereford and Worcs.": "Hereford og Worcs.",
  "Highlands-Altay Rep.": "Highlands-Altay Rep",
  "Hsinchu City": "Hsinchu by",
  "Hsinchu County": "Hsinchu amt",
  "Hualien County": "Hualien amt",
  Igdir: "Iğdır",
  "Ingushetija Republic": "Ingushetija Republik",
  "Isle Of Eigg": "Isle af EIgG",
  Jihomoravsky: "Jihomoracsky",
  JK: "Jammu og Kashmir",
  KALMYKIYA: "Kalmykia",
  "Kaohsiung City": "Kaohsiung by",
  "Keelung City": "Keelung by",
  "Kinmen County": "Kinmen amt",
  KIRSEHIR: "Kırşehir",
  "Kwazulu/Natal": "Kwazulu / Natal",
  "Länsi-Suomi": "Lansi-Suomi",
  "Lianjiang County": "Lianjiang amt",
  "Lower Austria": "Nedre Østrig",
  "Malvinas/Falkland Is": "Malvinas / Falkland Er",
  "Marijskaya Republic": "Marijskaya Republik",
  "Médio Tejo": "Medio Tejo",
  "Miaoli County": "Miaoli amt",
  MORDOVIYA: "Mordovia",
  Moscow: "Moskva",
  "Nantou County": "Nantou amt",
  Naples: "Napoli",
  "New TaipeiCity": "New Taipei by",
  "Newry and Mourne": "Newry og Mourne",
  "North-Osetiya Republ": "Nord-Osetiyaniya Republ",
  "North-West": "Nord-Vest",
  "Nottingham City": "Nottingham By",
  "Penghu County": "Penghu amt",
  "Pingtung County": "Pingtung amt",
  "Pyrenees (Hautes)": "Pyrenæerne (Hautes)",
  "Ra's al Khaymah": "Ra 's al Khaymah",
  Reading: "Læsning",
  "Redcar and Cleveland": "Redcar og Cleveland",
  Rome: "Rom",
  "San Anders de Provi:": "San Anders de bestem:",
  Scotland: "Skotland",
  Select: "Vælg",
  "Sønderjylland amt": "Sønderjyllands amt",
  "SOUTH COTABATO": "Syd Cotabato",
  "South Glamorgan": "Syd Glamorgan",
  "South Luzon": "Syd Luzon",
  "South Mindanao": "Syd Mindanao",
  "St. Petersburg": "St. Petersborg",
  "Storstrøm amt": "Storstrøms amt",
  Styria: "Steiermark",
  "Sulawesi Tenggara So": "Sulawesi Tenggara Så",
  Switzerland: "Schweiz",
  "Taichung City": "Taichung by",
  "Tainan City": "Tainan by",
  "Taipei City": "Taipei by",
  "Taitung County": "Taitung amt",
  "Taoyuan City": "Taoyuan by",
  TAS: "Tasmanien",
  "The Jewish Auton.are": "Den jødiske Auton.are",
  "The Nizhniy Novgorod": "Den Nizhniy Novgorod",
  "The Taymir Auton.dis": "Den Taymir Auton.dis",
  Turin: "Torino",
  "Tuva Republic": "Tuva Republik",
  UDMURTIA: "UDMURTIEN",
  "Upper Austria": "Øvre Østrig",
  Venice: "Venedig",
  VI: "Virgin Islands, USA",
  Vienna: "Wien",
  VISEU: "I Viseu",
  "Vostochno-Kazakhstan": "Vostochno-Kasakhstan",
  "Western Mindanao": "Vestlige Mindanao",
  Yekaterinburg: "Jekaterinburg",
  "Yilan County": "Yilan amt",
  "Yunlin County": "Yunlin amt",
  Zurich: "Zürich",
  三重県: "三重 県",
  京都府: "京都 府",
  佐賀県: "佐贺 県",
  兵庫県: "兵 库 県",
  千葉県: "千叶 県",
  和歌山県: "和 歌 山 県",
  埼玉県: "埼 玉 県",
  大分県: "大分 県",
  大阪府: "大阪 府",
  奈良県: "奈良 県",
  富山県: "富山 県",
  山口県: "山口 県",
  山形県: "山形 県",
  山梨県: "山 梨 県",
  岐阜県: "岐阜 県",
  岡山県: "冈山 県",
  岩手県: "岩手 県",
  島根県: "岛 根 県",
  広島県: "広 島 県",
  徳島県: "徳 岛 県",
  新潟県: "新泻 県",
  東京都: "东京 都",
  栃木県: "栃 木 県",
  滋賀県: "滋 贺 県",
  熊本県: "熊 本 県",
  石川県: "石川 県",
  神奈川県: "神奈川 県",
  福井県: "福井 県",
  福岡県: "福冈 県",
  福島県: "福岛 県",
  秋田県: "秋田 県",
  群馬県: "群 马 県",
  茨城県: "茨城 県",
  長崎県: "长崎 県",
  長野県: "长野 県",
  青森県: "青森 県",
  静岡県: "静冈 県",
  香川県: "香 川 県",
  高知県: "高 知 県",
  鳥取県: "鸟取 県",
  鹿児島県: "鹿 児 岛 県",
};