// ##
//lang code =ja_jp, form locale = ja_JP, territory = JP
var translateState = {
  AA: "アメリカ軍隊",
  Aargau: "アールガウ州",
  AB: "アルバータ州",
  Aberdeenshire: "アバディーンシャー",
  ABRA: "アブラ",
  "Abu Dhabi": "アブダビ",
  Acre: "エーカー",
  ACT: "アウスト·キャピタルTERR",
  Adana: "アダナ",
  "ADGCID Campo": "ADGCIDカンポ",
  AE: "国軍ヨーロッパ",
  Afyon: "アフヨン",
  "AGIN-BURYAT": "AGIN-ブリヤート",
  Agri: "アグリ",
  Aguascalientes: "アグアスカリエンテス",
  "AGUSAN DEL NORTE": "アグサン川DEL NORTE",
  "AGUSAN DEL SUR": "アグサン川DEL SUR",
  Ain: "アン",
  Aisne: "エーヌ",
  Ajman: "アジマン",
  AK: "アラスカ州",
  "Akershus Fylke": "アーケシュフースFylke",
  AKLAN: "アクラン州",
  Aksaray: "アクサライ",
  AL: "アラバマ州",
  "Al Fujayrah": "アルフジャイラ",
  Alagoas: "アラゴアス州",
  Alava: "アラバ",
  Alba: "アルバ",
  Albacete: "アルバセテ",
  ALBAY: "アルバイ州",
  "Alentejo Litoral": "Litoralのアレンテージョ",
  Alessandra: "アレッサンドラ",
  Alexandria: "アレクサンドリア",
  Alicante: "アリカンテ",
  Allier: "アリエ",
  Almeria: "アルメリア",
  "Alpes (Hautes)": "アルプ（リズール）",
  "Alpes (Hte-Provence)": "アルプ（HTE-プロヴァンス）",
  "Alpes-Maritimes": "アルプ=マリティーム県",
  ALTAY: "アルタイ",
  Amapa: "アマパ",
  Amasya: "アマスヤ",
  AMAZONAS: "アマゾナス",
  AMAZONAS: "アマゾナス",
  "Amnat Charoen": "Amnatチャルン",
  AMUR: "アムール",
  AN: "アンダマン/ニコバル諸島",
  Ancash: "アンカシュ",
  Ancona: "アンコーナ",
  Anegada: "アネガダ",
  "Anenii Noi": "Aneniiノイ",
  "Ang Thong": "アントン",
  Angus: "アンガス",
  Anhui: "安徽省",
  Ankara: "アンカラ",
  Antalya: "アンタルヤ",
  ANTIQUE: "アンティーク",
  Antofagasta: "アントファガスタ",
  Antrim: "アントリム州",
  Antwerp: "アントワープ",
  Aosta: "アオスタ",
  AP: "アンドラプラデシ",
  AP: "国軍太平洋",
  "Appenzell Ausserrh.": "アッペンツェルAusserrh。",
  "Appenzell Innerrh": "アッペンツェルInnerrh",
  Apure: "アプレ州",
  Apurimac: "アプリマック",
  AR: "アーカンソー州",
  AR: "アルナチャルプラデシュ州",
  Arad: "アラド",
  Aragua: "アラグア州",
  Arauca: "アラウカ",
  Araucania: "アラウカニア",
  Ardahan: "アルダハン",
  Ardeche: "アルデーシュ",
  Ardennes: "アルデンヌ",
  Arequipa: "アレキパ",
  Arezzo: "アレッツォ",
  Arges: "アルジェス",
  Argyll: "アーガイル",
  "Århus amt": "オーフスAMT",
  ARKHANGELSK: "アルハンゲリスク",
  Armagh: "アーマー州",
  AS: "アッサム",
  AS: "米サモア",
  "Ascoli Piceno": "アスコリピチェノ",
  Asti: "アスティ",
  ASTRAKHAN: "アストラハン",
  Asturias: "アストゥリアス",
  Aswan: "アスワン",
  Atacama: "アタカマ",
  Atlantico: "アトランティコ",
  Aube: "オーブ",
  Auckland: "オークランド",
  Aude: "オード",
  "Aust-Agder Fylke": "アウストアグデルFylke",
  Ave: "アベニュー",
  AVEIRO: "アベイロ",
  Avellino: "アベリノ",
  Aveyron: "アベロン",
  Avila: "アビラ",
  Avon: "エイボン",
  Ayacucho: "アヤクチョ",
  Aydin: "アイドゥン",
  Ayrshire: "エアーシア",
  AZ: "アリゾナ州",
  Bacau: "バカウ",
  Badajoz: "バダホス",
  "Baden-Württemberg": "バーデン·ヴュルテンベルク州",
  Bahia: "バイア",
  "Baja California Nort": "バハ·カリフォルニアNort",
  "Baja California Sur": "バハ·カリフォルニア·スル州",
  Baleares: "バレアレス",
  "Bali Bali": "バリ島",
  Balikesir: "バルケシル",
  Ballymena: "Ballymenaの",
  Ballymoney: "バリマネー",
  Balti: "バルティ",
  Baluchistan: "バルチスタン",
  Bangkok: "バンコク",
  Baranya: "バラニャ",
  Barcelona: "バルセロナ",
  Bari: "バリ",
  Barinas: "バリナス",
  "Bas-Rhin": "バラン",
  "Basel (city)": "バーゼル（市）",
  "Basel (regional)": "バーゼル（地域）",
  BASHKORTOSTAN: "バシコルトスタン",
  BASILAN: "バシラン島",
  BATAAN: "バターン",
  BATANES: "バタネス州",
  BATANGAS: "バタンガス州",
  "Bath&NthEstSomerset": "バス＆NthEstSomerset",
  Batman: "バットマン",
  "Bay of Plenty": "プレンティー湾",
  Bayburt: "バイブルト",
  Bayern: "バイエルン州",
  BC: "ブリティッシュコロンビア州",
  Bedfordshire: "ベッドフォードシャー州",
  Beijing: "北京",
  "Beira Interior Norte": "ベイラインテリアノルテ",
  BEJA: "ベジャ",
  Belfast: "ベルファスト",
  BELGOROD: "ベルゴロド",
  Belluno: "ベルーノ",
  Bender: "ベンダー",
  Benevento: "ベネベント",
  BENGAL: "ベンガル",
  "Bengkulu Bengkulu": "ベンクルー州ベンクルー州",
  BENGUET: "ベンゲット州",
  Bergamo: "ベルガモ",
  Bergen: "ベルゲン",
  Berkshire: "バークシャー",
  Berlin: "ベルリン",
  Bern: "ベルン州",
  Bialystok: "ビアウィストク",
  Bicol: "ビコール",
  Biella: "ビエラ",
  Bihor: "ビホル",
  Bilecik: "ビレジク",
  BILIRAN: "ビリラン",
  BINGOL: "ビンギョル",
  "Bio-Bio": "バイオバイオ",
  "Bistrita-Nasaud": "ビストリツァ-Nasaud",
  Bitlis: "ビトリス",
  "Bjelovar-Bilogora": "ビェロバル-Bilogora",
  Blackburn: "ブラックバーン",
  Blackpool: "ブラックプール",
  "Blekinge Län": "ブレーキンゲ蘭",
  Bogota: "ボゴタ",
  BOHOL: "ボホール",
  Bolivar: "ボリバル",
  Bologna: "ボローニャ",
  Bolu: "ボル",
  Bolzano: "ボルツァーノ",
  Borders: "国境",
  "Bornholm amt": "ボーンホルム島AMT",
  Botosani: "ボトシャニ",
  "Bouches-du-Rhone": "ブーシュデュローヌ",
  Bournemouth: "ボーンマス",
  Boyaca: "ボヤカ",
  BR: "ビハール州",
  Brabant: "ブラバント州",
  "Bracknell Forest": "ブラックネルフォレスト",
  BRAGA: "ブラガ",
  "BRAGAN¦A": "ブラガンサ",
  Braila: "Brailaの",
  Brandenburg: "ブランデンブルク",
  Brasov: "ブラショブ",
  Bratislava: "ブラチスラバ",
  Bremen: "ブレーメン",
  Brescia: "ブレシア",
  "Brighton & Hove": "ブライトン＆ホーブ",
  Brindisi: "ブリンディジ",
  Bristol: "ブリストル",
  "Brod-Posavina": "ブロート·Posavina",
  BRYANSK: "ブリャンスク",
  Buckinghamshire: "バッキンガムシャー州",
  Bucuresti: "ブカレスト",
  Budapest: "ブダペスト",
  "Buenos Aires": "ブエノスアイレス",
  BUKIDNON: "ブキドノン州",
  BULACAN: "ブラカン州",
  Burgas: "ブルガス",
  Burgenland: "ブルゲンラント州",
  Burgos: "ブルゴス",
  Buriram: "ブリーラム",
  Bursa: "ブルサ",
  BURYATIYA: "ブリヤーチア",
  "Buskerud Fylke": "ブスケルーFylke",
  Buzau: "ブザウ",
  Bydgoszcz: "ビドゴシュチ",
  CA: "カリフォルニア州",
  Caceres: "カセレス",
  Cadiz: "カディス",
  CAGAYAN: "カガヤン",
  "Cagayan Valley": "カガヤン·バレー",
  Cagliari: "カリアリ",
  Cairo: "カイロ",
  Caithness: "ケイスネス",
  Cajamarca: "カハマルカ",
  Caldas: "カルダス",
  Calvados: "カルバドス",
  "CAMARINES NORTE": "カマリネスノルテ",
  "CAMARINES SUR": "カマリネスSUR",
  Cambridgeshire: "ケンブリッジシャー州",
  CAMIGUIN: "カミギン州",
  Campeche: "カンペチェ",
  Campobasso: "カンポバッソ",
  Canakkale: "チャナッカレ",
  Cankiri: "チャンクル",
  Cantabria: "カンタブリア",
  Cantal: "カンタル",
  Canterbury: "カンタベリー",
  Capetown: "ケープタウン",
  CAPIZ: "マドガイ",
  Caqueta: "カケタ",
  Carabobo: "カラボボ州",
  Caracas: "カラカス",
  "Caras-Severin": "カラス - セヴェリン",
  Carlow: "カーロー",
  Carrickfergus: "キャリクファーガス",
  Caserta: "カゼルタ",
  Castellon: "カステリョン",
  "CASTELO BRANCO": "カステロ·ブランコ",
  Castlereagh: "キャッスル",
  Catamarca: "カタマルカ",
  CATANDUANES: "カタンドアネス島",
  Catania: "カタニア",
  Catanzaro: "カタンツァロ",
  Cauca: "カウカ",
  CAVITE: "カビテ州",
  "Ceadir-Lunga": "Ceadir·ルンガ",
  Ceara: "セアラ州",
  CEBU: "セブ",
  Celje: "ツェリェ",
  Central: "中央の",
  "Central Luzon": "中部ルソン",
  "Central Visayas": "中央ビサヤ",
  Cesar: "セザール",
  CH: "チャンディーガル",
  Chachoengsao: "チャチェンサオ",
  Chaco: "チャコ",
  "Chai Nat": "チャイナート",
  Chaiyaphum: "チャイヤプーム",
  "Chakassky Republic": "Chakassky共和国",
  "Changhua County": "彰化県",
  Chanthaburi: "チャンタブリー",
  Charente: "シャラント",
  "Charente-Maritime": "シャラントマリティム",
  "CHECHENO-INGUSHETIA": "CHECHENO-イングーシ",
  CHECHNYA: "チェチェン",
  Chelm: "ヘルム",
  CHELYABINSK: "チェリャビンスク",
  Cher: "シェール",
  Cheshire: "チェシャー",
  "Chiang Mai": "チエンマイ",
  "Chiang Rai": "チェンライ",
  Chiapas: "チアパス州",
  "Chiayi City": "嘉義市",
  "Chiayi County": "嘉義県",
  Chieti: "キエティ",
  CHIOU: "Chiouさん",
  Chisinau: "キシナウ",
  CHITA: "チタ",
  Choco: "チョコ",
  "Chon Buri": "チョンブリ",
  Chongqing: "重慶市",
  Chubut: "チュブト州",
  CHUKOT: "チュコート",
  "Chukotka Auton. dist": "チュコトAuton。 DIST",
  Chumphon: "チュムポン",
  Ciechanow: "チェハヌフ",
  "Ciudad Real": "シウダードレアル",
  Clare: "クレア",
  Cleveland: "クリーブランド",
  Cluj: "クルージュ",
  "Cntrl Mindanao": "CNTRLミンダナオ",
  CO: "コロラド州",
  Coahuila: "コアウイラ州",
  COIMBRA: "コインブラ",
  Coleraine: "コールレーン",
  Colima: "コリマ",
  Como: "コモ",
  Constanta: "コンスタンツァ",
  Cookstown: "クック",
  Copenhagen: "コペンハーゲン",
  Coquimbo: "コキンボ",
  Cordoba: "コルドバ",
  Corinthia: "コリン",
  Cork: "コーク",
  Cornwall: "コーンウォール",
  Correze: "コレーズ",
  Corrientes: "コリエンテス",
  "Corse-du-Nord": "コルス·デュ·ノール",
  "Corse-du-Sud": "コルス=デュ=シュド",
  Corum: "チョルム",
  Cosenza: "コゼンツァ",
  COTABATO: "コタバト",
  "Cote-d Or": "コート-Dまたは",
  "Cotes-d Armor": "コーツ-Dアーマー",
  "Cova da Beira": "コヴァ·ダ·ベイラ",
  Craigavon: "Craigavonの",
  Cremona: "クレモナ",
  Creuse: "クルーズ",
  Crotone: "クロトネ",
  CT: "コネチカット",
  CT: "チャッティースガル",
  Cuenca: "クエンカ",
  Cumbria: "カンブリア州",
  Cundinamarca: "クンディナマルカ",
  Cuneo: "クネオ",
  Cuzco: "クスコ",
  Czestochowa: "チェンストホーバ",
  "D.O.M.T.O.M": "DOMTOM",
  DAGESTAN: "ダゲスタン",
  "Dalarnas Län": "ダーラナ蘭",
  "Dar-es-Salaam": "ダルエスサラーム",
  Darlington: "ダーリントン",
  DAVAO: "ダバオ",
  "DAVAO DEL NORTE": "ダバオ·デル·ノルテ",
  "DAVAO DEL SUR": "ダバオDEL SUR",
  "DAVAO ORIENTAL": "ダバオオリエンタル",
  DC: "コロンビア特別区",
  DD: "ダマンディーウ",
  DE: "デラウェア州",
  Debrecen: "デブレツェン",
  "Delta Amacuro": "デルタAmacuro",
  Denizli: "デニズリ",
  Derbyshire: "ダービーシャー州",
  Devon: "デボン",
  "DI Aceh Aceh": "DIアチェアチェ",
  "DI Yogyakarta Yogyak": "DIジョグYogyak",
  "Distrito Especial": "ブラジリア特別な",
  "Distrito Federal": "連邦区",
  Diyarbakir: "ディヤルバクル",
  "DKI Jakarta Jakarta": "DKIジャカルタ",
  DL: "ニューデリー",
  DN: "DADRAとナガル·ハヴ",
  DOLNOSLASKIE: "ドルノシロンスク",
  Donegal: "ドニゴール",
  Dordogne: "ドルドーニュ",
  Dorset: "ドーセット州",
  Doubs: "ドゥー",
  Douro: "ドーロ",
  Down: "ダウン",
  DRAMAS: "ドラマ",
  Dravograd: "ドラボグラード",
  Drenthe: "ドレンテ州",
  Drome: "ドローム",
  Dublin: "ダブリン",
  "Dubrovnik-Neretva": "ドブロヴニク - ネレトバ川",
  "Dumfries a. Galloway": "フリース。ギャロウェー",
  Dunbartonshire: "ダンバートンシャイア",
  Dungannon: "Dungannonの",
  Durango: "ドゥランゴ",
  Durham: "ダラム",
  "East Lothian": "イーストロージアン",
  "East Riding": "イーストライディング",
  "East Sussex": "イーストサセックス州",
  "Eastern Cape": "東ケープ州",
  "EASTERN SAMAR": "東部サマル",
  "Eastern Visayas": "東部Visayas",
  Edirne: "エディルネ",
  Eger: "エゲル",
  Elblag: "エルブロンク",
  Enna: "エンナ",
  "Entre Douro e Vouga": "エントレ·ドウロ電子ボーガ川",
  "Entre Rios": "エントレリオス州",
  Erzincan: "エルジンジャン",
  Erzurum: "エルズルム",
  Eskisehir: "エスキシェヒル",
  "Espirito Santo": "エスピリトサント州",
  Essex: "エセックス",
  Essonne: "エソンヌ",
  "Estado de Mexico": "Estadoメキシコ",
  "Etelä-Suomi": "Etelä-スオミ",
  Eure: "ウール",
  "Eure-et-Loir": "ウール·エ·ロワール",
  EVORA: "エボラ",
  Falcon: "ファルコン",
  Fermanagh: "ファーマナ州",
  Ferrara: "フェラーラ",
  Fife: "横笛",
  Finistere: "フィニステール",
  "Finnmark Fylke": "フィンマルクFylke",
  Firenze: "フィレンツェ",
  FL: "フロリダ州",
  Flevoland: "フレヴォラント州",
  Foggia: "フォッジャ",
  Forli: "フォルリ",
  Formosa: "フォルモサ",
  "Frederiksborg amt": "フレデリクスボーAMT",
  Fribourg: "フリブール",
  Friesland: "フリースラント州",
  Frosinone: "フロジノーネ",
  Fujian: "福建省",
  "Fyn amt": "フュAMT",
  GA: "ゴア",
  GA: "ジョージア州",
  Galati: "ガラツ",
  Galway: "ゴールウェイ",
  Gansu: "甘粛省",
  Gard: "ガード",
  "Garonne (Haute)": "ガロンヌ（オート）",
  Gauteng: "ハウテン",
  "Gävleborgs Län": "Gävleborgs蘭",
  Gaziantep: "ガジアンテプ",
  Gdansk: "グダニスク",
  Gelderland: "ヘルダーラント",
  Geneva: "ジュネーブ",
  Genova: "ジェノバ",
  Gerona: "ヘロナ",
  Gers: "ジェール",
  Giresun: "Giresunの",
  Gironde: "ジロンド県",
  Giurgiu: "ジウルジウ",
  GJ: "グジャラート",
  Glarus: "グラールス州",
  Gloucestershire: "グロスターシャー州",
  Goias: "ゴイアス州",
  Gorizia: "ゴリツィア",
  Gorzow: "ゴジュフウィエル",
  "Gotlands Län": "Gotlands蘭",
  Grampian: "グランピアン",
  Granada: "グラナダ",
  Graubuenden: "グラウビュンデン",
  "Greater London": "グレーター·ロンドン",
  "Greater Manchester": "グレーター·マンチェスター",
  Groningen: "フローニンゲン",
  "Grønlands amt": "GrønlandsAMT",
  Grosseto: "グロッセート",
  GU: "グアム島",
  Guadalajara: "グアダラハラ",
  Guanajuato: "グアナフアト",
  Guangdong: "広東",
  Guangxi: "広西壮族自治区",
  GUARDA: "グアルダ",
  Guerrero: "ゲレロ",
  Guipuzcoa: "ギプスコア",
  Guizhou: "貴州省",
  Gwent: "グウェント州",
  Gwynedd: "グウィネズ",
  Gyor: "ジェール",
  "Gyor-Moson-Sopron": "ジョール·お客様の滞在を心よりショプロン",
  Haifa: "ハイファ",
  Hainan: "海南",
  Hainaut: "エノー州",
  "Hajdu-Bihar": "アイドゥー-ビハール",
  Hakkari: "ハッキャーリ",
  "Hallands Län": "Hallands蘭",
  Halton: "ハルトン",
  Hamburg: "ハンブルク",
  Hampshire: "ハンプシャー",
  Hanoi: "ハノイ",
  Hartlepool: "ハートルプール",
  Hatay: "ハタイ",
  "Haut-Rhin": "オーラン",
  "HAUTE-CORSE": "オートコルス",
  "Hauts-de-Seine": "オード·ド·セーヌ",
  "Hawke´s Bay": "ホークスベイ",
  Hebei: "河北省",
  "Hedmark Fylke": "ヘドマルクFylke",
  Heilongjiang: "黒竜江省",
  Henan: "河南省",
  Herault: "エロー",
  "Hereford and Worcs.": "ヘレフォードとWorcs。",
  Herefordshire: "ヘレフォードシャー",
  Hertfordshire: "ハートフォードシャー州",
  Hessen: "ヘッセン",
  HI: "ハワイ",
  Hidalgo: "イダルゴ",
  Highland: "ハイランド",
  "Highlands-Altay Rep.": "高地·アルタイ議員",
  "Hong Kong Island": "香港島",
  "Hordaland Fylke": "ホルダランFylke",
  "Hors-France": "オードブルフランス",
  HP: "ヒマチャル·プラデシュ",
  HR: "ハリヤナ州",
  "Hrastnik Lasko": "Hrastnik Laskoの",
  "Hsinchu City": "新竹市",
  "Hsinchu County": "新竹県",
  "Hualien County": "花蓮県",
  HUANUCO: "ワヌコ",
  Hubei: "湖北省",
  Huelva: "ウエルバ",
  Huesca: "ウエスカ",
  Huila: "ウイラ",
  Humberside: "ハンバーサイド州",
  Hunan: "湖南省",
  Hunedoara: "フネドアラ",
  IA: "アイオワ州",
  Ialomita: "ヤロミツァ川",
  Iasi: "ヤシ",
  Ica: "イカ",
  ID: "アイダホ州",
  IFUGAO: "イフガオ州",
  IL: "イリノイ州",
  "ILHA DA GRACIOSA": "グランデ島DAグラシオーザ",
  "ILHA DA MADEIRA": "グランデ島DA MADEIRA",
  "ILHA DAS FLORES": "グランデ島DAS FLORES",
  "ILHA DE PORTO SANTO": "ボイペーバポルト·サント",
  "ILHA DE SANTA MARIA": "ボイペーバSANTA MARIA",
  "ILHA DE SAO JORGE": "ボイペーバサン·ジョルジェ",
  "ILHA DE SAO MIGUEL": "ボイペーバサンミゲル",
  "ILHA DO CORVO": "グランデ島DO CORVO",
  "ILHA DO FAIAL": "グランデ島はファイアルのDO",
  "ILHA DO PICO": "グランデ島はPICOのDO",
  "ILHA TERCEIRA": "グランデ島テルセイラ島",
  "Ilirska Bistrica": "Ilirska Bistricaの",
  "Ille-et-Vilaine": "イル=エ=ヴィレーヌ川",
  Ilocos: "イロコス",
  "ILOCOS NORTE": "イロコスノルテ州",
  "ILOCOS SUR": "イロコス·シュール·",
  ILOILO: "イロイロ",
  Imperia: "インペリア",
  IN: "インディアナ州",
  Indre: "アンドル",
  "Indre-et-Loire": "アンドル·エ·ロワール",
  "Ingushetija Republic": "Ingushetija共和国",
  "Inverness-Shire": "インバネス·シャイア",
  "Irian Jaya Irian Jay": "イリアンジャヤイリアンジェイ",
  Irkutsk: "イルクーツク",
  ISABELA: "イザベラ",
  Isere: "イゼール",
  Isernia: "イゼルニア",
  Islamabad: "イスラマバード",
  "Isle Of Arran": "アラン島",
  "Isle Of Barra": "バラ島",
  "Isle Of Benbecula": "ベンベキュラアイルオブ",
  "Isle Of Bute": "ビュート島",
  "Isle Of Canna": "カンナアイルオブ",
  "Isle Of Coll": "collの島",
  "Isle Of Colonsay": "コロンゼアイルオブ",
  "Isle Of Cumbrae": "Cumbraeアイルオブ",
  "Isle Of Eigg": "Eiggアイルオブ",
  "Isle Of Gigha": "ギーアアイルオブ",
  "Isle Of Harris": "ハリス島",
  "Isle Of Iona": "アイオナ島",
  "Isle Of Islay": "アイラ島の島",
  "Isle Of Jura": "ジュラの島",
  "Isle Of Lewis": "ルイス島",
  "Isle Of Mull": "マル島",
  "Isle Of North Uist": "北ユイストアイルオブ",
  "Isle Of Rum": "ラム島",
  "Isle Of Scalpay": "Scalpayアイルオブ",
  "Isle Of Skye": "スカイ島",
  "Isle Of South Uist": "サウスウイスト島ワイト",
  "Isle Of Tiree": "タイリー島の島",
  "Isle of Wight": "ワイト島",
  "Isles Of Scilly": "シリー諸島",
  Isparta: "ウスパルタ",
  Istanbul: "イスタンブール",
  Istra: "イストラ半島",
  "Itä-Suomi": "ITA-スオミ",
  IVANOV: "イワノフ",
  Izmir: "イズミル",
  Izola: "イゾラ",
  Jaen: "ハエン",
  Jalisco: "ハリスコ州",
  "Jambi Jambi": "ジャンビジャンビ",
  "Jämtlands Län": "Jämtlands蘭",
  "Jasz-Nagykun-Szolnok": "Jasz-Nagykun-ソルノク",
  "Jawa Barat West Java": "ジャワバラット州西ジャワ",
  "Jawa Tengah Central": "ジャワトゥンガ州中央",
  "Jawa Timur East Java": "ジャワティムール東ジャワ",
  Jerusalem: "エルサレム",
  JH: "ジャールカンド",
  Jiangsu: "江蘇省",
  Jiangxi: "江西省",
  Jilin: "吉林省",
  JK: "ジャンムー＆カシミール",
  Johannesburg: "ヨハネスブルク",
  Johor: "ジョホール州",
  "Jönköpings Län": "Jönköpings蘭",
  "Jost Van Dyke": "ヨーストヴァンダイク島",
  Jujuy: "フフイ州",
  JUNIN: "フニン",
  Jura: "ジュラ",
  KA: "カルナタカ",
  "KABARDINO-BALKARIA": "カバルダBALKARIA",
  Kalasin: "カラシン",
  "Kalimantan Barat Wes": "カリマンタンバラット州ウェス",
  "Kalimantan Selatan S": "カリマンタンスラタンS",
  "Kalimantan Tengah Ce": "カリマンタントゥンガ州のCe",
  "Kalimantan Timur Eas": "カリマンタンティムールイース",
  KALINGA: "カリンガ",
  KALININGRAD: "カリーニングラード",
  Kalisz: "カリシュ",
  "Kalmar Län": "カルマル蘭",
  KALMYKIYA: "カルムイキア",
  KALUGA: "カルーガ",
  "Kamphaeng Phet": "カンペーンペッ",
  Kanchanaburi: "カンチャナブリー",
  "Kaohsiung City": "高雄市",
  KARABUK: "カラビュク",
  "KARACHAY-CHERKESSIA": "カラチャイ·CHERKESSIA",
  Karaman: "カラマン",
  KARELIA: "カレリア",
  Karlovac: "カルロバツ",
  Kars: "カルス",
  Kashmir: "カシミール",
  Kastamonu: "カスタモヌ",
  Katowice: "カトウィツェ",
  Kavan: "カバン",
  Kayseri: "カイセリ",
  Kecskemet: "ケチケメート",
  Kedah: "ケダ州",
  "Keelung City": "基隆市",
  Kelantan: "ケランタン州",
  Kent: "ケント",
  Kerry: "ケリー",
  Khabarovsk: "ハバロフスク",
  "Khon Kaen": "コンケン",
  Khyber: "カイバル",
  Kildare: "キルデア",
  Kilkenny: "キルケニー",
  Kilkis: "キルキス",
  "Kingston-Upon-Hull": "キングストン·アポン·ハル",
  "Kinmen County": "金門県",
  KIROV: "キーロフ",
  KL: "ケララ",
  "København amt": "コペンハーゲンAMT",
  Kocaeli: "コジャエリ",
  "Komarom-Esztergom": "Komaromの、エステルゴム",
  Konin: "コニン",
  Konya: "コンヤ",
  Koper: "コペル",
  "Koprivnica-Krizevci": "コプリプニツァ-クリジェフツィ",
  Kowloon: "カオルーン",
  Krabi: "クラビ",
  Krakow: "クラクフ",
  Kranj: "クラーニ",
  KRASNODAR: "クラスノダール",
  KRASNOYARSK: "クラスノヤルスク",
  "Kronobergs Län": "Kronobergs蘭",
  "Krung Thep": "クルンテプ",
  KS: "カンザス州",
  "Kuala-Lumpur": "クアラルンプール -",
  KURGAN: "クルガン",
  KURSK: "クルスク",
  KUTAHYA: "キュタヒヤ",
  "Kwazulu/Natal": "クワ/ナタール",
  KY: "ケンタッキー州",
  "L Aquila": "Lラクイラ",
  LA: "ルイジアナ州",
  "La Coruña": "ラコルニャ",
  "La Guajira": "ラグアヒラ",
  "La Libertad": "ラリベルタド",
  "La Pampa": "ラ·パンパ",
  "La Rioja": "ラリオハ",
  "La Spezia": "ラスペツィア",
  "LA UNION": "ラウニオン",
  Labuan: "ラブアン島",
  LAD: "ラダク",
  Lambayeque: "ランバイェケ",
  Lampang: "ラムパーン",
  Lamphun: "ラムプーン",
  "Lampung Lampung": "ランプンランプン",
  "LANAO DEL NORTE": "LanaoデルNORTE",
  "LANAO DEL SUR": "Lanaoデルシュール",
  Lanarkshire: "ラナークシャイア",
  Lancashire: "ランカシャー州",
  Landes: "ランデス",
  "Länsi-Suomi": "Länsi-スオミ",
  Laois: "リーシュ",
  Lappi: "ラッピ",
  Lara: "ララ",
  Larne: "ラーン",
  "Las Palmas": "ラスパルマス",
  Latina: "ラティナ",
  LD: "ラクシャディープ諸島",
  Lecce: "レッチェ",
  Lecco: "レッコ",
  Legnica: "レグニツァ",
  "Leicester City": "レスター·シティ",
  Leicestershire: "レスターシャー州",
  LEIRIA: "レイリア",
  Leitrim: "リートリム",
  LENINGRADSKAYA: "レニングラード",
  Leon: "レオン",
  Lerida: "レリダ",
  Leszno: "レシュノ",
  LEYTE: "レイテ",
  "Lianjiang County": "連江県",
  Liaoning: "遼寧",
  Libertador: "リベルタドール",
  Liege: "リエージュ",
  "Lika-Senj": "リカ - セニ",
  Lillehammer: "リレハンメル",
  Limavady: "Limavadyの",
  Limburg: "リンブルフ",
  Limerick: "リマリック",
  Lincolnshire: "リンカンシャー州",
  LIPETSK: "リペツク",
  Lisboa: "リスボン",
  Lisburn: "リスバーン",
  Livorno: "リボルノ",
  "Ljubljana-Bezigrad": "リュブリャナ-Bezigrad",
  "Ljubljana-Center": "リュブリャナ·センター",
  "Ljubljana-Moste-Polj": "リュブリャナ-MOSTE-Polj",
  "Ljubljana-Siska": "リュブリャナ-Siska",
  "Ljubljana-Vic-Rudnik": "リュブリャナ-VIC-Rudnik",
  Lodi: "ロディ",
  Loei: "ルーイ",
  Logatec: "Logatecの",
  "Loir-et-Cher": "ロアールエシェール",
  Loire: "ロアール",
  "Loire (Haute)": "ロワール（オート）",
  "Loire-Atlantique": "ロアールアトランティック",
  Loiret: "ロアレ",
  London: "ロンドン",
  Londonderry: "ロンドンデリー",
  Longford: "ロングフォード",
  "Lop Buri": "ロッブリー",
  Loreto: "ロレト",
  "Los Lagos": "ロス·ラゴス",
  Lot: "たくさんの",
  "Lot-et-Garonne": "ロット=エ=ガロンヌ県",
  Lothian: "ロシアン",
  Louth: "ラウス",
  Lovech: "ロベチ",
  "Lower Austria": "オーストリア",
  Lozere: "ロゼール",
  LUBELSKIE: "ルブリン県",
  Lublin: "ルブリン",
  Lucca: "ルッカ",
  LUCENA: "ルセナ",
  Lucerne: "ルツェルン",
  Lugo: "ルーゴ",
  Luton: "ルートン",
  Luxembourg: "ルクセンブルク",
  MA: "マサチューセッツ州",
  Macerata: "マチェラタ",
  "MADRE DE DIOS": "マドレデディオス",
  Madrid: "マドリッド",
  "Mae Hong Son": "メーホンソン",
  MAGADAN: "マガダン",
  Magdalena: "マグダレナ",
  Magherafelt: "Magherafeltの",
  MAGUINDANAO: "マギンダナオ州",
  "Maha Sarakham": "マハSarakham",
  "Maine-et-Loire": "メーヌ·ロワール",
  Malaga: "マラガ",
  Malatya: "マラティヤ",
  "Maluku Maluku": "マルクマルク",
  "Malvinas/Falkland Is": "マルビナス/フォークランドです",
  "Manawatu-Wanganui": "マナワツ·ワンガヌイ",
  Manche: "マンシュ",
  Manisa: "マニサ",
  Mantova: "マントヴァ",
  Maramures: "マラムレ",
  Maranhao: "マランハオ",
  Mardin: "マルディン",
  Maribor: "マリボル",
  "Marijskaya Republic": "Marijskaya共和国",
  MARINDUQUE: "マリンドゥケ",
  Marne: "マルヌ",
  "Marne (Haute)": "マルヌ（オート）",
  "Masa Carrara": "マサカラーラ",
  MASBATE: "マスバテ",
  Matera: "マテラ",
  "Mato Grosso": "マトグロッソ州",
  "Mato Grosso do Sul": "マットグロッソドスル",
  Maule: "モール",
  Mayenne: "マイエンヌ",
  Mayo: "メイヨー",
  MB: "マニトバ州",
  MD: "メリーランド州",
  ME: "メイン",
  Meath: "ミーズ",
  "Mecklenburg-Vorpommern": "メクレンブルクフォアポンメルン",
  "Médio Tejo": "メディオテージョ",
  Melaka: "マラッカ",
  Mendoza: "メンドーサ",
  Merida: "メリダ",
  Merseyside: "マージーサイド",
  Messina: "メッシーナ",
  Meta: "メタ",
  "Metro Manila": "メトロマニラ",
  "Meurthe-et-Moselle": "ムルト=エ=モゼル県",
  Meuse: "ムーズ川",
  MH: "マハラシュトラ",
  MI: "ミシガン州",
  "Miaoli County": "苗栗県",
  Michoacan: "ミチョアカン州",
  "Mid Glamorgan": "ミッドグラモーガン",
  Middlesbrough: "ミドルズブラ",
  Middlesex: "ミドルセックス",
  Midlothian: "ミッドロージアン",
  "Milton Keynes": "ミルトンキーンズ",
  "Minas Gerais": "ミナスジェライス州",
  "MINDORO OCCIDENTAL": "ミンドロ島西洋の",
  "MINDORO ORIENTAL": "ミンドロオリエンタル",
  Miranda: "ミランダ",
  "MISAMIS OCCIDENTAL": "ミサミスオクシデンタル州",
  "MISAMIS ORIENTAL": "ミサミスオリエンタル州",
  Misiones: "ミシオネス",
  Miskolc: "ミシュコルツ",
  ML: "メガラヤ州",
  MN: "マニプール",
  MN: "ミネソタ州",
  MO: "ミズーリ州",
  Modena: "モデナ",
  Monagas: "モナガス",
  Monaghan: "モナハン",
  Montana: "モンタナ州",
  Montevideo: "モンテビデオ",
  Moquegua: "モケグア",
  Morbihan: "モルビアン",
  MORDOVIYA: "モルドビヤ",
  "Møre og Romsdal F.": "多くのOG Romsdal F.",
  Morelos: "モレロス州",
  Moscow: "モスクワ",
  Moselle: "モーゼル",
  MOSKVA: "モスクワ",
  MP: "マディヤプラデシュ",
  Mpumalanga: "ムプマランガ州",
  MS: "ミシシッピ州",
  Mugla: "ムーラ",
  Mukdahan: "ムクダハン",
  Murcia: "ムルシア",
  Mures: "ムレシ川",
  Murmansk: "ムルマンスク",
  MZ: "ミゾラム",
  Nagykanizsa: "ナジカニジャ",
  Nairn: "ネアン",
  "Nakhon Nayok": "ナコーンNayok",
  "Nakhon Pathom": "ナコンバトム",
  "Nakhon Phanom": "ナコンラチャナコンパノム",
  "Nakhon Ratchasima": "ナコンラチャシマ",
  "Nakhon Sawan": "ナコンサワン",
  "Nakhon Si Thammarat": "ナコンシータマラート",
  Namur: "ナミュール",
  Nan: "ナン",
  "Nantou County": "南投県",
  Naples: "ナポリ",
  Narathiwat: "ナラーティワート",
  "NATIONAL CAPITAL REG": "首都REG",
  Navarra: "ナバラ",
  Nayarit: "ナヤリット",
  NB: "ニューブランズウィック州",
  NC: "ノースカロライナ州",
  ND: "ノースダコタ州",
  NE: "ネブラスカ州",
  "Negeri Sembilan": "ヌグリスンビラン州",
  "NEGROS OCCIDENTAL": "ネグロスオクシデンタル州",
  "NEGROS ORIENTAL": "ネグロスオリエンタル",
  "Nei Mongol": "内モンゴル",
  NENETS: "ネネツ語",
  Neuchatel: "ヌーシャテル",
  Neuquen: "ネウケン",
  NEVSEHIR: "ネブシェヒル",
  "New TaipeiCity": "新北市",
  "New Territories": "新界",
  Newbury: "ニューベリー",
  "Newry and Mourne": "リーとモーン",
  Newtownabbey: "ニュータウンアベイ",
  NH: "ニューハンプシャー州",
  Nidwalden: "ニトヴァルデン",
  Niedersachsen: "ニーダーザクセン州",
  Nigde: "ニーデ",
  Ningxia: "寧夏回族自治区",
  NJ: "ニュージャージー州",
  NL: "ナガランド",
  NL: "ニューファンドランド",
  NM: "ニューメキシコ州",
  "Nong Bua Lamphu": "ノン·ブアランプー",
  "Nong Khai": "ノンカイ",
  Nonthaburi: "ノンタブリー",
  "Noord-Brabant": "北ブラバント",
  "Noord-Holland": "北ホラント",
  Nord: "ノール",
  "Nord-Trøndelag Fylk": "ノールトロンデラーグFylk",
  "Nordjylland amt": "ノーユランAMT",
  "Nordland Fylke": "ヌールランFylke",
  "Nordrhein-Westfalen": "ノルトライン·ヴェストファーレン",
  Norfolk: "ノーフォーク",
  "Norrbottens Län": "Norrbottens蘭",
  "Norte de Santander": "ノルテデサンタンデル",
  "NORTH COTABATO": "北コタバト州",
  "North Down": "ノースダウン",
  "North Humberside": "ノースハンバーサイド",
  "North Lincolnshire": "北リンカンシャー",
  "North Somerset": "北サマセット",
  "North Yorkshire": "ノースヨークシャー州",
  "North-Osetiya Republ": "北Osetiya Republ",
  "North-West": "ノース·ウェスト",
  Northamptonshire: "ノーサンプトンシャー州",
  Northern: "ノーザン",
  "Northern Cape": "北ケープ州",
  "Northern Mindanao": "北ミンダナオ",
  "Northern Province": "北部州",
  "NORTHERN SAMAR": "北サマール州",
  Northland: "ノースランド",
  Northumberland: "ノーサンバーランド",
  "Nottingham City": "ノッティンガム市",
  Nottinghamshire: "ノッティンガムシャー州",
  "Nova Gorica": "ノヴァゴリツァ",
  Novara: "ノバラ",
  NOVGOROD: "ノブゴロド",
  "Novo Mesto": "ノヴォ·メスト",
  NOVOSIBIRSK: "ノボシビルスク",
  "Nowy Sacz": "ノウィソンチ",
  NS: "ノバスコシア州",
  NSW: "ニューサウスウェールズ州",
  NT: "ノーザン·テリトリー",
  NT: "ノースウェスト準州",
  "NthEast Lincolnshire": "NthEastリンカンシャー",
  NU: "ヌナブト",
  "NUEVA ECIJA": "ヌエバエシハ州",
  "Nueva Esparta": "ヌエバEsparta",
  "NUEVA VIZCAYA": "ヌエバビスカヤ州",
  "Nuevo Leon": "ヌエボレオン州",
  Nuoro: "ヌオロ",
  "Nusa Tenggara Barat": "ヌサテンガラレナソフィア",
  "Nusa Tenggara Timur": "ヌサテンガラティムール",
  NV: "ネバダ州",
  NY: "ニューヨーク州",
  Nyiregyhaza: "ニーレジハーザ",
  Oaxaca: "オアハカ",
  Obwalden: "オプヴァルデン",
  Oeste: "オエステ",
  Offaly: "オファリー",
  OH: "オハイオ州",
  Oise: "オアーズ",
  OK: "オクラホマ州",
  OLONGAPO: "オロンガポ",
  Olsztyn: "オルシュティン",
  Omagh: "オマー",
  OMSK: "オムスク",
  ON: "オンタリオ州",
  "Oost-Vlaanderen": "オースト-ブラーンデレン",
  "Oppland Fylke": "オップランFylke",
  OR: "オレゴン州",
  Ordu: "オルドゥ",
  "Örebro Län": "オレブロ蘭",
  OREL: "オレル",
  ORENBURG: "オレンブルグ",
  Orense: "オレンセ",
  Oristano: "オリスタノ",
  Orkney: "オークニー諸島",
  Orne: "オルヌ",
  "Osijek-Baranja": "オシエク-Baranja",
  Oslo: "オスロ",
  "Östergötlands Län": "エステルイェトランド蘭",
  "Østfold Fylke": "エーストフォールFylke",
  Otago: "オタゴ",
  Oulu: "オウル",
  Overijssel: "オーフェルアイセル",
  Oxfordshire: "オックスフォードシャー州",
  PA: "ペンシルベニア州",
  Padova: "パドバ",
  Pahang: "パハン州",
  PALAWAN: "パラワン",
  Palencia: "パレンシア",
  Palermo: "パレルモ",
  PAMPANGA: "パンパンガ州",
  PANGASINAN: "パンガシナン州",
  Para: "パラ",
  Paraiba: "パライバ州",
  Parana: "パラナ",
  Paris: "パリ",
  Parma: "パルマ",
  "Pas-de-Calais": "パドカレ",
  Pasco: "パスコ",
  "Pathum Thani": "パトゥムターニー",
  Pattani: "パッタニ",
  Pavia: "パビア",
  PB: "パンジャブ",
  PE: "プリンスエドワード島",
  Pecs: "ペーチ",
  "Penghu County": "澎湖県",
  PENZA: "ペンザ",
  Perak: "ペラ州",
  Perlis: "ペルリス",
  PERM: "ペルミ",
  Pernambuco: "ペルナンブコ州",
  Perthshire: "パース",
  Perugia: "ペルージャ",
  Pesaro: "ペザロ",
  Pescara: "ペスカーラ",
  Pest: "害虫",
  Peterborough: "ピーターバラ",
  Phangnga: "パンガー",
  Phatthalung: "パッタルン",
  Phayao: "パヤオ",
  Phetchabun: "ペッチャブン山脈",
  Phetchaburi: "ペッチャブリー",
  Phitsanulok: "ピッサヌローク",
  "PHRA NAKHON SI AYUTT": "プラナコーンSI AYUTT",
  Phrae: "プレー",
  Phuket: "プーケット",
  Piacenza: "ピアツェンツァ",
  Piaui: "ピアウイ州",
  Pila: "ピラ",
  "Pingtung County": "屏東県",
  "Pinhal Interior N.": "ピニャインテリアN.",
  "Pinhal Interior Sul": "ルドのインテリア·スル",
  Piran: "ピラン",
  Pisa: "ピサ",
  Pistoia: "ピストイア",
  Piura: "ピウラ",
  Plock: "プロック",
  Plymouth: "プリマス",
  Pontevedra: "ポンテベドラ",
  Poole: "プール",
  Pordenone: "ポルデノーネ",
  PORTALEGRE: "ポルタレグレ",
  Portsmouth: "ポーツマス",
  Postojna: "ポストイナ",
  Potenza: "ポテンツァ",
  Powys: "ポウイス",
  Poznan: "ポズナン",
  PR: "プエルトリコ",
  "Prachin Buri": "プラチンブリ",
  "PRACHUAP KHIRI KHAN": "プラチュワップキーリーカン",
  Praha: "プラハ",
  Prato: "プラト",
  "Primorje-Gorski Kot.": "Primorje-Gorskiコット。",
  PRIMORSKIY: "沿海",
  Przemysl: "プシェミシル",
  PSKOV: "プスコフ",
  Ptuj: "プトゥイ",
  Puebla: "プエブラ",
  "Pulau Pinang": "ペナンペナン",
  Puno: "プノ",
  Putumayo: "プトゥマヨ",
  "Puy-de-Dôme": "ピュイドドーム",
  PW: "パラオ",
  PY: "ポンディシェリー",
  "Pyrenees (Hautes)": "ピレネー（リズール）",
  "Pyrenees-Atlantiques": "ピレネー=アトランティック県",
  "Pyrenees-Orientales": "ピレネー=オリアンタル県",
  QC: "ケベック州",
  Qinghai: "青海",
  QLD: "クイーンズランド州",
  "Quarry Bay": "鰂魚",
  Queretaro: "ケレタロ",
  QUEZON: "ケソン州",
  Quindio: "キンディオ",
  QUIRINO: "キリノ州",
  Quito: "キト",
  "Radlje Ob Dravi": "RadljeオビDravi",
  Radom: "ラドム",
  Radovljica: "ラドヴリツァ",
  Ragusa: "ラグーザ",
  RANONG: "ラノーン",
  RATCHABURI: "ラチャブリ",
  Ravenna: "ラベンナ",
  "Ravne Na Koroskem": "RavneナKoroskem",
  Reading: "読書",
  "Redcar and Cleveland": "レッドカーとクリーブランド",
  "Reggio Calabria": "レッジョ·ディ·カラブリア",
  "Reggio Emilia": "レッジョ·エミリア",
  "Region Metropolitana": "地域メトロポリターナ",
  Renfrewshire: "レンフルーシャイア",
  "Rep di San Marino": "担当者·ディ·サン·マリノ",
  Réunion: "レユニオン",
  "Rheinland-Pfalz": "ラインラント·プファルツ州",
  Rhone: "ローヌ",
  RI: "ロードアイランド州",
  "Riau Riau": "リアウ州リアウ州",
  "Ribe amt": "リーベAMT",
  Rieti: "リエティ",
  Rimini: "リミニ",
  "Ringkøbing amt": "リンケビングAMT",
  "Rio De Janeiro": "リオ·デ·ジャネイロ",
  "Rio Grande de Norte": "リオグランデドノルテ",
  "Rio Grande do Sul": "リオグランデドスル",
  "Rio Negro": "リオネグロ",
  Risaralda: "リサラルダ",
  RIZAL: "リサール州",
  Rize: "リゼ",
  RJ: "ラジャスタン",
  "Rochester Up. Medway": "ロチェスターアップ。メドウェイ",
  "Rogaland Fylke": "ローガランFylke",
  Rome: "ローマ",
  Rondonia: "ロンドニア",
  Roraima: "ロライマ",
  "Roskilde amt": "ロスキレAMT",
  "Ross-Shire": "ロス·シャイア",
  ROSTOV: "ロストフ",
  Rovigo: "ロビゴ",
  Ruse: "策略",
  Rutland: "ラトランド",
  RYAZAN: "リャザン",
  Rzeszow: "ジェシュフ",
  SA: "南オーストラリア州",
  "Sa Kaeo": "SAプラケオ",
  Saarland: "ザールラント州",
  Sabah: "サバ州",
  Sachsen: "ザクセン",
  "Sachsen-Anhalt": "ザクセンアンハルト",
  Sakarya: "サカリヤ川",
  SAKHA: "サハ",
  SAKHALIN: "サハリン",
  "SAKON NAKHON": "サコンナコン",
  Salamanca: "サラマンカ",
  Salerno: "サレルノ",
  Salta: "サルタ",
  Salzburg: "ザルツブルク",
  SAMAR: "サマル",
  Samsun: "サムスン",
  "SAMUT PRAKAN": "サムットプラカーン",
  "SAMUT SAKHON": "サムッSAKHON",
  "SAMUT SONGKHRAM": "サムトソンクラム",
  "San Anders de Provi:": "サンアンダース·デ·Provi：",
  "San Juan": "サンファン",
  "San Luis": "サンルイス",
  "San Luis Potosi": "サンルイスポトシ",
  "San Martín": "サンマルティン",
  SANLIURFA: "シャンルウルファ",
  "Santa Catarina": "サンタカタリナ州",
  "Santa Cruz": "サンタクルス",
  "Santa Fe": "サンタフェ",
  Santander: "サンタンデル",
  SANTAREM: "サンタレン",
  Santiago: "サンティアゴ",
  "Santiago Del Estero": "サンチアゴデルエステロ",
  "Sao Paulo": "サンパウロ",
  "Saone (Haute)": "ソーヌ（オート）",
  "Saone-et-Loire": "ソーヌ=エ=ロワール県",
  "SARA BURI": "サラブリ",
  SARATOV: "サラトフ",
  Sarawak: "サラワク州",
  Sarthe: "サルト",
  Sassari: "サッサリ",
  "Satu Mare": "サトゥマーレ",
  SATUN: "サトゥン",
  Savoie: "サボア",
  "Savoie (Haute)": "サヴォワ（オート）",
  Savona: "サボナ",
  SC: "サウスカロライナ州",
  Schaffhausen: "シャフハウゼン",
  "Schleswig-Holstein": "シュレースヴィヒ=ホルシュタイン州",
  Scotland: "スコットランド",
  SD: "サウスダコタ州",
  Segovia: "セゴビア",
  "Seine-et-Marne": "セーヌ·エ·マルヌ",
  "Seine-Maritime": "セーヌマリティム",
  "Seine-Saint-Denis": "セーヌ·サン·ドニ",
  Selangor: "セランゴール州",
  Select: "選択",
  "Sentjur Pri Celju": "SentjurぷりCelju",
  Sergipe: "セルジペ州",
  "Severo-Kazakhstansk": "セベロ-Kazakhstansk",
  "SEVERO-OSETINSKAYA": "セベロ-OSETINSKAYA",
  Sevilla: "セビリア",
  "Sevres (Deux)": "セーヴル（ドゥ）",
  Shaanxi: "陝西",
  Shandong: "山東省",
  Shanghai: "上海",
  Shanxi: "山西",
  Sharjah: "シャルジャ",
  Shetland: "シェトランド諸島",
  Shropshire: "シュロップシャー州",
  Sibenik: "シベニク",
  Sibiu: "シビウ",
  Sichuan: "四川省",
  Siedlce: "シェドルツェ",
  Siena: "シエナ",
  SILAY: "シライ",
  Sinaloa: "シナロア州",
  Sind: "シンド",
  "SING BURI": "SINGブリ",
  Singapore: "シンガポール",
  Sinop: "シノップ",
  SIQUIJOR: "シキホール島",
  Siracusa: "シラクーザ",
  SIRNAK: "シュルナク",
  "Sisak-Moslavina": "シサク-Moslavina",
  SISAKET: "シーサゲート",
  Sivas: "シバス",
  SK: "サスカチュワン州",
  SK: "シッキム",
  "Skåne Län": "スコーネ蘭",
  "Skofja Loka": "Skofjaロカ",
  SLASKIE: "シュロスキエ",
  Slavonski: "スラ",
  Sligo: "スライゴ",
  Slough: "スラウ",
  "Slovenska Bistrica": "スロバキアBistricaの",
  Slupsk: "スルプスク",
  "Smarje Pri Jelsah": "SmarjeぷりJelsah",
  SMOLENSK: "スモレンスク",
  "Södermanlands Län": "Södermanlands蘭",
  Sofiya: "ソフィア",
  "SOFIYA-GRAD": "ソフィア-GRAD",
  "Sogn og Fjordane F.": "ソグンオフィヨーラネF.",
  Solothurn: "ゾロトゥルン",
  Somerset: "サマセット",
  Somme: "ソンム",
  Somogy: "ショモジ",
  "Sønderjylland amt": "SønderjyllandAMT",
  Sondrio: "ソンドリオ",
  SONGKHLA: "ソンクラー",
  Sonora: "ソノラ州",
  Sopron: "ショプロン",
  "Sør-Trøndelag Fylk": "SOR-トロンデラーグFylk",
  Soria: "ソリア",
  SORSOGON: "ソルソゴン州",
  "SOUTH COTABATO": "南コタバト",
  "South Glamorgan": "サウスグラモーガン州",
  "South Humberside": "南ハンバーサイド",
  "South Luzon": "南ルソン",
  "South Mindanao": "南ミンダナオ",
  "South Yorkshire": "サウスヨークシャー州",
  Southampton: "サウサンプトン",
  Southend: "サウスエンド",
  Southern: "南部の",
  "SOUTHERN LEYTE": "南レイテ",
  Southland: "南部",
  "Split-Dalmatia": "分割ダルマチア",
  "St. Gallen": "ザンクト·ガレン",
  "St. Petersburg": "セントピーターズバーグ",
  "Sta. Cruz Tenerife": "駅。クルス島",
  "Stadt Zagreb": "シュタットザグレブ",
  Staffordshire: "スタフォードシャー州",
  STAVROPOL: "スタブロポリ",
  "Stefan-Voda": "ステファン·ヴォーダ",
  "Sth. Gloucestershire": "STH。グロスターシャー州",
  "Stockholms Län": "ストックホルム蘭",
  "Stockton-on-Tees": "ストックトンオンティーズ",
  "Storstrøm amt": "StorstrømAMT",
  Strabane: "Strabaneの",
  Strathclyde: "ストラスクライド",
  Styria: "スティリア",
  Suceava: "スチヤバ",
  Sucre: "スクレ",
  Suffolk: "サフォーク",
  SUKHOTHAI: "スコータイ",
  "Sulawesi Selatan Sou": "スラウェシスラタン荘",
  "Sulawesi Tengah Cent": "スラウェシトゥンガ州セント",
  "Sulawesi Tenggara So": "スラウェシトゥンガラ州したがって、",
  "Sulawesi Utara North": "スラウェシウタラ州ノース",
  "SULTAN KUDARAT": "サルタンKudarat",
  SULU: "スールー",
  "Sumatera Barat West": "スマトラバラット州西部",
  "Sumatera Selatan Sou": "スマトラスラタン荘",
  "Sumatera Utara North": "スマトラウタラ州ノース",
  "SUPHAN BURI": "スパンブリー県",
  "SURAT THANI": "スラトタニ",
  SURIGAO: "スリガオ",
  "SURIGAO DEL NORTE": "スリガオ·デル·ノルテ",
  "SURIGAO DEL SUR": "スリガオDEL SUR",
  SURIN: "スリン",
  Surrey: "サリー",
  Sussex: "サセックス",
  Sutherland: "サザーランド",
  Suwalki: "スバルキ",
  SWIETOKRZYSKIE: "シフィェンティクシシュ",
  Switzerland: "スイス",
  "Szabolcs-Szat.-Bereg": "サボルチ-Szat.-Bereg",
  Szczecin: "シュチェチン",
  Szeged: "セゲド",
  Szekesfehervar: "セーケシュフェヘールヴァール",
  Szolnok: "ソルノク",
  Szombathely: "ソンバトヘイ",
  Tabasco: "タバスコ",
  Tachira: "タチラ州",
  Tacna: "タクナ",
  "Taichung City": "台中市",
  "Tainan City": "台南市",
  "Taipei City": "台北市",
  "Taitung County": "台東県",
  Tamaulipas: "タマウリパス州",
  TAMBOV: "タンボフ",
  "Taoyuan City": "桃園市",
  Taranaki: "タラナキ",
  Taranto: "タラント",
  TARLAC: "タルラック",
  Tarn: "タルン",
  "Tarn-et-Garonne": "タルン=エ=ガロンヌ県",
  Tarnow: "タルヌフ",
  Tarragona: "タラゴナ",
  TAS: "タスマニア州",
  Tatabanya: "タタバーニャ",
  TATARSTAN: "タタルスタン",
  "TAWI-TAWI": "タウィ - タウィ",
  Tayside: "テーサイド州",
  "Tel Aviv": "テル·アビブ",
  "Telemark Fylke": "テレマークFylke",
  Teramo: "テラモ",
  Terengganu: "トレンガヌ",
  Terni: "テルニ",
  "Territ.-de-Belfort": "Territ.·ド·ベルフォール",
  Teruel: "テルエル",
  TG: "テランガーナ",
  "The Jewish Auton.are": "ユダヤ人のAuton.are",
  "The Nizhniy Novgorod": "ニージニーノブゴロド",
  "The Taymir Auton.dis": "Taymir Auton.dis",
  Thurgau: "トゥールガウ州",
  Thüringen: "チューリンゲン",
  Thurrock: "サロック",
  Tianjin: "天津",
  Ticino: "ティチーノ州",
  "Tierra Del Fuego": "ティエラ·デル·フエゴ",
  "Timor Timur East Tim": "ティモールティムール東ティム",
  Tipperary: "ティペラリー",
  Tiraspol: "ティラスポリ",
  TN: "タミル·ナードゥ州",
  TN: "テネシー州",
  Tocantins: "トカンティンス",
  Tokat: "トカト",
  Toledo: "トレド",
  TOLIMA: "トリマ",
  Tolmin: "トルミン",
  TOMSK: "トムスク",
  Torbay: "トーベイ",
  Tortola: "トルトラ島",
  Torun: "トルン",
  TR: "トリプラ",
  Trabzon: "トラブゾン",
  TRANG: "トラン",
  Transvaal: "トランスバール",
  Trapani: "トラパニ",
  Trento: "トレント",
  Treviso: "トレビゾ",
  Trieste: "トリエステ",
  "Troms Fylke": "トロムスFylke",
  Trujillo: "トルヒーヨ",
  Tucuman: "トゥクマン州",
  TULA: "トゥーラ",
  Tulcea: "トゥルチヤ",
  Turin: "トリノ",
  "Tuva Republic": "トゥヴァ共和国",
  TVER: "トベリ",
  TX: "テキサス州",
  "Tyne and Wear": "ベッドフォードシャー州",
  Tyrol: "チロル",
  Tyrone: "タイローン",
  TYUMEN: "チュメニ",
  TYVA: "トゥヴァ",
  "UBON RATCHATHANI": "ウボンラチャタニ",
  Ucayali: "ウカヤリ",
  Udine: "ウディネ",
  "UDON THANI": "ウドンタニ",
  ULYANOVSK: "ウリヤノフスク",
  "Umm al Qaywayn": "ウンム·アルQaywayn",
  UP: "ウッタルプラデーシュ州",
  "Upper Austria": "アッパーオーストリア",
  "Uppsala Län": "ウプサラ蘭",
  Uri: "ウリ",
  USAK: "ウシャク",
  "Ust-Ordinsky Buryat": "ウスチ·Ordinskyブリヤート",
  UT: "ウッタラーカンド",
  UT: "ユタ州",
  "UTHAI THANI": "ウタイタニ",
  Utrecht: "ユトレヒト",
  UTTARADIT: "ウッタラジ",
  VA: "バージニア州",
  "Val-d Oise": "ヴァル-Dオワーズ",
  "Val-de-Marne": "ヴァル·ド·マルヌ",
  Valais: "ヴァリス",
  Valencia: "バレンシア",
  Valladolid: "バリャドリド",
  "Valle del Cuaca": "ヴァッレ·デル·Cuaca",
  Valparaiso: "バルパライソ",
  Van: "ヴァン",
  Var: "バール",
  Varazdin: "バラジジン",
  Varese: "バレーゼ",
  Vargas: "バルガス",
  "Värmlands Län": "Värmlands蘭",
  Varna: "バルナ",
  Vaslui: "バスルイ",
  "Västerbottens Län": "Västerbottens蘭",
  "Västernorrlands Län": "Västernorrlands蘭",
  "Västmanlands Län": "Västmanlands蘭",
  "Västra Götalands Län": "ヴェストGötalands蘭",
  Vaucluse: "ボークリューズ",
  Vaud: "ヴォー",
  "Vejle amt": "ヴァイレAMT",
  Vendee: "買い手",
  Venice: "ヴェネツィア",
  Veracruz: "ベラクルス州",
  Verbania: "ヴェルバニア",
  Vercelli: "ベルチェリ",
  Verona: "ヴェローナ",
  "Vest-Agder Fylke": "ベストアグデルFylke",
  "Vestfold Fylke": "ベストフォールFylke",
  "Vestsjælland amt": "VestsjællandAMT",
  Veszprem: "ウェスプレーム",
  VI: "米領バージン諸島",
  "VIANA DO CASTELO": "ヴィアナドカステロ",
  "Vibo Valentia": "ビーボバレンチア",
  "Viborg amt": "ビボルAMT",
  VIC: "ビクトリア",
  Vicenza: "ビチェンツァ",
  Vienna: "ウィーン",
  Vienne: "ビエンヌ",
  "Vienne (Haute)": "ヴィエンヌ（オート）",
  "VILA REAL": "ビラレアル",
  "Virgin Gorda": "バージン·ゴルダ",
  "Virovitica-Podravina": "ビロビチツァ-Podravina",
  VISEU: "ビゼウ",
  Viterbo: "ビテルボ",
  Vizcaya: "ビスカヤ",
  Vladivostok: "ウラジオストク",
  VOLGOGRAD: "ボルゴグラード",
  Vorarlberg: "フォアアールベルク州",
  VORONEZH: "ボロネジ",
  Vosges: "ボージュ",
  "Vostochno-Kazakhstan": "Vostochno  - カザフスタン",
  VT: "バーモント州",
  "Vukovar-Srijem": "ヴコヴァル-Srijem",
  WA: "ワシントン",
  WA: "西オーストラリア州",
  Waikato: "ワイカト",
  Walbrzych: "バウブジヒ",
  Warrington: "ウォリントン",
  Warszawa: "ワルシャワ",
  Warwickshire: "ウォリックシャー",
  Waterford: "ウォーターフォード",
  WB: "西ベンガル",
  Wellington: "ウェリントン",
  "West Coast": "ウェストコースト",
  "West Glamorgan": "ウェストグラモーガン",
  "West Lothian": "ウェストロージアン",
  "West Midlands": "ウェスト·ミッドランズ",
  "West Sussex": "ウエストサセックス",
  "West Visayas": "西ビサヤス",
  "West Yorkshire": "ウェストヨークシャー",
  "West-Vlaanderen": "西ブラーンデレン",
  "Western Cape": "西ケープ州",
  "Western Isles": "西部の島",
  "Western Mindanao": "西洋のミンダナオ",
  "WESTERN SAMAR": "WESTERNサマール島",
  Westmeath: "ウェストミーズ",
  Wexford: "ウェクスフォード",
  WI: "ウィスコンシン州",
  Wicklow: "ウィックロー",
  Wilayah: "連邦直轄",
  Wiltshire: "ウィルトシャー州",
  "Windsor & Maidenhead": "ウィンザー＆メードンヘッド",
  Wokingham: "ウォーキンガム",
  Worcestershire: "ウースターシャー",
  Wroclaw: "ブロツラフ",
  WV: "ウェストバージニア州",
  WY: "ワイオミング州",
  Xinjiang: "新疆",
  Xizang: "西蔵",
  "Yakutiya-Saha Rrepub": "Yakutiya-サハRrepub",
  Yakutsk: "ヤクーツク",
  YALA: "ヤラ",
  Yalova: "Yalovaの",
  "YAMALO-NENETS": "YAMALO·ネネツ",
  YAROSLAV: "ヤロスラフ",
  YASOTHON: "Yasothonの",
  Yekaterinburg: "エカテリンブルク",
  "Yilan County": "宜蘭県",
  Yonne: "ヨンヌ県",
  York: "ヨーク",
  Yorkshire: "ヨークシャー",
  YT: "ユーコン州",
  Yucatan: "ユカタン",
  "Yunlin County": "雲林県",
  Yunnan: "雲南",
  Yvelines: "イブリーヌ",
  Zacatecas: "サカテカス",
  "Zadar-Knin": "ザダル·クニン",
  "Zagorje Ob Savi": "Zagorjeオビサビ",
  Zagreb: "ザグレブ",
  Zala: "ザラ",
  ZAMBALES: "サンバレス州",
  "ZAMBOANGA DEL NORTE": "サンボアンガ·デル·ノルテ",
  "ZAMBOANGA DEL SUR": "サンボアンガDEL SUR",
  Zamora: "サモラ",
  Zamosc: "ザモシチ",
  Zaragoza: "サラゴサ",
  Zeeland: "ゼーラント",
  Zhejiang: "浙江省",
  "Zielona Gora": "ジェロナグーラ",
  Zug: "ツーク",
  "Zuid-Holland": "南ホラント",
  Zulia: "スリア州",
  Zurich: "チューリッヒ",
  東京都: "東京",
  大阪府: "大阪",
  愛知県: "愛知",
  神奈川県: "神奈川",
  埼玉県: "埼玉",
  青森県: "青森",
  岩手県: "岩手",
  宮城県: "宮城",
  秋田県: "秋田",
  山形県: "山形",
  福島県: "福島",
  茨城県: "茨城",
  栃木県: "栃木",
  群馬県: "群馬",
  千葉県: "千葉",
  新潟県: "新潟",
  富山県: "富山",
  石川県: "石川",
  福井県: "福井",
  山梨県: "山梨",
  長野県: "長野",
  岐阜県: "岐阜",
  静岡県: "静岡",
  三重県: "三重",
  滋賀県: "滋賀",
  京都府: "京都",
  兵庫県: "兵庫",
  奈良県: "奈良",
  和歌山県: "和歌山",
  鳥取県: "鳥取",
  島根県: "島根",
  岡山県: "岡山",
  広島県: "広島",
  山口県: "山口",
  徳島県: "徳島",
  香川県: "香川",
  愛媛県: "愛媛",
  高知県: "高知",
  福岡県: "福岡",
  佐賀県: "佐賀",
  長崎県: "長崎",
  熊本県: "熊本",
  大分県: "大分",
  宮崎県: "宮崎",
  鹿児島県: "鹿児島",
  沖縄県: "沖縄",
};