// ##
//lang code =zh_tw, form locale = zh_tw, form language = 繁體中文 (Chinese Traditional)
var translateState = {
  AA: "武裝部隊美國",
  Aargau: "阿爾高",
  AB: "阿爾伯塔",
  Aberdeenshire: "阿伯丁",
  Acre: "英畝",
  ACT: "奧斯特資本TERR",
  Adana: "阿達納",
  "ADGCID Campo": "ADGCID坎普",
  Adiyaman: "阿德亞曼",
  AE: "武裝部隊歐洲",
  Afyon: "阿菲永",
  "AGIN-BURYAT": "AGIN，布里亞特",
  Agri: "農業",
  Aguascalientes: "阿瓜斯卡連特斯",
  "AGUSAN DEL NORTE": "AGUSAN城北",
  "AGUSAN DEL SUR": "南阿古桑",
  Ain: "艾因",
  "AISEN DEL GENERAL CA": "艾森DEL，一般CA",
  Aisne: "埃納",
  AK: "阿拉斯加州",
  "Akershus Fylke": "阿克斯胡斯郡",
  AKLAN: "阿卡蘭",
  Aksaray: "阿克薩拉伊",
  AL: "阿拉巴馬州",
  Alagoas: "阿拉戈阿斯",
  Alava: "阿拉瓦",
  Alba: "阿爾巴",
  Albacete: "阿爾巴塞特",
  ALBAY: "阿爾拜",
  "Alentejo Litoral": "阿連特茹Litoral",
  Alessandra: "亞歷山德拉",
  Alexandria: "亞歷山德里亞",
  Alicante: "阿利坎特",
  Allier: "阿列",
  Almeria: "阿爾梅里亞",
  "Alpes (Hautes)": "阿爾卑斯（Hautes）",
  "Alpes (Hte-Provence)": "阿爾卑斯（HTE-普羅旺斯）",
  "Alpes-Maritimes": "阿爾卑斯濱海省",
  ALTAY: "阿勒泰",
  Amapa: "阿馬帕",
  Amasya: "阿馬西亞",
  AMAZONAS: "亞馬孫",
  AMAZONAS: "亞馬孫",
  "Amnat Charoen": "amnat卜蜂",
  AMUR: "阿穆爾",
  AN: "安達曼群島/尼科巴",
  Ancash: "安卡什",
  Ancona: "安科納",
  Anegada: "阿內加達",
  "Anenii Noi": "anenii河內",
  "Ang Thong": "Ang皮帶",
  Angus: "安格斯",
  Anhui: "安徽",
  Ankara: "安卡拉",
  Antalya: "安塔利亞",
  ANTIQUE: "古董",
  Antofagasta: "安託法加斯塔",
  Antrim: "安特里姆",
  Antwerp: "安特衛普",
  Anzoategui: "安索阿特吉",
  Aosta: "奧斯塔",
  AP: "安得拉邦",
  AP: "武裝部隊太平洋",
  "Appenzell Ausserrh.": "阿彭策爾Ausserrh。",
  "Appenzell Innerrh": "阿彭策爾Innerrh",
  Apure: "阿普雷",
  Apurimac: "阿普里馬克",
  AR: "阿肯色州",
  AR: "阿魯納恰爾邦",
  Arad: "阿拉德",
  Aragua: "阿拉瓜州",
  Arauca: "阿勞卡",
  Araucania: "阿勞卡尼亞",
  Ardahan: "阿爾達罕",
  Ardeche: "阿爾代什",
  Ardennes: "阿登",
  Ards: "阿茲",
  Arequipa: "阿雷基帕",
  Arezzo: "阿雷佐",
  Arges: "阿爾杰什",
  Argyll: "阿蓋爾",
  "Århus amt": "奧胡斯AMT",
  Ariege: "阿列日省",
  ARKHANGELSK: "阿爾漢格爾斯克",
  Armagh: "阿馬",
  Artvin: "阿爾特溫",
  AS: "美屬薩摩亞",
  AS: "阿薩姆邦",
  "Ascoli Piceno": "阿斯科利皮切諾",
  Asti: "阿斯蒂",
  ASTRAKHAN: "阿斯特拉罕",
  Asturias: "阿斯圖里亞斯",
  Aswan: "阿斯旺",
  Atacama: "阿塔卡馬",
  ATHENS: "雅典",
  Atlantico: "大西洋",
  Aube: "奧布",
  Auckland: "奧克蘭",
  Aude: "奧德",
  AURORA: "震旦",
  "Aust-Agder Fylke": "AUST-Agder的郡",
  Ave: "大道",
  AVEIRO: "阿威羅",
  Avellino: "阿韋利諾",
  Aveyron: "阿韋龍",
  Avila: "阿維拉",
  Avon: "雅芳",
  Ayacucho: "阿亞庫喬",
  Aydin: "艾登",
  Ayrshire: "艾爾郡",
  AZ: "亞利桑那",
  Bacau: "巴克烏",
  "Bacs-Kiskun": "巴奇 - 基什孔",
  Badajoz: "巴達霍斯",
  "Baden-Württemberg": "巴登 - 符騰堡州",
  Bahia: "巴伊亞",
  "Baja California Nort": "南下加利福尼亞州NORT",
  "Baja California Sur": "南下加利福尼亞州",
  Baleares: "巴利阿里",
  "Bali Bali": "巴厘島",
  Balikesir: "巴勒克埃西爾",
  Ballymena: "巴利米納",
  Ballymoney: "巴利馬尼",
  Balti: "巴蒂",
  Baluchistan: "俾路支",
  Banbridge: "班布里奇",
  Bangkok: "曼谷",
  Baranya: "巴蘭尼亞州",
  Barcelona: "巴塞羅那",
  Bari: "巴里",
  Barinas: "巴里納斯",
  Bartin: "巴爾騰",
  "Bas-Rhin": "下萊茵省",
  "Basel (city)": "巴塞爾（市）",
  "Basel (regional)": "巴塞爾（地區）",
  BASHKORTOSTAN: "巴什科爾托斯坦",
  BASILAN: "巴西蘭島",
  BATAAN: "巴丹",
  BATANES: "巴丹",
  BATANGAS: "八打雁",
  "Bath&NthEstSomerset": "浴缸及NthEstSomerset",
  Batman: "蝙蝠俠",
  "Bay of Plenty": "豐盛灣",
  Bayburt: "巴伊布爾特",
  Bayern: "拜仁",
  BC: "不列顛哥倫比亞省",
  Bedfordshire: "貝德福德",
  Beijing: "北京",
  "Beira Interior Norte": "貝拉內政部北",
  BEJA: "貝雅",
  Bekescsaba: "貝凱什喬包",
  Belfast: "貝爾法斯特",
  BELGOROD: "別爾哥羅德",
  Belluno: "貝盧諾",
  Bender: "德爾",
  Benevento: "貝內文托",
  BENGAL: "孟加拉",
  "Bengkulu Bengkulu": "明古魯明古魯",
  BENGUET: "本格特",
  Bergamo: "貝加莫",
  Bergen: "卑爾根",
  Berkshire: "伯克希爾",
  Berlin: "柏林",
  Bern: "伯爾尼",
  Berwickshire: "貝里克希爾",
  Bialystok: "比亞韋斯托克",
  Bicol: "比科爾",
  Biella: "比耶拉",
  Bihor: "比霍爾",
  Bilecik: "比萊吉克",
  BILIRAN: "比利蘭",
  BINGOL: "賓格爾",
  "Bio-Bio": "比奧比奧",
  "Bistrita-Nasaud": "比斯特里察 -  Nasaud",
  Bitlis: "比特利斯",
  "Bjelovar-Bilogora": "別洛瓦爾-Bilogora",
  Blackburn: "布萊克本",
  Blackpool: "黑澤",
  "Blekinge Län": "布萊金厄蘭",
  Bogota: "波哥大",
  BOHOL: "波荷",
  Bolivar: "玻利瓦爾",
  Bologna: "博洛尼亞",
  Bolu: "波魯",
  Bolzano: "博爾扎諾",
  Borders: "邊界",
  "Bornholm amt": "博恩霍爾姆AMT",
  "Borsod-Abauj-Zemplen": "爾紹德 -  Abauj  - 曾普倫",
  Botosani: "博托沙尼",
  Bournemouth: "伯恩茅斯",
  Boyaca: "博亞卡",
  BR: "比哈爾邦",
  Brabant: "布拉邦",
  "Bracknell Forest": "布拉克內爾森林",
  BRAGA: "布拉加",
  "BRAGAN¦A": "布拉干薩 (Braganza)",
  Braila: "布勒伊拉",
  Brandenburg: "勃蘭登堡",
  Brasov: "布拉索夫",
  Bratislava: "布拉迪斯拉發",
  Bremen: "不來梅",
  Brescia: "布雷西亞",
  "Brighton & Hove": "布賴頓",
  Brindisi: "布林迪西",
  Bristol: "布里斯托爾",
  "Brod-Posavina": "布羅德 - 波薩維納",
  BRYANSK: "布良斯克",
  Buckinghamshire: "白金漢",
  Bucuresti: "布加勒斯特",
  Budapest: "布達佩斯",
  BUKIDNON: "布基農",
  BULACAN: "布拉幹",
  Burdur: "布爾杜爾",
  Burgas: "布爾加斯",
  Burgos: "布爾戈斯",
  Bursa: "囊",
  BURYATIYA: "布里亞特",
  "Buskerud Fylke": "布斯克呂郡",
  Buzau: "布澤烏",
  Bydgoszcz: "比得哥什",
  CA: "加州",
  Caceres: "卡塞雷斯",
  Cadiz: "加迪斯",
  CAGAYAN: "卡加延",
  "Cagayan Valley": "卡加延河谷",
  Cagliari: "卡利亞裡",
  Cahul: "卡胡爾",
  Cairo: "開羅",
  Caithness: "凱斯內斯",
  Cajamarca: "卡哈馬卡",
  Calarasi: "克勒拉希",
  Caldas: "卡爾達斯",
  Calvados: "卡爾瓦多斯",
  "CAMARINES NORTE": "卡馬里內斯NORTE",
  "CAMARINES SUR": "卡馬里內斯SUR",
  Cambridgeshire: "劍橋",
  CAMIGUIN: "甘米銀",
  Campeche: "坎佩切",
  Campobasso: "坎波巴索",
  Canakkale: "恰納卡萊",
  Cankiri: "昌克勒",
  Cantabria: "坎塔布里亞",
  Cantal: "康塔爾",
  Canterbury: "坎特伯雷",
  Capetown: "開普敦",
  CAPIZ: "卡皮斯",
  Caqueta: "卡克塔",
  Carabobo: "卡拉沃沃",
  Caracas: "加拉加斯",
  "Caras-Severin": "卡拉什 - 塞維林",
  Carlow: "卡洛",
  Carrickfergus: "卡里克弗",
  Casanare: "卡薩納雷",
  Caserta: "卡塞塔",
  Castellon: "卡斯特利翁",
  "CASTELO BRANCO": "布朗庫堡",
  Castlereagh: "卡斯爾雷",
  CATANDUANES: "卡坦端內斯",
  Catania: "卡塔尼亞",
  Catanzaro: "卡坦扎羅",
  Cauca: "考卡",
  CAVITE: "甲米地",
  "Ceadir-Lunga": "ceadir-倫加",
  Ceara: "塞阿拉",
  CEBU: "宿務",
  Celje: "採列",
  Central: "中央",
  "Central Luzon": "呂宋島中部",
  "Central Visayas": "中部米沙鄢",
  Cesar: "塞薩爾",
  CH: "昌迪加爾",
  Chachoengsao: "北柳",
  "Chai Nat": "灣仔納特",
  "Chakassky Republic": "chakassky共和國",
  "Changhua County": "彰化縣",
  Chanthaburi: "尖竹汶府",
  "Chanti-Mansyjsky Aut": "闡提-Mansyjsky AUT",
  Charente: "夏朗德",
  "Charente-Maritime": "濱海夏朗德",
  "CHECHENO-INGUSHETIA": "CHECHENO  - 印古什",
  CHECHNYA: "車臣",
  CHELYABINSK: "車里雅賓斯克",
  Cher: "雪兒",
  Cheshire: "柴",
  "Chiang Mai": "清邁",
  "Chiang Rai": "清萊",
  Chiapas: "恰帕斯州",
  "Chiayi City": "嘉義市",
  "Chiayi County": "嘉義縣",
  Chieti: "基耶蒂",
  CHIOU: "陳郁秀",
  Chisinau: "基希訥烏",
  Choco: "喬科",
  "Chon Buri": "春武裡",
  Chongqing: "重慶",
  CHUKOT: "楚克奇",
  "Chukotka Auton. dist": "楚科奇王文浩。區",
  Chumphon: "春蓬",
  CHUVASHIA: "楚瓦什",
  "Ciudad Real": "雷阿爾城",
  Clare: "克萊爾",
  Cleveland: "克利夫蘭",
  Cluj: "克盧日",
  Clwyd: "克盧伊德",
  "Cntrl Mindanao": "CNTRL棉蘭老島",
  CO: "科羅拉多州",
  Coahuila: "科阿韋拉",
  COIMBRA: "科英布拉",
  Cojedes: "科赫德斯",
  Coleraine: "科爾雷恩",
  Colima: "科利馬",
  Como: "科莫",
  Constanta: "康斯坦察",
  Cookstown: "庫克斯敦",
  Copenhagen: "哥本哈根",
  Coquimbo: "科金博",
  Cordoba: "科爾多瓦",
  Cork: "軟木",
  Cornwall: "康沃爾",
  Correze: "科雷茲",
  "Corse-du-Nord": "科西嘉 - 杜北",
  "Corse-du-Sud": "科西嘉 - 杜 - 南基",
  Corum: "崑崙",
  Cosenza: "科森扎",
  COTABATO: "哥打巴托",
  "Cote-d Or": "科特迪瓦-D或",
  "Cotes-d Armor": "柯特斯-ð護甲",
  "Cova da Beira": "科瓦達貝拉",
  Craigavon: "克雷加文",
  Cremona: "克雷莫納",
  Creuse: "克勒茲",
  Crotone: "克羅托",
  CT: "康涅狄格",
  CT: "恰蒂斯加尔邦",
  Cuenca: "昆卡",
  Cumbria: "坎布里亞",
  Cundinamarca: "昆迪納馬卡",
  Cuneo: "庫尼奧",
  Cuzco: "庫斯科",
  Czestochowa: "琴斯托霍瓦",
  DAGESTAN: "達吉斯坦",
  "Dalarnas Län": "達拉納蘭",
  "Dar-es-Salaam": "達ES-達累斯薩拉姆",
  Darlington: "達靈頓",
  DAVAO: "達沃",
  "DAVAO DEL NORTE": "達沃城北",
  "DAVAO DEL SUR": "達沃DEL，起動率",
  "DAVAO ORIENTAL": "達沃東方",
  DC: "哥倫比亞特區",
  DD: "達曼和第烏",
  DE: "特拉華州",
  Debrecen: "德布勒森",
  "Delta Amacuro": "阿馬庫羅三角洲",
  Denizli: "代尼茲利",
  Derbyshire: "德比郡",
  Devon: "德文",
  "DI Aceh Aceh": "迪亞齊省亞齊",
  "DI Yogyakarta Yogyak": "迪日惹Yogyak",
  "Distrito Federal": "聯邦區",
  Diyarbakir: "迪亞巴克爾",
  "DKI Jakarta Jakarta": "DKI的雅加達雅加達",
  DL: "新德里",
  DN: "達德拉和納加爾哈維有",
  Dolj: "多爾日",
  Donegal: "多尼戈爾",
  Dordogne: "多爾多涅",
  Dorset: "賽特",
  Doubs: "杜省",
  Douro: "杜羅",
  Down: "向下",
  DRAMAS: "電視劇",
  Drenthe: "德倫特",
  Drome: "德龍",
  Dubasari: "杜伯薩里",
  Dublin: "都柏林",
  "Dubrovnik-Neretva": "杜布羅夫尼克 - 內雷特瓦",
  "Dumfries a. Galloway": "鄧弗里斯1。加洛韋",
  Dumfriesshire: "鄧弗里斯郡",
  Dunaujvaros: "多瑙新城",
  Dunbartonshire: "鄧巴頓郡",
  Dungannon: "鄧甘嫩",
  Durango: "杜蘭戈",
  Durham: "達勒姆",
  "East Lothian": "東洛錫安",
  "East Riding": "東部騎馬",
  "East Sussex": "東薩塞克斯",
  "Eastern Cape": "東開普省",
  "EASTERN SAMAR": "東薩馬",
  "Eastern Visayas": "東米沙鄢",
  Edirne: "埃迪爾",
  Eger: "埃格爾",
  Elazig: "埃拉澤",
  Elblag: "埃爾布隆格",
  Enna: "恩納",
  "Entre Douro e Vouga": "恩特雷里奧斯杜羅éVouga",
  Erzincan: "埃爾津詹",
  Erzurum: "埃爾祖魯姆",
  Eskisehir: "埃斯基謝希爾",
  "Espirito Santo": "聖埃斯皮裡圖州",
  Essex: "埃塞克斯",
  Essonne: "埃松",
  "Estado de Mexico": "墨西哥州",
  Eure: "厄爾",
  "Eure-et-Loir": "厄爾 -  ET-盧瓦爾",
  EVORA: "埃武拉",
  Falcon: "鶻",
  FARO: "法如國際貿易",
  Fejer: "的Fejer",
  Fermanagh: "弗馬納",
  Ferrara: "費拉拉",
  Fife: "法伊夫",
  Finistere: "菲尼斯泰爾",
  "Finnmark Fylke": "芬馬克郡",
  Firenze: "佛羅倫薩",
  FL: "佛羅里達",
  Flevoland: "弗萊福蘭",
  Foggia: "福賈",
  Forli: "弗利",
  Fribourg: "弗里堡",
  Friesland: "弗里斯蘭",
  Frosinone: "費辛隆尼",
  Fujian: "福建",
  GA: "果阿",
  GA: "格魯吉亞",
  Galati: "加拉茨",
  Galway: "戈爾韋",
  Gansu: "甘肅",
  Gard: "加爾",
  "Garonne (Haute)": "加龍河（高級）",
  Gauteng: "電話",
  "Gävleborgs Län": "耶夫勒堡省",
  Gaziantep: "加濟安泰普",
  Gdansk: "格但斯克",
  Gelderland: "海爾德蘭",
  Geneva: "日內瓦",
  Genova: "熱那亞",
  Gerona: "赫羅納",
  Gers: "蒙古包",
  Giresun: "吉雷松",
  Gironde: "吉倫特",
  Giurgiu: "久爾久",
  GJ: "古吉拉特邦",
  Glarus: "格拉魯斯",
  Gloucestershire: "格洛斯特",
  Goias: "戈亞斯",
  Gorizia: "戈里齊亞",
  Gorj: "戈爾日",
  "Gotlands Län": "gotlands蘭",
  Grampian: "嘉林",
  Granada: "格拉納達",
  Graubuenden: "格勞賓登州",
  "Greater London": "大倫敦",
  "Greater Manchester": "大曼徹斯特",
  Groningen: "格羅寧根",
  Grosseto: "格羅塞托",
  GU: "關島",
  Guadalajara: "瓜達拉哈拉",
  Guanajuato: "瓜納華托",
  Guangdong: "廣東",
  Guangxi: "廣西",
  GUARDA: "瓜爾達",
  Guarico: "瓜裡科",
  Guaviare: "瓜維亞雷",
  Guerrero: "格雷羅",
  GUIMARAS: "吉馬拉斯",
  Guipuzcoa: "吉普斯誇",
  Guizhou: "貴州",
  GUMUSHANE: "居米甚哈內",
  Guyane: "圭亞那",
  Gwent: "格溫特",
  Gwynedd: "圭內斯",
  Gyor: "傑爾",
  "Gyor-Moson-Sopron": "傑爾的Moson-索普隆",
  Haifa: "海法",
  Hainan: "海南",
  Hainaut: "埃諾",
  "Hajdu-Bihar": "豪伊杜 - 比哈爾",
  Hakkari: "哈卡里",
  "Hallands Län": "哈蘭蘭",
  Halton: "哈爾頓",
  Hamburg: "漢堡",
  Hampshire: "新罕布什爾州",
  Hanoi: "河內",
  Hartlepool: "哈特爾普爾",
  Hatay: "哈塔伊",
  "Haut-Rhin": "上萊茵省",
  "HAUTE-CORSE": "上科西嘉",
  "Hauts-de-Seine": "hauts德塞納",
  "Hawke´s Bay": "霍克斯灣",
  Hebei: "河北",
  "Hedmark Fylke": "海德馬克郡",
  Heilongjiang: "黑龍江",
  Henan: "河南",
  Herault: "埃羅",
  "Hereford and Worcs.": "Hereford和Worcs。",
  Herefordshire: "赫里福德",
  Hertfordshire: "赫特福德郡",
  Hessen: "黑森州",
  Heves: "赫維什",
  HI: "夏威夷",
  Hidalgo: "伊達爾戈",
  Highland: "高原",
  "Highlands-Altay Rep.": "阿爾泰共和國高地",
  "Hong Kong Island": "香港島",
  "Hordaland Fylke": "霍達蘭郡",
  "Hors-France": "開胃法國",
  HP: "喜馬偕爾邦",
  HR: "哈里亞納邦",
  "Hrastnik Lasko": "hrastnik洛什科",
  "Hsinchu City": "新竹市",
  "Hsinchu County": "新竹縣",
  "Hualien County": "花蓮縣",
  Huancavelica: "萬卡維利卡",
  HUANUCO: "瓦努科",
  Hubei: "湖北",
  Huelva: "韋爾瓦",
  Huesca: "韋斯卡",
  Huila: "威拉",
  Humberside: "亨伯賽德",
  Hunan: "湖南",
  Hunedoara: "胡內多阿拉",
  IA: "愛荷華州",
  Ialomita: "雅洛米察",
  Iasi: "雅西",
  Ica: "伊卡",
  ID: "愛達荷州",
  IFUGAO: "伊富高",
  IL: "伊利諾伊州",
  "ILHA DA GRACIOSA": "伊利亞的DA格拉西奧薩",
  "ILHA DA MADEIRA": "伊利亞的DA馬德拉",
  "ILHA DAS FLORES": "伊利亞DAS的弗洛雷斯",
  "ILHA DE PORTO SANTO": "青洲德聖港",
  "ILHA DE SANTA MARIA": "青洲德桑塔瑪麗亞",
  "ILHA DE SAO JORGE": "青洲德聖喬治",
  "ILHA DE SAO MIGUEL": "青洲德聖米格爾",
  "ILHA DO CORVO": "伊利亞DO的Corvo礦",
  "ILHA DO FAIAL": "伊利亞溶解氧法亞爾",
  "ILHA DO PICO": "伊利亞溶解氧筆克",
  "ILHA TERCEIRA": "伊利亞特塞拉",
  "Ilirska Bistrica": "ilirska比斯特里察",
  "Ille-et-Vilaine": "伊勒 - 維萊訥省",
  Ilocos: "伊羅戈",
  "ILOCOS NORTE": "北伊羅戈",
  "ILOCOS SUR": "南伊羅戈",
  ILOILO: "伊洛伊洛",
  Imperia: "因佩里亞",
  IN: "印地安那",
  Indre: "安德爾",
  "Indre-et-Loire": "安德爾 - 盧瓦爾省",
  "Ingushetija Republic": "ingushetija共和國",
  "Inverness-Shire": "因弗內斯郡",
  "Irian Jaya Irian Jay": "伊里安查亞伊里安查周杰倫",
  Irkutsk: "伊爾庫茨克",
  ISABELA: "伊莎貝拉",
  Isere: "伊澤爾",
  Isernia: "伊塞爾尼亞",
  Islamabad: "伊斯蘭堡",
  "Isle Of Arran": "遠祖艾倫",
  "Isle Of Barra": "遠祖巴拉",
  "Isle Of Benbecula": "遠祖的本貝丘拉島",
  "Isle Of Bute": "遠祖弼",
  "Isle Of Canna": "遠祖的美人蕉",
  "Isle Of Coll": "遠祖的科爾",
  "Isle Of Colonsay": "遠祖的Colonsay",
  "Isle Of Cumbrae": "遠祖的Cumbrae",
  "Isle Of Eigg": "遠祖的Eigg",
  "Isle Of Gigha": "遠祖的Gigha",
  "Isle Of Harris": "遠祖哈里斯",
  "Isle Of Iona": "遠祖的艾奧娜",
  "Isle Of Islay": "遠祖的艾萊",
  "Isle Of Jura": "遠祖汝拉",
  "Isle Of Lewis": "遠祖劉易斯",
  "Isle Of Mull": "遠祖馬爾",
  "Isle Of North Uist": "島的北部Uist",
  "Isle Of Rum": "遠祖的朗姆酒",
  "Isle Of Scalpay": "遠祖的Scalpay",
  "Isle Of Skye": "斯凱島",
  "Isle Of South Uist": "島南Uist",
  "Isle Of Tiree": "遠祖的Tiree",
  "Isle of Wight": "懷特島",
  "Isles Of Scilly": "島的錫利",
  Isparta: "伊斯帕爾塔",
  Istanbul: "伊斯坦布爾",
  "Itä-Suomi": "ITA-芬蘭語",
  "IVANO-FRANKIVSKA": "伊万諾 -  FRANKIVSKA",
  IVANOV: "伊万諾夫",
  Izmir: "伊茲密爾",
  Izola: "伊佐拉",
  Jaen: "哈恩",
  Jalisco: "哈利斯科",
  "Jambi Jambi": "佔碑佔碑",
  "Jämtlands Län": "jämtlands蘭",
  "Jasz-Nagykun-Szolnok": "亞斯 - 納傑孔 - 索爾諾克",
  "Jawa Barat West Java": "西爪哇爪哇巴拉",
  "Jawa Tengah Central": "爪哇登加中",
  "Jawa Timur East Java": "東爪哇爪哇帖木兒",
  Jerusalem: "耶路撒冷",
  JH: "贾坎德邦",
  Jiangsu: "江蘇",
  Jiangxi: "江西",
  Jihocesky: "南捷克",
  Jilin: "吉林",
  JK: "查謨和克什米爾",
  Johannesburg: "約翰內斯堡",
  Johor: "柔佛",
  "Jönköpings Län": "延雪平嵐",
  "Jost Van Dyke": "約斯特範",
  JUNIN: "胡寧",
  Jura: "朱拉",
  KA: "卡納塔克邦",
  "KABARDINO-BALKARIA": "卡巴爾達 - 巴爾卡爾",
  "KAHRAMAN MARAS": "KAHRAMAN馬拉什",
  Kalasin: "加拉信",
  "Kalimantan Barat Wes": "加里曼丹巴拉韋斯",
  "Kalimantan Selatan S": "加里曼丹Selatan小號",
  "Kalimantan Tengah Ce": "加里曼丹登加CE",
  "Kalimantan Timur Eas": "加里曼丹帖木兒大通",
  KALINGA: "卡林加",
  KALININGRAD: "加里寧格勒",
  Kalisz: "卡利甚",
  "Kalmar Län": "卡爾馬蘭",
  KALMYKIYA: "卡爾梅克",
  KALUGA: "卡盧加",
  KALUZHSKAYA: "卡盧加州",
  Kamnik: "卡姆尼克",
  "Kamphaeng Phet": "甘烹碧",
  Kanchanaburi: "北碧府",
  "Kaohsiung City": "高雄市",
  "KARACHAY-CHERKESSIA": "卡拉恰伊 - 切爾克斯",
  Karaman: "卡拉曼",
  KARELIA: "卡累利阿",
  Karlovac: "卡爾洛瓦茨",
  Kars: "卡爾斯",
  Kashmir: "克什米爾",
  Kastamonu: "卡斯塔莫努",
  Katowice: "卡托維茲",
  Kavan: "揚·卡萬",
  Kayseri: "開塞利",
  Kecskemet: "凱奇凱梅特",
  Kedah: "吉打州",
  "Keelung City": "基隆市",
  Kelantan: "吉蘭丹州",
  Kent: "肯特",
  Kerry: "黑色的小乳牛",
  Khabarovsk: "哈巴羅夫斯克",
  "Khon Kaen": "孔敬",
  Khyber: "開伯爾",
  Kildare: "基爾代爾",
  KILIS: "基利斯",
  Kilkenny: "基爾肯尼",
  Kilkis: "基爾基斯",
  "Kingston-Upon-Hull": "金斯敦 - 赫爾",
  "Kinmen County": "金門縣",
  Kirikkale: "克里卡爾",
  Kirklareli: "克爾克拉雷利",
  KIROV: "基洛夫",
  KL: "喀拉拉邦",
  "København amt": "哥本哈根AMT",
  Kocaeli: "科賈埃利",
  "Komarom-Esztergom": "科馬羅姆 - 埃斯泰爾戈姆",
  Konya: "科尼亞",
  Koper: "科佩爾",
  "Koprivnica-Krizevci": "科普里夫尼察，Krizevci",
  Kowloon: "九龍",
  Krabi: "喀比",
  Krakow: "克拉科夫",
  Kranj: "克拉尼",
  KRASNODAR: "克拉斯諾達爾",
  KRASNOYARSK: "克拉斯諾亞爾斯克",
  "Kronobergs Län": "kronobergs蘭",
  "Krung Thep": "泰京銀行Thep",
  KS: "堪薩斯",
  "Kuala-Lumpur": "吉隆坡 - 吉隆坡",
  KURGAN: "庫爾幹",
  KURSK: "庫爾斯克",
  KUTAHYA: "屈塔希亞",
  "Kwazulu/Natal": "誇祖魯/納塔爾",
  KY: "肯塔基州",
  "L Aquila": "大號拉奎拉",
  LA: "路易斯安那州",
  "La Coruña": "拉科魯尼亞",
  "La Guajira": "拉瓜希拉",
  "La Libertad": "拉利伯塔德",
  "La Rioja": "拉里奧哈",
  "La Spezia": "拉斯佩齊亞",
  "LA UNION": "拉烏尼翁",
  Labuan: "納閩",
  LAD: "拉達克",
  LAGUNA: "麗",
  Lambayeque: "蘭巴耶克",
  Lampang: "南邦",
  Lamphun: "南奔",
  "Lampung Lampung": "楠榜省楠榜",
  "LANAO DEL NORTE": "北拉瑙",
  "LANAO DEL SUR": "南拉瑙",
  Lanarkshire: "拉納克",
  Lancashire: "蘭開夏郡",
  Landes: "蘭德斯",
  "Länsi-Suomi": "藍絲，芬蘭語",
  Laois: "嶗",
  Lara: "拉拉",
  Larne: "拉恩",
  "Las Palmas": "拉斯帕爾馬斯",
  Latina: "拉提納",
  LD: "拉克沙群島",
  Lecce: "萊切",
  Lecco: "萊科",
  Legnica: "萊格尼察",
  "Leicester City": "萊切斯特城",
  Leicestershire: "萊斯特",
  LEIRIA: "萊里亞",
  Leitrim: "利特里姆",
  Lendava: "倫達瓦",
  LENINGRADSKAYA: "列寧格勒",
  Leon: "萊昂",
  Lerida: "萊里達",
  LEYTE: "萊特",
  "Lianjiang County": "連江縣",
  Liaoning: "遼寧",
  Libertador: "解放者",
  Liege: "列日",
  "Lika-Senj": "利卡-Senj",
  Lillehammer: "利勒哈默爾",
  LIMA: "利馬",
  Limavady: "利馬瓦迪",
  Limburg: "林堡",
  Limerick: "五行打油詩",
  Lincolnshire: "林肯郡",
  LIPETSK: "利佩茨克",
  Lisboa: "葡京",
  Lisburn: "利斯",
  Livorno: "利沃諾",
  "Ljubljana-Bezigrad": "盧布爾雅那 -  Bezigrad",
  "Ljubljana-Center": "盧布爾雅那的中心",
  "Ljubljana-Moste-Polj": "的盧布爾雅那-Moste-Polj",
  "Ljubljana-Siska": "盧布爾雅那 -  Siska",
  "Ljubljana-Vic-Rudnik": "盧布爾雅那-VIC-魯德尼克",
  Lodi: "洛迪",
  LODZKIE: "羅茲",
  Loei: "黎",
  "Loir-et-Cher": "盧瓦爾 - 謝爾",
  Loire: "盧瓦爾河",
  "Loire (Haute)": "盧瓦爾（高級）",
  "Loire-Atlantique": "盧瓦爾河 - 大西洋",
  Loiret: "盧瓦雷",
  London: "倫敦",
  Londonderry: "倫敦德里",
  Longford: "朗福德",
  "Lop Buri": "華富裡",
  Loreto: "洛雷托",
  "Los Lagos": "洛斯拉戈斯",
  Lot: "很多",
  "Lot-et-Garonne": "很多-ET-龍河",
  Lothian: "洛錫安",
  Louth: "勞斯",
  Lozere: "洛澤爾",
  LUBELSKIE: "盧布林",
  Lublin: "盧布林",
  Lucca: "盧卡",
  LUCENA: "盧塞納",
  Lucerne: "盧塞恩",
  Lugo: "盧戈",
  Luton: "盧頓",
  Luxembourg: "盧森堡",
  MA: "美國馬薩諸塞州",
  Macerata: "馬切拉塔",
  "MADRE DE DIOS": "馬德雷德迪奧斯",
  Madrid: "馬德里",
  "Mae Hong Son": "湄宏順",
  MAGADAN: "馬加丹",
  Magdalena: "馬格達萊納",
  Magherafelt: "馬拉費爾特",
  MAGUINDANAO: "馬京達瑙省",
  "Maha Sarakham": "瑪哈Sarakham",
  "Maine-et-Loire": "緬因州盧瓦爾省",
  Malaga: "馬拉加",
  Malatya: "馬拉蒂亞",
  "Maluku Maluku": "馬魯古省馬魯古",
  "Manawatu-Wanganui": "瑪納瓦圖旺格努伊",
  Manche: "芒",
  MANILA: "新華社馬尼拉",
  Manisa: "馬尼薩",
  Mantova: "曼托瓦",
  Maramures: "馬拉穆列什",
  Maranhao: "馬拉尼昂州",
  Mardin: "馬爾丁",
  "MARI EL": "MARI的EL",
  Maribor: "馬里博爾",
  "Marijskaya Republic": "marijskaya共和國",
  MARINDUQUE: "馬林杜克",
  Marne: "馬恩",
  "Marne (Haute)": "馬恩（高級）",
  "Masa Carrara": "馬薩卡拉拉",
  Matera: "馬泰拉",
  "Mato Grosso": "馬托格羅索",
  "Mato Grosso do Sul": "南馬托格羅索",
  Maule: "馬烏萊",
  Mayenne: "馬耶訥",
  Mayo: "梅奧",
  MB: "馬尼托巴",
  MD: "馬里蘭",
  ME: "緬因州",
  Meath: "米斯",
  "Mecklenburg-Vorpommern": "梅克倫堡 - 前波莫瑞",
  "Médio Tejo": "Medio的特茹",
  Melaka: "馬六甲",
  Merida: "梅里達",
  Merseyside: "默西塞德郡",
  Messina: "墨西拿",
  Meta: "元",
  "Metro Manila": "馬尼拉",
  "Meurthe-et-Moselle": "默爾特 - 摩澤爾省",
  Meuse: "默茲",
  MH: "馬哈拉施特拉邦",
  MI: "密歇根",
  "Miaoli County": "苗栗縣",
  Michoacan: "米卻肯",
  "Mid Glamorgan": "中旬Glamorgan的",
  Middlesbrough: "米德爾斯堡",
  Middlesex: "米德爾塞克斯",
  Midlothian: "洛錫安",
  MILANO: "米蘭",
  "Milton Keynes": "米爾頓凱恩斯",
  "Minas Gerais": "米納斯吉拉斯州",
  "MINDORO OCCIDENTAL": "民都洛西洋",
  "MINDORO ORIENTAL": "民都洛東方",
  Miranda: "米蘭達",
  "MISAMIS OCCIDENTAL": "西米薩米斯",
  "MISAMIS ORIENTAL": "東米薩米斯",
  Miskolc: "米甚科爾茨",
  ML: "梅加拉亞邦",
  MN: "明尼蘇達州",
  MN: "曼尼普爾邦",
  MO: "密蘇里州",
  Modena: "摩德納",
  Monagas: "莫納加斯",
  Monaghan: "莫納漢",
  Montana: "蒙大拿",
  Montevideo: "蒙得維的亞",
  Moquegua: "莫克瓜",
  Morbihan: "莫爾比昂",
  MORDOVIYA: "莫爾多維亞",
  "Møre og Romsdal F.": "更多OG魯姆斯達爾樓",
  Morelos: "莫雷洛斯",
  Moscow: "莫斯科",
  Moselle: "摩澤爾",
  MOSKVA: "莫斯科",
  MOUNTAIN: "山",
  Moyle: "莫伊爾",
  MP: "中央邦",
  Mpumalanga: "姆普馬蘭加",
  MS: "密西西比河",
  Mugla: "穆拉",
  Mukdahan: "穆達漢",
  Murcia: "穆爾西亞",
  Mures: "穆列什",
  Murmansk: "摩爾曼斯克",
  "Murska Sobota": "murska博塔",
  MUS: "毛里求斯",
  MZ: "米佐拉姆",
  Nagykanizsa: "瑙吉考尼饒",
  Nairn: "奈倫",
  "Nakhon Nayok": "那空那育",
  "Nakhon Pathom": "佛統",
  "Nakhon Phanom": "那空拍儂",
  "Nakhon Ratchasima": "呵叻",
  "Nakhon Sawan": "那空沙旺",
  "Nakhon Si Thammarat": "洛坤府",
  Namur: "那慕爾",
  Nan: "南",
  "Nantou County": "南投縣",
  Naples: "那不勒斯",
  Narathiwat: "那拉提瓦",
  Narino: "納里尼奧",
  "NATIONAL CAPITAL REG": "國家資本金章第",
  Navarra: "納瓦拉",
  Nayarit: "納亞里特",
  NB: "新不倫瑞克省",
  NC: "北卡羅萊納州",
  ND: "北達科他州",
  NE: "內布拉斯加州",
  Neamt: "亞姆茨",
  "Negeri Sembilan": "森美蘭",
  "NEGROS OCCIDENTAL": "西內格羅斯",
  "NEGROS ORIENTAL": "內格羅斯東方",
  "Nei Mongol": "內蒙古",
  NENETS: "涅涅茨",
  Neuchatel: "納沙泰爾",
  NEVSEHIR: "內夫謝希爾",
  "New TaipeiCity": "新北市",
  "New Territories": "新界",
  Newbury: "紐伯里",
  "Newry and Mourne": "紐裡和莫恩",
  Newtownabbey: "紐敦阿比",
  NH: "新罕布什爾州",
  Nidwalden: "瓦爾登",
  Niedersachsen: "下薩克森州",
  Nievre: "涅夫勒",
  Nigde: "尼代",
  Ningxia: "寧夏",
  NIZHEGORODSKAYA: "下諾夫哥羅德",
  NJ: "新澤西",
  NL: "紐芬蘭",
  NL: "那加蘭邦",
  NM: "新墨西哥",
  Nograd: "諾格拉德",
  "Nong Bua Lamphu": "農布阿欣欣向榮",
  "Nong Khai": "農凱",
  Nonthaburi: "暖武裡府",
  "Noord-Brabant": "北布拉邦",
  "Noord-Holland": "北荷蘭省",
  Nord: "諾德",
  "Nord-Trøndelag Fylk": "北特倫德拉格Fylk的",
  "Nordjylland amt": "北日德蘭AMT",
  "Nordland Fylke": "諾爾蘭郡",
  "Nordrhein-Westfalen": "北萊茵 - 威斯特法倫州",
  Norfolk: "諾福克",
  "Norrbottens Län": "norrbottens蘭",
  "Norte de Santander": "北桑坦德",
  "NORTH COTABATO": "北哥打巴托",
  "North Down": "北唐",
  "North Humberside": "北亨伯賽德",
  "North Lincolnshire": "北林肯郡",
  "North Somerset": "北薩默塞特",
  "North Yorkshire": "北約克郡",
  "North-Osetiya Republ": "北Osetiya Republ的",
  "North-West": "西北",
  Northamptonshire: "北安普敦郡",
  Northern: "北方",
  "Northern Cape": "北開普省",
  "Northern Mindanao": "北棉蘭老島",
  "Northern Province": "北方省",
  "NORTHERN SAMAR": "北方SAMAR",
  Northland: "北國",
  Northumberland: "諾森伯蘭",
  "Nottingham City": "諾丁漢市",
  Nottinghamshire: "諾丁漢",
  "Nova Gorica": "新戈里察",
  Novara: "諾瓦拉",
  NOVGOROD: "諾夫哥羅德",
  "Novo Mesto": "新梅斯托",
  NOVOSIBIRSK: "新西伯利亞",
  "Nowy Sacz": "的Nowy松奇",
  NS: "新斯科舍省",
  NSW: "新南威爾士州",
  NT: "北領地",
  NT: "西北地區",
  "NthEast Lincolnshire": "NthEast林肯郡",
  NU: "努納武特地區",
  "NUEVA ECIJA": "新怡詩夏",
  "Nueva Esparta": "新埃斯帕塔",
  "NUEVA VIZCAYA": "新比斯開",
  "Nuevo Leon": "新萊昂州",
  Nuoro: "努奧羅",
  "Nusa Tenggara Barat": "努沙登加拉巴拉",
  "Nusa Tenggara Timur": "東努沙登加拉",
  NV: "內華達州",
  NY: "紐約",
  Nyiregyhaza: "尼賴吉哈佐",
  Oaxaca: "瓦哈卡",
  Obwalden: "瓦爾登",
  Oeste: "的Oeste",
  Offaly: "奧法利",
  OH: "俄亥俄州",
  Oise: "瓦茲",
  OK: "俄克拉何馬",
  OLONGAPO: "加波",
  Olsztyn: "奧爾什丁",
  Omagh: "奧馬",
  ON: "安大略省",
  OPOLSKIE: "奧波萊",
  "Oppland Fylke": "奧普蘭郡",
  OR: "俄勒岡州",
  Ordu: "奧爾杜",
  "Örebro Län": "厄勒布魯",
  ORENBURG: "奧倫堡",
  Orense: "奧倫塞",
  Oristano: "奧里斯塔諾",
  Orkney: "奧克尼",
  ORLOVSKAYA: "奧廖爾",
  Orne: "奧恩",
  "Osijek-Baranja": "奧西耶克 - 巴拉尼亞",
  Oslo: "奧斯陸",
  "Östergötlands Län": "東約特蘭",
  "Østfold Fylke": "東福爾郡",
  Otago: "奧塔哥",
  Oulu: "奧盧",
  Overijssel: "上艾瑟爾",
  Oxfordshire: "牛津",
  PA: "賓夕法尼亞州",
  Padova: "帕多瓦",
  Pahang: "彭亨",
  PALAWAN: "巴拉望",
  Palencia: "帕倫西亞",
  Palermo: "巴勒莫",
  PAMPANGA: "邦板牙",
  PANGASINAN: "邦阿西楠",
  Para: "第",
  Paraiba: "帕拉伊巴",
  Parana: "巴拉那",
  Paris: "巴黎",
  Parma: "帕爾馬",
  "Pas-de-Calais": "PAS-DE-加萊",
  Pasco: "帕斯科",
  "Pathum Thani": "巴吞他尼",
  Pattani: "北大",
  Pavia: "帕維亞",
  PB: "旁遮普",
  PE: "愛德華王子島",
  Pecs: "佩奇",
  "Penghu County": "澎湖縣",
  PENZA: "奔薩",
  Perak: "霹靂",
  Perlis: "玻璃市",
  PERM: "燙髮",
  Pernambuco: "伯南布哥",
  Perthshire: "佩思",
  Perugia: "佩魯賈",
  Pesaro: "佩薩羅",
  Pescara: "佩斯卡拉",
  Pest: "害蟲",
  Peterborough: "彼得伯勒",
  Phangnga: "攀牙",
  Phatthalung: "好在Phatthalung",
  Phayao: "帕堯",
  Phetchabun: "碧差汶",
  Phetchaburi: "碧武裡",
  Phichit: "披集府",
  Phitsanulok: "彭世洛",
  "PHRA NAKHON SI AYUTT": "帕那空司AYUTT",
  Phrae: "帕府",
  Phuket: "普吉島",
  Piacenza: "皮亞琴察",
  Piaui: "皮奧伊",
  Pila: "皮拉",
  "Pingtung County": "屏東縣",
  "Pinhal Interior N.": "皮尼亞爾內政部N.",
  "Pinhal Interior Sul": "皮尼亞爾內政部扎",
  Piran: "皮蘭",
  Pisa: "比薩",
  Pistoia: "皮斯托亞",
  Piura: "皮烏拉",
  Plock: "普沃茨克",
  Plymouth: "普利茅斯",
  Pontevedra: "龐特維德拉",
  Poole: "普爾",
  Pordenone: "波代諾",
  PORTALEGRE: "波塔萊格雷",
  PORTO: "波爾圖",
  Portsmouth: "朴茨茅斯",
  Portuguesa: "波圖格薩",
  Postojna: "波斯托伊納",
  Potenza: "波坦察",
  Powys: "波伊斯",
  Poznan: "波茲南",
  PR: "波多黎各",
  "Prachin Buri": "巴真武裡",
  "PRACHUAP KHIRI KHAN": "巴蜀KHIRI汗",
  Praha: "布拉格",
  Prahova: "普拉霍瓦",
  Prato: "普拉托",
  "Primorje-Gorski Kot.": "Primorje的Gorski葛",
  PRIMORSKIY: "濱海",
  Przemysl: "普熱梅希爾",
  PSKOV: "普斯科夫",
  Puebla: "普埃布拉",
  "Pulau Pinang": "檳城",
  Puno: "普諾",
  Putumayo: "普圖馬約",
  "Puy-de-Dôme": "多姆德圓頂",
  PW: "帕勞",
  PY: "Pondicherry的",
  "Pyrenees (Hautes)": "比利牛斯省（Hautes）",
  "Pyrenees-Atlantiques": "比利牛斯 - 大西洋",
  "Pyrenees-Orientales": "比利牛斯 -  Orientales",
  QC: "魁北克",
  Qinghai: "青海",
  QLD: "昆士蘭",
  "Quarry Bay": "鰂魚湧",
  Queretaro: "克雷塔羅",
  QUEZON: "奎松",
  Quindio: "金迪奧",
  QUIRINO: "基里諾",
  Quito: "基多",
  Radom: "拉多姆",
  Ragusa: "拉古薩",
  RANONG: "拉廊",
  Ravenna: "拉韋納",
  "Ravne Na Koroskem": "ravne娜Koroskem",
  RAYONG: "羅勇",
  Reading: "閱讀",
  "Redcar and Cleveland": "雷德卡和克利夫蘭",
  "Reggio Calabria": "雷焦卡拉布里亞",
  "Reggio Emilia": "瑞吉歐",
  "Region Metropolitana": "地區大都會",
  Renfrewshire: "倫弗魯",
  "Rep di San Marino": "聲望迪聖馬力諾",
  Réunion: "留尼汪",
  "Rheinland-Pfalz": "萊茵蘭 - 普法爾茨州",
  Rhone: "羅納",
  RI: "羅德島",
  "Riau Riau": "廖內里奧",
  Rimini: "里米尼",
  "Ringkøbing amt": "靈克賓AMT",
  "Rio De Janeiro": "里約熱內盧",
  "Rio Grande de Norte": "德北里奧格蘭德",
  "Rio Grande do Sul": "南里奧格蘭德州",
  Risaralda: "里薩拉爾達",
  RIZAL: "黎剎",
  Rize: "裡澤",
  RJ: "拉賈斯坦邦",
  "Rochester Up. Medway": "羅切斯特最多。梅德韋",
  "Rogaland Fylke": "羅加蘭郡",
  "ROI ET": "投資回報率的ET",
  ROMBLON: "朗布隆",
  Rome: "羅馬",
  Rondonia: "朗多尼亞",
  Roraima: "羅賴馬",
  "Roskilde amt": "羅斯基勒AMT",
  "Ross-Shire": "羅斯郡",
  ROSTOV: "羅斯托夫",
  Rovigo: "羅維戈",
  Ruse: "騙術",
  Rutland: "拉特蘭",
  RYAZAN: "梁贊",
  Rzeszow: "熱舒夫",
  SA: "南澳大利亞",
  "Sa Kaeo": "沙繳",
  Saarland: "薩爾",
  Sabah: "沙巴",
  Sachsen: "薩克森",
  "Sachsen-Anhalt": "薩克森 - 安哈爾特州",
  Sakarya: "薩卡里亞",
  SAKHA: "薩哈",
  SAKHALIN: "薩哈林",
  "SAKON NAKHON": "左近呵",
  Salamanca: "薩拉曼卡",
  Salerno: "薩萊諾",
  SAMARA: "薩馬拉",
  Samsun: "薩姆松",
  "SAMUT PRAKAN": "北欖",
  "SAMUT SAKHON": "沙木沙空",
  "SAMUT SONGKHRAM": "沙木堪",
  "San Luis Potosi": "聖路易斯波托西",
  "San Martín": "聖馬丁",
  SANLIURFA: "桑尼烏法",
  "Santa Catarina": "聖卡塔琳娜",
  Santander: "桑坦德",
  SANTAREM: "聖塔倫",
  Santiago: "聖地亞哥",
  "Sao Paulo": "聖保羅",
  "Saone (Haute)": "索恩（高級）",
  "Saone-et-Loire": "索恩 - 盧瓦爾省",
  "SARA BURI": "薩拉武裡",
  SARANGANI: "薩蘭加尼",
  SARATOV: "薩拉托夫",
  Sarawak: "沙撈越",
  Sarthe: "薩爾特",
  Sassari: "薩薩里",
  "Satu Mare": "薩圖馬雷",
  SATUN: "沙敦",
  Savoie: "薩瓦",
  "Savoie (Haute)": "薩瓦（高級）",
  Savona: "薩沃納",
  SC: "南卡羅來納州",
  Schaffhausen: "沙夫豪森",
  "Schleswig-Holstein": "石勒蘇益格 - 荷爾斯泰因",
  Scotland: "蘇格蘭",
  SD: "南達科他州",
  Segovia: "塞哥維亞",
  "Seine-et-Marne": "塞納 - 馬恩省",
  "Seine-Maritime": "濱海塞納",
  "Seine-Saint-Denis": "塞納 - 聖德尼",
  Selangor: "雪蘭莪州",
  Select: "选择",
  "Sentjur Pri Celju": "sentjur小學Celju",
  Sergipe: "塞爾希培",
  SETUBAL: "塞圖巴爾",
  "Severo-Kazakhstansk": "北-Kazakhstansk",
  "SEVERO-OSETINSKAYA": "北-OSETINSKAYA",
  Sevilla: "塞維利亞",
  "Sevres (Deux)": "塞弗爾（德塞夫勒）",
  Shaanxi: "陝西",
  Shandong: "山東",
  Shanghai: "上海",
  Shanxi: "山西",
  Shetland: "設得蘭群島",
  Shropshire: "什羅普",
  Sibenik: "希貝尼克",
  Sibiu: "錫比烏",
  Sichuan: "四川",
  Siena: "錫耶納",
  Siirt: "錫爾特",
  Sinaloa: "錫那羅亞",
  Sind: "信德",
  "SING BURI": "信武裡",
  Singapore: "新加坡",
  Sinop: "錫諾普",
  SIQUIJOR: "錫基霍爾",
  Siracusa: "錫拉庫薩",
  SIRNAK: "舍爾納克",
  "Sisak-Moslavina": "西薩克-Moslavina",
  Sivas: "錫瓦斯",
  SK: "薩斯喀徹溫省",
  SK: "錫金",
  "Skåne Län": "斯科納",
  "Skofja Loka": "skofja洛卡",
  SLASKIE: "西里西亞",
  Slavonski: "斯拉沃尼亞",
  Sligo: "斯萊戈",
  Slough: "泥沼",
  "Slovenska Bistrica": "slovenska比斯特里察",
  Slupsk: "斯武普斯克",
  "Smarje Pri Jelsah": "smarje小學Jelsah",
  SMOLENSK: "斯摩棱斯克",
  "Södermanlands Län": "södermanlands蘭",
  "Sogn og Fjordane F.": "松恩OG Fjordane樓",
  Solothurn: "索洛圖恩",
  Somerset: "薩默塞特",
  Somme: "索姆",
  Somogy: "紹莫吉",
  "Sønderjylland amt": "南日德蘭AMT",
  Sondrio: "松德里奧",
  SONGKHLA: "宋卡",
  Sonora: "索諾拉",
  Sopron: "索普隆",
  "Sør-Trøndelag Fylk": "SOR-拉格Fylk",
  Soria: "索里亞",
  SORSOGON: "索索貢",
  "SOUTH COTABATO": "南哥打巴托",
  "South Glamorgan": "南格拉摩根",
  "South Humberside": "南亨伯賽德",
  "South Luzon": "南呂宋島",
  "South Mindanao": "南部棉蘭老島",
  "South Yorkshire": "南約克郡",
  Southampton: "南安普敦",
  Southend: "紹森德",
  Southern: "南部的",
  "SOUTHERN LEYTE": "南萊特",
  Southland: "南國",
  "Split-Dalmatia": "分裂的達爾馬提亞",
  "St. Gallen": "聖加侖",
  "St. Petersburg": "聖彼得堡",
  "Sta. Cruz Tenerife": "站聖克魯斯特內里費",
  "Stadt Zagreb": "STADT薩格勒布",
  Staffordshire: "斯塔福德",
  STAVROPOL: "斯塔夫羅波爾",
  "Stefan-Voda": "斯蒂芬 - 沃達",
  "Sth. Gloucestershire": "某物。格洛斯特",
  Stirlingshire: "斯特靈",
  "Stockholms Län": "斯德哥爾摩蘭",
  "Stockton-on-Tees": "斯托克頓，T卹",
  "Storstrøm amt": "斯托AMT",
  Strabane: "斯特拉班",
  Strathclyde: "斯特拉斯克萊德",
  Suceava: "蘇恰瓦",
  Sucre: "蘇克雷",
  Suffolk: "薩福克",
  SUKHOTHAI: "素可泰",
  "Sulawesi Selatan Sou": "南蘇拉威西叟",
  "Sulawesi Tengah Cent": "蘇拉威西登加美分",
  "Sulawesi Tenggara So": "蘇拉威西Tenggara所以",
  "Sulawesi Utara North": "北蘇拉威西省Utara",
  "SULTAN KUDARAT": "蘇丹庫達拉",
  SULU: "蘇魯",
  "Sumatera Barat West": "西蘇門答臘巴拉",
  "Sumatera Selatan Sou": "蘇門答臘Selatan叟",
  "Sumatera Utara North": "北蘇門答臘Utara",
  "SUPHAN BURI": "素攀武裡",
  "SURAT THANI": "素叻他尼",
  SURIGAO: "蘇里高",
  "SURIGAO DEL NORTE": "蘇里高城北",
  "SURIGAO DEL SUR": "蘇里高DEL，起動率",
  SURIN: "蘇林",
  Surrey: "薩里",
  Sussex: "蘇塞克斯",
  Sutherland: "薩瑟蘭",
  Suwalki: "蘇瓦烏基",
  SVERDLOV: "斯維爾德洛夫",
  SWIETOKRZYSKIE: "聖十字",
  Switzerland: "瑞士",
  "Szabolcs-Szat.-Bereg": "的索博爾奇-Szat.-Bereg",
  Szczecin: "甚切青",
  Szeged: "塞格德",
  Szekesfehervar: "塞克希費黑瓦爾",
  Szolnok: "索爾諾克",
  Szombathely: "松博特海伊",
  Tabasco: "塔巴斯科",
  Tachira: "塔奇拉",
  Tacna: "塔克納",
  "Taichung City": "台中市",
  "Tainan City": "台南市",
  "Taipei City": "台北市",
  "Taitung County": "台東縣",
  TAK: "德",
  Tamaulipas: "塔毛利帕斯",
  TAMBOV: "坦波夫",
  "Taoyuan City": "桃園市",
  Taranaki: "塔拉納基",
  Taranto: "塔蘭托",
  Tarapaca: "塔拉帕卡",
  TARLAC: "塔拉克",
  Tarn: "塔恩",
  "Tarn-et-Garonne": "塔恩-等加龍省",
  Tarnow: "塔爾努夫",
  Tarragona: "塔拉戈納",
  TAS: "塔斯馬尼亞",
  Tatabanya: "陶陶巴尼奧",
  TATARSTAN: "韃靼斯坦",
  "TAWI-TAWI": "塔威 - 塔威",
  Tayside: "泰賽德",
  Tekirdag: "泰基爾達",
  "Tel Aviv": "特拉維夫",
  "Telemark Fylke": "泰勒馬克郡",
  Teramo: "泰拉莫",
  Terengganu: "丁加奴",
  Terni: "特爾尼",
  "Territ.-de-Belfort": "territ.-DE-貝爾福",
  Teruel: "特魯埃爾",
  TG: "特倫甘納邦",
  THA: "臨屋區",
  "The Jewish Auton.are": "猶太Auton.are",
  "The Nizhniy Novgorod": "下諾夫哥羅德",
  "The Taymir Auton.dis": "Taymir Auton.dis",
  Thurgau: "高州",
  Thüringen: "圖林根",
  Thurrock: "瑟羅克",
  Tianjin: "天津",
  Ticino: "提契諾州",
  Timis: "蒂米甚",
  "Timor Timur East Tim": "東帝汶帖木兒東添",
  Tipperary: "蒂珀雷",
  Tiraspol: "蒂拉斯波爾",
  TN: "泰米爾納德邦",
  TN: "田納西州",
  Tocantins: "托坎廷斯",
  Tokat: "託卡特",
  Toledo: "托萊多",
  TOLIMA: "托利馬",
  Tolna: "托爾瑙",
  TOMSK: "托木斯克",
  Torbay: "托貝",
  Tortola: "托爾托拉",
  Torun: "托倫",
  TR: "特里普拉邦",
  Trabzon: "特拉布宗",
  Transvaal: "德蘭士瓦",
  Trapani: "特拉帕尼",
  TRAT: "達勒",
  Trbovlje: "的Trbovlje",
  Trento: "特倫托",
  Treviso: "特雷維索",
  Trieste: "的里雅斯特",
  "Troms Fylke": "特羅姆斯郡",
  Trujillo: "特魯希略",
  TULA: "圖拉",
  Tulcea: "圖爾恰",
  Tumbes: "通貝斯",
  Tunceli: "通傑利",
  Turin: "都靈",
  "Tuva Republic": "圖瓦共和國",
  TVER: "特維爾",
  TX: "得克薩斯州",
  "Tyne and Wear": "泰恩河和磨損",
  Tyrone: "泰隆",
  TYUMEN: "秋明",
  TYVA: "圖瓦",
  "UBON RATCHATHANI": "烏汶",
  Ucayali: "烏卡亞利",
  Udine: "烏迪內",
  "UDON THANI": "烏隆",
  ULYANOVSK: "烏里揚諾夫斯克州",
  UP: "北方邦",
  "Uppsala Län": "烏普薩拉",
  Uri: "烏里",
  USAK: "烏沙克",
  "Ust-Ordinsky Buryat": "烏斯Ordinsky布里亞特",
  UT: "北阿坎德邦",
  UT: "猶他州",
  "UTHAI THANI": "烏泰他尼",
  Utrecht: "烏得勒支",
  UTTARADIT: "程逸",
  VA: "弗吉尼亞州",
  "Val-d Oise": "VAL-ð瓦茲",
  "Val-de-Marne": "瓦爾 - 德 - 馬恩省",
  Valais: "瓦萊州",
  Valencia: "瓦倫西亞",
  Valladolid: "巴利亞多利德",
  Valparaiso: "瓦爾帕萊索",
  Van: "貨車",
  Var: "瓦爾",
  Varese: "瓦雷澤",
  Vargas: "巴爾加斯",
  "Värmlands Län": "värmlands蘭",
  Varna: "瓦爾納",
  Vas: "輸精管",
  Vaslui: "瓦斯盧伊",
  "Västerbottens Län": "västerbottens蘭",
  "Västernorrlands Län": "西諾爾蘭",
  "Västmanlands Län": "västmanlands蘭",
  "Västra Götalands Län": "西哥Götalands局域網",
  Vaucluse: "沃克呂茲",
  Vaud: "沃",
  Vaupes: "沃佩斯",
  "Vejle amt": "瓦埃勒AMT",
  Vendee: "買受人",
  Venice: "威尼斯",
  Veracruz: "韋拉克魯斯",
  Verbania: "韋爾巴尼亞",
  Vercelli: "韋爾切利",
  Verona: "維羅納",
  "Vest-Agder Fylke": "背心阿格德郡",
  "Vestfold Fylke": "西福爾郡",
  Veszprem: "維斯普雷姆",
  VI: "美國維爾京群島，",
  "VIANA DO CASTELO": "維亞納堡",
  "Vibo Valentia": "維博瓦倫蒂亞",
  "Viborg amt": "維堡AMT",
  VIC: "維多利亞",
  Vicenza: "維琴察",
  Vichada: "比查達",
  Vienne: "維埃納省",
  "Vienne (Haute)": "維埃納省（高級）",
  "VILA REAL": "雷阿爾",
  "Virgin Gorda": "維爾京戈達",
  VISEU: "維塞烏",
  Viterbo: "維泰博",
  Vizcaya: "比斯開",
  VLADIMIR: "弗拉基米爾",
  Vladivostok: "符拉迪沃斯托克",
  VOLGOGRAD: "伏爾加格勒",
  VORONEZH: "沃羅涅日",
  Vosges: "孚日",
  "Vostochno-Kazakhstan": "vostochno，哈",
  Vrancea: "弗朗恰",
  VT: "佛蒙特",
  "Vukovar-Srijem": "武科瓦爾，Srijem",
  WA: "華盛頓",
  WA: "西澳大利亞州",
  Waikato: "懷卡托",
  Walbrzych: "瓦烏布日赫",
  Warrington: "靈頓",
  Warszawa: "華沙",
  Warwickshire: "沃里克",
  Waterford: "沃特福德",
  WB: "西孟加拉邦",
  Wellington: "惠靈頓",
  "West Coast": "西海岸",
  "West Glamorgan": "西Glamorgan的",
  "West Lothian": "西洛錫安",
  "West Midlands": "西米德蘭",
  "West Sussex": "西薩塞克斯",
  "West Visayas": "西維薩亞斯",
  "West Yorkshire": "西約克郡",
  "Western Cape": "西開普省",
  "Western Isles": "西部群島",
  "Western Mindanao": "西棉蘭老島",
  "WESTERN SAMAR": "西部SAMAR",
  Westmeath: "西米斯",
  Wexford: "韋克斯福德",
  WI: "威斯康星州",
  Wicklow: "威克洛",
  Wiltshire: "威爾特",
  "Windsor & Maidenhead": "溫莎和梅登黑德",
  Wloclawek: "弗沃茨瓦韋克",
  Wokingham: "沃金厄姆",
  Worcestershire: "伍斯特郡",
  Wroclaw: "弗羅茨瓦夫",
  WV: "西弗吉尼亞州",
  WY: "懷俄明州",
  Xinjiang: "新疆",
  Xizang: "西藏",
  "Yakutiya-Saha Rrepub": "yakutiya-薩哈Rrepub",
  Yakutsk: "雅庫茨克",
  YALA: "亞拉",
  Yalova: "亞洛瓦",
  "YAMALO-NENETS": "亞馬爾 - 涅涅茨",
  YAROSLAV: "雅羅斯拉夫",
  YASOTHON: "耶梭通",
  Yekaterinburg: "葉卡捷琳堡",
  "Yilan County": "宜蘭縣",
  Yonne: "約訥",
  York: "紐約",
  Yorkshire: "約克郡",
  Yozgat: "約茲加特",
  YT: "育空地區",
  Yucatan: "尤卡坦半島",
  "Yunlin County": "雲林縣",
  Yunnan: "雲南",
  Yvelines: "伊夫林",
  Zacatecas: "薩卡特卡斯",
  "Zadar-Knin": "扎達爾 - 克寧",
  "Zagorje Ob Savi": "zagorje OB薩維",
  Zagreb: "薩格勒布",
  Zala: "砸落",
  Zalaegerszeg: "佐洛埃格塞格",
  ZAMBALES: "三描禮士",
  "ZAMBOANGA DEL NORTE": "北三寶顏",
  "ZAMBOANGA DEL SUR": "三寶顏",
  Zamora: "薩莫拉",
  Zamosc: "扎莫希奇",
  Zaragoza: "薩拉戈薩",
  Zeeland: "澤蘭",
  Zhejiang: "浙江",
  "Zielona Gora": "錫隆納葛拉",
  Zonguldak: "宗古爾達克",
  Zug: "楚格",
  "Zuid-Holland": "南荷蘭",
  Zulia: "蘇利亞",
  Zurich: "蘇黎世",
  静岡県: "靜岡県",
};