//lang code =ko, form locale = ko_KR, form language = 한국어 (Korean)
var translateState = {
  AA: "국군 미국",
  Aargau: "아르 가우",
  AB: "앨버타",
  ABRA: "상자를",
  "Abu Dhabi": "아부 다비",
  Acre: "에이커",
  ACT: "Aust 자본금 Terr",
  Adana: "아다나",
  "ADGCID Campo": "ADGCID 캄포",
  Adiyaman: "아디야만",
  AE: "국군 유럽",
  Agri: "아그리",
  Aguascalientes: "아과 스 칼리 엔테스",
  "AGUSAN DEL NORTE": "AGUSAN DEL 노르테",
  Ain: "아무것도",
  "AISEN DEL GENERAL CA": "AISEN DEL 일반 캘리포니아",
  AK: "알래스카",
  "Akershus Fylke": "아케 르스 후스 Fylke",
  Aksaray: "아크 사레",
  AL: "알라바마",
  "Al Fujayrah": "알 Fujayrah",
  Alagoas: "알라 고 아스",
  Alava: "알라바",
  Alba: "알바",
  Albacete: "알바세테",
  "Alentejo Litoral": "Litoral Alentejo",
  Alessandra: "알레 산드라",
  Alexandria: "알렉산드 리아",
  Alicante: "알리칸테",
  Allier: "알리",
  Almeria: "알메리아",
  "Alpes (Hautes)": "알프스 (오트)",
  "Alpes (Hte-Provence)": "알프스 (했나 - 프로방스)",
  "Alpes-Maritimes": "알프 마리팀",
  ALTAY: "알타이",
  Amapa: "아마파",
  Amasya: "아마스야",
  AMAZONAS: "나스",
  AMAZONAS: "나스",
  AMUR: "아무르",
  AN: "Andamans / 니코 바르",
  Ancona: "앙코나",
  "Anenii Noi": "Anenii 노이",
  "Ang Thong": "중앙의 끈팬티",
  Angus: "앵거스",
  Anhui: "안후이",
  Ankara: "앙카라",
  ANTIQUE: "고대의",
  Antofagasta: "안토 파가 스타",
  Antwerp: "앤트워프",
  Aosta: "아오 스타",
  AP: "국군 태평양",
  AP: "안드 라 프라 데",
  "Appenzell Ausserrh.": "아펜첼 Ausserrh.",
  "Appenzell Innerrh": "아펜첼 Innerrh",
  AR: "아루나찰 프라 데",
  AR: "아칸소",
  Arad: "아라드",
  Ardahan: "아르 다한",
  Ardennes: "아르 덴",
  Arequipa: "아레키파",
  Arezzo: "아레초",
  "Århus amt": "오르후스 AMT",
  ARKHANGELSK: "아르 한 겔 스크",
  Artvin: "아르트빈",
  AS: "아메리칸 사모아",
  AS: "아삼",
  "Ascoli Piceno": "아스 콜리 피체노",
  Asti: "아스티",
  ASTRAKHAN: "아스트라한",
  Asturias: "아스 투 리아스",
  Aswan: "아스완",
  Atacama: "아타 카마",
  ATHENS: "아테네",
  Atlantico: "아틀란티코",
  Aube: "오브",
  Auckland: "오클랜드",
  Aude: "오드",
  AURORA: "오로라",
  "Aust-Agder Fylke": "아우스트애그더 Fylke",
  Ave: "번가",
  Avellino: "아벨 리노",
  Aveyron: "아베롱",
  Avila: "아빌라",
  Avon: "에이번",
  Aydin: "아이딘",
  AZ: "애리조나",
  "Bacs-Kiskun": "절대 후퇴 - Kiskun",
  Badajoz: "바다 호스",
  "Baden-Württemberg": "바덴 - 뷔르템베르크",
  Bahia: "바이아",
  "Baja California Nort": "바하 캘리포니아 Nort",
  "Baja California Sur": "바하 캘리포니아 수르",
  "Bali Bali": "발리 발리",
  Balikesir: "발리케시르",
  Bangkok: "방콕",
  Barcelona: "바르셀로나",
  Bari: "바리",
  Bartin: "바르틴",
  "Bas-Rhin": "바스 - 라인강",
  "Basel (city)": "바젤 (시)",
  "Basel (regional)": "바젤 (지역)",
  BASHKORTOSTAN: "바슈 코르 토 스탄",
  BATAAN: "바탄",
  "Bath&NthEstSomerset": "바스 & NthEstSomerset",
  Batman: "말 당번",
  "Bay of Plenty": "플렌티 만",
  Bayburt: "바이 부 르트",
  Bayern: "바이에른",
  BC: "브리티시 컬럼비아",
  Bedfordshire: "이만",
  Beijing: "북경",
  "Beira Interior Norte": "베이라 인테리어 노르테",
  BEJA: "베자",
  Belfast: "벨파스트",
  Belluno: "벨루노",
  Bender: "흥청거림",
  Benevento: "베네 벤토",
  BENGAL: "벵골",
  Bergamo: "베르 가모",
  Bergen: "베르겐",
  Berkshire: "버크셔",
  Berlin: "베를린",
  Bern: "베른",
  Biella: "비엘라",
  Bilecik: "빌레직",
  BINGOL: "빙괼",
  "Bio-Bio": "바이오 바이오",
  Bitlis: "비틀리스",
  Blackburn: "블랙번",
  Blackpool: "블랙풀",
  "Blekinge Län": "블레킹예 란",
  Bogota: "보고타",
  Bolivar: "볼리바르",
  Bologna: "볼로냐",
  Bolu: "볼루",
  Bolzano: "볼차노",
  Borders: "테두리",
  "Bornholm amt": "보른 홀름 AMT",
  Botosani: "보토샤니",
  "Bouches-du-Rhone": "Bouches - 뒤 - 론",
  Bournemouth: "본머스",
  BR: "비하르",
  Brabant: "브라반트",
  "Bracknell Forest": "블랙 넬 숲",
  BRAGA: "브래거",
  "BRAGAN¦A": "브라간사",
  Braila: "브러 일라",
  Brandenburg: "브란 덴 부르크",
  Brasov: "브라쇼브",
  Bratislava: "브라 티슬라바",
  Bremen: "브레멘",
  Brescia: "브레시아",
  "Brighton & Hove": "브라이튼 & Hove",
  Brindisi: "브린 디시",
  Bristol: "브리스틀",
  Bucuresti: "부쿠레슈티",
  Budapest: "부다페스트",
  "Buenos Aires": "부에노스 아이레스",
  Burdur: "부르두르",
  Burgenland: "부르겐란트",
  Burgos: "부르 고스",
  Bursa: "부르사",
  BURYATIYA: "부리야티야",
  "Buskerud Fylke": "부스케루 Fylke",
  Bydgoszcz: "비드고슈치",
  CA: "캘리포니아",
  Caceres: "카세 레스",
  Cadiz: "카디즈",
  "Cagayan Valley": "Cagayan 밸리",
  Cagliari: "칼리 아리",
  Cairo: "카이로",
  Cajamarca: "카자 마카",
  "CAMARINES NORTE": "CAMARINES 노르테",
  "CAMARINES SUR": "CAMARINES 쉬르",
  Campeche: "캄페체",
  Cankiri: "칸키리",
  Cantabria: "칸타 브리아",
  Cantal: "캉탈",
  Canterbury: "캔터베리",
  Capetown: "케이프 타운",
  Caracas: "카라카스",
  "Caras-Severin": "카라스 - 세브린",
  Caserta: "카세르타",
  Castellon: "카스텔론",
  "CASTELO BRANCO": "CASTELO 브랑코",
  Catania: "카타 니아",
  Catanzaro: "카탄 차로",
  Ceara: "세아라",
  CEBU: "세부",
  Central: "중심적인",
  "Central Luzon": "중부 루존",
  "Central Visayas": "중앙 Visayas",
  Cesar: "세자르",
  CH: "찬디가르",
  "Chai Nat": "차이티 냇",
  "Chakassky Republic": "Chakassky 공화국",
  "Changhua County": "장화현",
  Charente: "샤항트",
  "Charente-Maritime": "샤항트-해양",
  CHECHNYA: "체첸",
  CHELYABINSK: "첼랴빈스크",
  Cher: "쉐어",
  Cheshire: "익살",
  "Chiang Mai": "치앙마이",
  "Chiang Rai": "치앙 라이",
  "Chiayi City": "자이시",
  "Chiayi County": "자이현",
  Chieti: "키에티",
  Chisinau: "키시 나우",
  CHITA: "치타",
  Choco: "초코",
  "Chon Buri": "촌부리 Buri",
  Chongqing: "충칭",
  Chumphon: "Chumphon의",
  "Ciudad Real": "시우 다드 레알",
  Clare: "클레어",
  Cleveland: "클리블랜드",
  "Cntrl Mindanao": "Cntrl 민다나오",
  CO: "콜로라도",
  Coahuila: "코아 우 일라",
  COIMBRA: "쿠임브라",
  Colima: "콜리마",
  Como: "코모",
  Copenhagen: "코펜하겐",
  Cordoba: "코르도바",
  Cork: "코르크",
  Cornwall: "콘월",
  "Corse-du-Nord": "코르스 - 뒤 - 노르",
  "Corse-du-Sud": "꼬르스-DU-수드",
  Corum: "코룸",
  Cosenza: "코센차",
  COTABATO: "코타 바토",
  "Cote-d Or": "코트-D 또는",
  "Cotes-d Armor": "Cotes-D 갑옷",
  "Cova da Beira": "Cova 다 베이라",
  Cremona: "크레 모나",
  Creuse: "크뢰즈",
  Crotone: "크로토네",
  CT: "차티스가르",
  CT: "코네티컷",
  Cuenca: "쿠엥카",
  Cumbria: "컴브리아",
  Cuneo: "쿠네오",
  Cuzco: "꾸스꼬",
  DAGESTAN: "다게스탄",
  "Dalarnas Län": "달라 르 나스 란",
  "Dar-es-Salaam": "다르 에스 살람-ES-",
  DAVAO: "다바오",
  "DAVAO DEL NORTE": "다바오 DEL 노르테",
  "DAVAO DEL SUR": "다바오 DEL SUR",
  "DAVAO ORIENTAL": "다바오 오리엔탈",
  DC: "컬럼비아 특별구",
  DD: "다만디우",
  DE: "델라웨어",
  Debrecen: "데브레첸",
  "Delta Amacuro": "델타 Amacuro",
  Denizli: "데니 즐리",
  Derbyshire: "더비셔",
  Devon: "데본",
  "DI Aceh Aceh": "DI 아체 아체",
  "DI Yogyakarta Yogyak": "DI 족자 카르타 Yogyak",
  "Distrito Especial": "Distrito 특히",
  "Distrito Federal": "Distrito 연방",
  Diyarbakir: "디야르바키르",
  "DKI Jakarta Jakarta": "DKI 자카르타 자카르타",
  DL: "뉴델리",
  DN: "DADRA 나가르어야",
  Donegal: "도네",
  Dordogne: "도르도뉴",
  Dorset: "영국 남부의 주",
  Down: "아래로",
  DRAMAS: "드라마",
  Drenthe: "드렌테",
  Dublin: "더블린",
  "Dubrovnik-Neretva": "두브로브니크 - Neretva",
  "Dumfries a. Galloway": "을 Dumfries. 갤러 웨이",
  Durango: "뒤랑고",
  Durham: "더럼",
  "East Lothian": "동쪽 Lothian",
  "East Riding": "이스트 타기",
  "East Sussex": "이스트 서섹스",
  "Eastern Cape": "이스턴 케이프",
  "EASTERN SAMAR": "동방 SAMAR",
  "Eastern Visayas": "동부 Visayas",
  Edirne: "에디 르네",
  Eger: "에게르",
  Elazig: "엘라 지그",
  "Entre Douro e Vouga": "Entre Douro 전자 Vouga",
  "Entre Rios": "Entre 리오스",
  Erzurum: "에르쥬럼",
  Eskisehir: "에스키쉐히르",
  "Espirito Santo": "에스피 리토 산토",
  Essex: "에섹스",
  Essonne: "에손",
  "Estado de Mexico": "에스타도 데 멕시코",
  Eure: "외르",
  "Eure-et-Loir": "외르 - 동부 표준시 - 큰산쥐",
  EVORA: "에보라",
  Falcon: "매",
  FARO: "놀이",
  Ferrara: "페라라",
  Fife: "파이프",
  "Finnmark Fylke": "핀마르크 Fylke",
  Firenze: "피렌체",
  FL: "플로리다",
  Foggia: "포자",
  Forli: "포르리",
  Formosa: "대만",
  "Frederiksborg amt": "프레드릭 스 보어 AMT",
  Freestate: "자치주",
  Fribourg: "프리 부르",
  Friesland: "프리슬란트",
  Frosinone: "프로시 노네",
  Fujian: "복건",
  "Fyn amt": "퓐 AMT",
  GA: "고아",
  GA: "그루지야",
  Galway: "골웨이",
  Gansu: "간쑤",
  "Garonne (Haute)": "Garonne (오트)",
  "Gävleborgs Län": "예블레보리 란",
  Gelderland: "겔더랜드",
  Geneva: "제네바",
  Genova: "제노바",
  Gers: "제르",
  Giresun: "기레순",
  Gironde: "지롱드",
  Giurgiu: "지우 르 지우",
  GJ: "구자라트",
  Glarus: "글라 루스",
  Goias: "고이 아스",
  Gorizia: "고리 치아",
  "Gotlands Län": "고틀란즈 란",
  Granada: "그라나다",
  "Greater London": "그레이터 런던",
  "Greater Manchester": "그레이터 맨체스터",
  Groningen: "흐로닝언",
  Grosseto: "그로 세토",
  GU: "괌",
  Guadalajara: "과달라하라",
  Guanajuato: "과나후아토",
  Guangdong: "광동",
  Guangxi: "광시",
  Guerrero: "게레로",
  Guipuzcoa: "기뿌스코",
  Gyor: "죄르",
  "Gyor-Moson-Sopron": "죄르 - Moson-Sopron",
  Haifa: "하이파",
  Hainan: "하이난",
  Hainaut: "에노",
  "Hajdu-Bihar": "Hajdu - 비하르",
  Hakkari: "하카리",
  "Hallands Län": "할란즈 란",
  Hamburg: "함부르크",
  Hampshire: "햄프셔",
  Hanoi: "하노이",
  "Haut-Rhin": "년산 호 - 라인강",
  "HAUTE-CORSE": "오트 꼬르스",
  "Hauts-de-Seine": "Hauts 드 센",
  "Hawke´s Bay": "혹스 베이",
  Hebei: "허베이",
  "Hedmark Fylke": "헤드 마크 Fylke",
  Heilongjiang: "흑룡 강성",
  Henan: "허난",
  "Hereford and Worcs.": "헤리퍼드 및 Worcs.",
  Hertfordshire: "하트 퍼 드셔",
  Hessen: "헤센",
  HI: "하와이",
  Hidalgo: "스페인의 하급 귀족",
  Highland: "고지",
  "Highlands-Altay Rep.": "하이랜드 - 알타이 공화국",
  "Hong Kong Island": "홍콩 섬",
  "Hordaland Fylke": "호르 다 란드 Fylke",
  "Hors-France": "Hors - 프랑스",
  HP: "히마찰프라데시",
  "Hsinchu City": "신주시",
  "Hsinchu County": "신주현",
  "Hualien County": "화롄현",
  Hubei: "호북",
  Huelva: "우엘바",
  Huesca: "우에 스카",
  Hunan: "호남",
  IA: "아이오와",
  ID: "아이다호",
  Igdir: "이그 디르",
  IL: "일리노이",
  "ILHA DA MADEIRA": "ILHA DA 마데이라",
  "ILHA DAS FLORES": "ILHA DAS 플로레스",
  "ILHA DE PORTO SANTO": "ILHA 드 포르토 산토",
  "ILHA DE SANTA MARIA": "ILHA 드 산타 마리아",
  "ILHA DE SAO JORGE": "ILHA DE SAO 호르헤",
  "ILHA DE SAO MIGUEL": "ILHA DE SAO 미구엘",
  "ILHA DO FAIAL": "ILHA는 FAIAL 할",
  "ILHA DO PICO": "ILHA가 피코를 할",
  "Ille-et-Vilaine": "Ille - 동부 표준시 - Vilaine",
  "ILOCOS NORTE": "ILOCOS 노르테",
  "ILOCOS SUR": "ILOCOS 쉬르",
  Imperia: "임페 리아",
  IN: "인디애나",
  Indre: "앵드르",
  "Indre-et-Loire": "앵드르에 루아르",
  "Ingushetija Republic": "Ingushetija 공화국",
  "Inverness-Shire": "인버네스 - 샤이",
  "Irian Jaya Irian Jay": "이리안 자야 이리안 제이",
  Irkutsk: "이르쿠츠크",
  Isernia: "이세 르 니아",
  Islamabad: "이슬 라마 바드",
  "Isle Of Arran": "Arran 섬",
  "Isle Of Barra": "Barra 섬",
  "Isle Of Benbecula": "Benbecula 섬",
  "Isle Of Bute": "Bute 섬",
  "Isle Of Canna": "칸나 섬",
  "Isle Of Coll": "Coll 섬",
  "Isle Of Colonsay": "Colonsay 섬",
  "Isle Of Cumbrae": "Cumbrae 섬",
  "Isle Of Eigg": "Eigg 섬",
  "Isle Of Gigha": "Gigha 섬",
  "Isle Of Harris": "해리스 섬",
  "Isle Of Iona": "Iona의 섬",
  "Isle Of Islay": "Islay의 섬",
  "Isle Of Jura": "쥐라 섬",
  "Isle Of Lewis": "루이스 섬",
  "Isle Of Mull": "궁리 섬",
  "Isle Of North Uist": "북한 Uist 섬",
  "Isle Of Rum": "럼 섬",
  "Isle Of Scalpay": "Scalpay 섬",
  "Isle Of Skye": "스카이 섬",
  "Isle Of South Uist": "남쪽 Uist 섬",
  "Isle Of Tiree": "Tiree 섬",
  "Isle of Wight": "와이트 섬",
  "Isles Of Scilly": "Scilly의 섬",
  Istanbul: "이스탄불",
  "Itä-Suomi": "ITA-Suomi",
  IVANOV: "이바노프",
  Izmir: "이즈미르",
  Jaen: "하엔",
  Jalisco: "코",
  "Jambi Jambi": "잠비 잠비",
  "Jämtlands Län": "옘틀란드즈 란",
  "Jasz-Nagykun-Szolnok": "Jasz-Nagykun-솔노크",
  "Jawa Barat West Java": "자와 Barat 웨스트 자바",
  "Jawa Tengah Central": "자와 Tengah 중앙",
  "Jawa Timur East Java": "자와 티무르 동자",
  Jerusalem: "예루살렘",
  JH: "자르칸드",
  Jiangsu: "강소",
  Jiangxi: "장시",
  Jilin: "지린",
  JK: "잠무 & 카슈미르",
  Johannesburg: "요하네스 버그",
  Johor: "조호르주",
  "Jönköpings Län": "옌셰핑 란",
  "Jost Van Dyke": "Jost 밴 Dyke도",
  Jujuy: "후후이",
  Jura: "쥐라",
  KA: "카르 나 타카",
  "Kalimantan Barat Wes": "칼리만탄 Barat 웨스",
  "Kalimantan Selatan S": "칼리만탄 슬라탄 S",
  "Kalimantan Tengah Ce": "칼리만탄 Tengah CE",
  "Kalimantan Timur Eas": "칼리만탄 티무르 Eas",
  KALININGRAD: "칼리 닌그라드",
  "Kalmar Län": "칼마르 란",
  KALMYKIYA: "칼미키아",
  Kanchanaburi: "칸차나 부리",
  "Kaohsiung City": "가오슝시",
  Kashmir: "카슈미르",
  Katowice: "카토 비체",
  Kayseri: "카이 세리",
  Kecskemet: "케치케메트",
  Kedah: "케다흐주",
  "Keelung City": "지룽시",
  Kelantan: "켈란탄주",
  Kent: "켄트",
  Kerry: "케리",
  Khabarovsk: "하바 로프 스크",
  "Khon Kaen": "콘캔",
  Khyber: "카이버",
  Kildare: "킬데어",
  Kilkenny: "킬케니",
  "Kingston-Upon-Hull": "킹스톤 -시 - 헐",
  "Kinmen County": "진먼현",
  Kirikkale: "키리 칼레",
  Kirklareli: "키르 클라 렐리",
  KIROV: "키로프",
  KIRSEHIR: "키르쉐히르",
  KL: "케랄라",
  "Komarom-Esztergom": "Komarom-에스테르곰",
  KOMI: "코미",
  Konya: "콘야",
  Kowloon: "구룡",
  Krabi: "크라비",
  Krakow: "크라코프",
  KRASNODAR: "크라 스노 다르",
  KRASNOYARSK: "크라 스노 야 르 스크",
  "Kronobergs Län": "크로노 베리 란",
  KS: "캔사스",
  "Kuala-Lumpur": "쿠알라룸푸르 - 콸라룸푸르",
  KURSK: "쿠르스크",
  KUTAHYA: "쿠타햐",
  "Kwazulu/Natal": "Kwazulu / 나탈",
  KY: "켄터키",
  "L Aquila": "패 Aquila",
  LA: "루이지애나",
  "La Coruña": "라 코루냐",
  "La Guajira": "라 지라",
  "La Libertad": "라 Libertad",
  "La Pampa": "라 Pampa",
  "La Rioja": "라리 오자",
  "La Spezia": "라스 페 치아",
  LAGUNA: "라구나",
  "LANAO DEL NORTE": "LANAO DEL 노르테",
  Landes: "랜디스",
  Laois: "라오 이스",
  Lara: "라라",
  "Las Palmas": "라스 팔마스",
  Latina: "라티나",
  LD: "락샤드윕",
  Lecce: "레체",
  Lecco: "레코",
  "Leicester City": "레스터 시티",
  Leitrim: "리트림",
  LENINGRADSKAYA: "레닌 그라드",
  Leon: "레온",
  LEYTE: "레이트",
  "Lianjiang County": "롄장현",
  Liaoning: "랴오닝",
  Liege: "군주",
  "Lika-Senj": "리카 - Senj",
  Limburg: "림부르흐",
  Limerick: "오행 희시",
  Lincolnshire: "링컨셔",
  Livorno: "리보 르노",
  "Ljubljana-Bezigrad": "류블랴나 - Bezigrad",
  "Ljubljana-Center": "류블랴나 - 센터",
  "Ljubljana-Moste-Polj": "류블랴나 - Moste-Polj",
  "Ljubljana-Siska": "류블랴나 - Siska",
  "Ljubljana-Vic-Rudnik": "류블랴나 - 빅 - Rudnik",
  Lodi: "로디",
  LODZKIE: "로드 즈 키",
  "Loir-et-Cher": "큰산쥐 - 동부 표준시 - 쉐어",
  Loire: "루아르",
  "Loire (Haute)": "루아르 (오트)",
  "Loire-Atlantique": "루아르 - ATLANTIQUE",
  Loiret: "루아레",
  London: "런던",
  Londonderry: "런던 데리",
  Longford: "롱퍼드",
  "Lop Buri": "베다 Buri",
  "Los Lagos": "로스 라고스",
  Lot: "로트",
  "Lot-et-Garonne": "로트 - 동부 표준시 - Garonne",
  Louth: "로우쓰",
  "Lower Austria": "낮은 오스트리아",
  LUBELSKIE: "루벨스키에",
  Lublin: "루블린",
  Lucca: "루카",
  Lucerne: "자주 개 자리",
  Lugo: "루고",
  Luton: "루턴",
  Luxembourg: "룩셈부르크",
  MA: "매사 추세츠 주",
  Macerata: "마체라타",
  "MADRE DE DIOS": "MADRE 데 디오스",
  Madrid: "마드리드",
  "Mae Hong Son": "매 홍 손",
  MAGADAN: "마가단",
  Magdalena: "막달레나",
  "Maha Sarakham": "마하 Sarakham",
  "Maine-et-Loire": "메인에 루아르",
  Malaga: "스페인 남부의 주말 라 가산 포도",
  Malatya: "말라 티아",
  "Maluku Maluku": "말루쿠 말루쿠",
  "Malvinas/Falkland Is": "말비나스 / 포클랜드인가요",
  "Manawatu-Wanganui": "마나와투 - 왕가 누이",
  Manche: "만체",
  MANILA: "마닐라",
  Mantova: "만토바",
  Maranhao: "마라냐웅",
  Mardin: "마르딘",
  Maribor: "마리보르",
  "Marijskaya Republic": "Marijskaya 공화국",
  Marne: "마른",
  "Marne (Haute)": "마른 (오트)",
  "Masa Carrara": "마사 카라라",
  Matera: "마테라",
  "Mato Grosso": "마투그로수",
  "Mato Grosso do Sul": "마투그로수두술",
  Mayo: "메이요",
  MB: "매니토바",
  MD: "메릴랜드",
  ME: "메인",
  "Mecklenburg-Vorpommern": "메클렌부르크 - Vorpommern",
  "Médio Tejo": "메디오 Tejo",
  Melaka: "말라카",
  Mendoza: "멘도사",
  Merida: "메리다",
  Merseyside: "머지 사이드 관할",
  Messina: "메시나",
  Meta: "메타",
  "Metro Manila": "메트로 마닐라",
  "Meurthe-et-Moselle": "Meurthe - 동부 표준시 - 모젤",
  Meuse: "뫼즈",
  MI: "미시간",
  "Miaoli County": "먀오리현",
  Michoacan: "미초아깐",
  "Mid Glamorgan": "중간 Glamorgan",
  Middlesbrough: "미들 즈 브러",
  Middlesex: "미들섹스",
  MILANO: "밀라노",
  "Milton Keynes": "밀턴 케인즈",
  "Minas Gerais": "미나스 제 라이스",
  "MINDORO OCCIDENTAL": "MINDORO 서양",
  "MINDORO ORIENTAL": "MINDORO 동양",
  Miranda: "미란다",
  "MISAMIS OCCIDENTAL": "MISAMIS 서양",
  "MISAMIS ORIENTAL": "MISAMIS 동양",
  Miskolc: "미슈콜츠",
  MN: "마니 푸르",
  MN: "미네소타",
  MO: "미주리",
  Modena: "모데나",
  Monaghan: "모나한",
  Montana: "몬타나",
  Montevideo: "몬테비데오",
  Morbihan: "모르 비앙",
  MORDOVIYA: "모르도비야",
  "Møre og Romsdal F.": "더 OG Romsdal F.",
  Morelos: "모렐 로스",
  Moscow: "모스크바",
  Moselle: "모젤 강",
  MOSKVA: "모스크바",
  MOUNTAIN: "산",
  MP: "Madhya 프라 데시",
  MS: "미시시피",
  Mugla: "뮤글라",
  Murcia: "무르시아",
  Murmansk: "무르만스크",
  MUS: "뮤스",
  MZ: "미조람",
  Nagykanizsa: "나지카니자",
  "Nakhon Si Thammarat": "Nakhon시 Thammarat",
  Namur: "나무르",
  Nan: "할머니",
  "Nantou County": "난터우현",
  Naples: "나폴리",
  "NATIONAL CAPITAL REG": "국립 자본 REG",
  Navarra: "나바라",
  NB: "뉴 브 런 즈윅",
  NC: "노스 캐롤라이나",
  ND: "노스 다코타",
  NE: "네브라스카",
  "Negeri Sembilan": "네게리 셈빌란",
  "NEGROS OCCIDENTAL": "NEGROS 서양",
  "NEGROS ORIENTAL": "NEGROS 동양",
  "Nei Mongol": "네이 몽골",
  Neuchatel: "뇌사텔",
  NEVSEHIR: "네브쉐히르",
  "New TaipeiCity": "신베이시",
  "New Territories": "신계",
  "Newry and Mourne": "Newry 및 Mourne",
  NH: "뉴 햄프셔",
  Nidwalden: "니트발덴",
  Niedersachsen: "니더작센",
  Nigde: "니데",
  Ningxia: "닝샤",
  NIZHEGORODSKAYA: "니체 고",
  NJ: "뉴저지",
  NL: "나갈 랜드",
  NL: "뉴펀들랜드",
  NM: "뉴 멕시코",
  "Nong Bua Lamphu": "농 부아 Lamphu",
  "Nong Khai": "농카이",
  "Noord-Brabant": "노르트 브라반트",
  "Noord-Holland": "노르트 네덜란드",
  Nord: "노르",
  "Nord-Trøndelag Fylk": "노르 Trøndelag Fylk",
  "Nordjylland amt": "노스윌란 AMT",
  "Nordland Fylke": "노를란드 Fylke",
  "Nordrhein-Westfalen": "노르 트 라인 베스트 팔렌 -",
  Norfolk: "노포크",
  "Norrbottens Län": "노르보텐 란",
  "Norte de Santander": "노르테 데 산탄데르",
  "NORTH COTABATO": "노스 코타 바토",
  "North Down": "북쪽 아래로",
  "North Humberside": "노스 Humberside",
  "North Lincolnshire": "노스 링컨셔",
  "North Somerset": "노스 서머셋",
  "North Yorkshire": "노스 요크셔",
  "North-Osetiya Republ": "북 - 오세 티 야 니야 Republ",
  "North-West": "북서",
  Northern: "북부",
  "Northern Cape": "노던 케이프",
  "Northern Mindanao": "북부 민다나오",
  "Northern Province": "북부 지방",
  "NORTHERN SAMAR": "북부 SAMAR",
  Northland: "스칸디 나비아 반도",
  Northumberland: "노섬버랜드",
  "Nottingham City": "노팅엄시",
  "Nova Gorica": "노바 Gorica",
  Novara: "노바라",
  NOVGOROD: "노브 고 로트",
  "Novo Mesto": "노보 Mesto",
  NOVOSIBIRSK: "노보 시비 르 스크",
  NS: "노바스코샤",
  NSW: "뉴사우스 웨일즈",
  NT: "노던 테리토리",
  NT: "노스 웨스트 준주",
  "NthEast Lincolnshire": "NthEast 링컨셔",
  NU: "누나 부트",
  "NUEVA ECIJA": "누에바 ECIJA",
  "Nueva Esparta": "누에바 Esparta",
  "NUEVA VIZCAYA": "누에바 비즈카야",
  "Nuevo Leon": "누에보 레온",
  Nuoro: "누오로",
  "Nusa Tenggara Barat": "누사 Tenggara Barat",
  "Nusa Tenggara Timur": "누사 Tenggara 티무르",
  NV: "네바다",
  NY: "뉴욕",
  Nyiregyhaza: "니레지하저",
  Oaxaca: "오악 사카",
  Obwalden: "옵발덴",
  Offaly: "오팔리",
  OH: "오하이오",
  OK: "오클라호마",
  Olsztyn: "올슈틴",
  OMSK: "옴스크",
  ON: "온타리오",
  OPOLSKIE: "오폴스키",
  "Oppland Fylke": "오플 란드 Fylke",
  OR: "오레곤",
  Ordu: "오르두",
  "Örebro Län": "외레브로 란",
  Oristano: "오리스타노",
  Orkney: "오크니",
  ORLOVSKAYA: "오를 로브 스카",
  Orne: "오른",
  "Osijek-Baranja": "오시예크-Baranja",
  Oslo: "오슬로",
  "Östergötlands Län": "외스테르예틀란드 란",
  Otago: "오타고",
  Oulu: "오울루",
  Overijssel: "오퍼 레 이설",
  Oxfordshire: "옥스 퍼 드셔",
  PA: "펜실베니아",
  Padova: "파도바",
  Pahang: "파항의",
  PALAWAN: "팔라완",
  Palencia: "팔렌 시아",
  Palermo: "팔레르모",
  Para: "파라",
  Paraiba: "파라 이바",
  Parana: "파라나",
  Paris: "파리",
  Parma: "파르마",
  "Pas-de-Calais": "파 드 칼레",
  Pasco: "파스코",
  "Pathum Thani": "Pathum 타니",
  Pavia: "파비아",
  PB: "펀잡",
  PE: "프린스 에드워드 아일랜드",
  Pecs: "근육",
  "Penghu County": "펑후현",
  PENZA: "펜자",
  Perak: "페락주",
  Perlis: "페를리스주",
  PERM: "파마",
  Pernambuco: "페르남부쿠",
  Perugia: "페루자",
  Pesaro: "페사로",
  Pescara: "페스 카라",
  Pest: "해충",
  Peterborough: "피터 버러",
  Phetchaburi: "페차부리",
  Phuket: "푸켓",
  Piacenza: "피아첸차",
  Piaui: "피아 우이",
  "Pingtung County": "핑둥현",
  "Pinhal Interior N.": "Pinhal 인테리어 N.",
  "Pinhal Interior Sul": "Pinhal 인테리어 솔",
  Pisa: "피사",
  Pistoia: "피스 토 이아",
  Plymouth: "플러 머스",
  Pontevedra: "폰테 베 드라",
  Poole: "풀",
  Pordenone: "포르 데 노네",
  PORTO: "포르토",
  Portsmouth: "영국 남부의 군항",
  Postojna: "포스토",
  Potenza: "포텐차",
  Poznan: "포즈난",
  PR: "푸에르 토리코",
  "PRACHUAP KHIRI KHAN": "PRACHUAP KHIRI 칸",
  Praha: "프라하",
  Prato: "프라토",
  PRIMORSKIY: "프리 모르",
  PSKOV: "프스코프",
  Puebla: "푸에블라",
  "Pulau Pinang": "풀라우 Pinang",
  "Puy-de-Dôme": "퓌이 드 돔",
  PW: "팔라우",
  "Pyrenees (Hautes)": "피레네 산맥 (오트)",
  "Pyrenees-Atlantiques": "피레네 - Atlantiques",
  "Pyrenees-Orientales": "피레네 - Orientales",
  QC: "퀘벡",
  Qinghai: "칭하이",
  QLD: "퀸즐랜드",
  "Quarry Bay": "채석장 베이",
  Queretaro: "케레타로",
  QUEZON: "퀘존",
  Quito: "키토",
  "Ra's al Khaymah": "라스 알 Khaymah",
  "Radlje Ob Dravi": "Radlje 오브 Dravi",
  Radom: "라돔",
  Ragusa: "라구사",
  Ravenna: "라벤나",
  "Ravne Na Koroskem": "Ravne 나 Koroskem",
  RAYONG: "라용",
  Reading: "독서",
  "Redcar and Cleveland": "Redcar와 클리블랜드",
  "Reggio Calabria": "레지오 칼라 브리아",
  "Reggio Emilia": "레지오 에밀리아",
  "Region Metropolitana": "지역 Metropolitana",
  "Rep di San Marino": "담당자 디 산마리노",
  Réunion: "레위니옹",
  Rhone: "론",
  RI: "로드 아일랜드",
  "Ribe amt": "리베 AMT",
  Rieti: "리에티",
  Rimini: "리미니",
  "Rio De Janeiro": "리오 드 자네이로",
  "Rio Grande de Norte": "리오 그란데 노르테 데",
  "Rio Grande do Sul": "리우그란데두술",
  "Rio Negro": "리오 네그로",
  RIZAL: "리잘",
  Rize: "리제",
  RJ: "라자스탄",
  "Rochester Up. Medway": "로체스터 올라간다. Medway",
  "Rogaland Fylke": "로가 란드 Fylke",
  "ROI ET": "투자 수익 (ROI) 동부 표준시",
  Rome: "로마",
  Rondonia: "론도니아",
  Roraima: "로라 이마",
  "Roskilde amt": "로스킬레 AMT",
  "Ross-Shire": "로스 - 샤이",
  ROSTOV: "로스토프",
  Rovigo: "로비고",
  Ruse: "책략",
  SA: "사우스 오스트 레일 리아",
  "Sa Kaeo": "사 Kaeo",
  Saarland: "자를란트",
  Sabah: "사바",
  Sachsen: "작센",
  "Sachsen-Anhalt": "작센 - 안할트",
  SAKHA: "사하",
  SAKHALIN: "사할린",
  Salamanca: "살라망카",
  Salerno: "살레 르노",
  Salta: "빨리하자",
  Salzburg: "잘츠부르크",
  SAMARA: "익과",
  Samsun: "삼순",
  "San Anders de Provi:": "샌프란 앤더스 드 Provi :",
  "San Juan": "산 후안",
  "San Luis": "산 루이스",
  "San Luis Potosi": "산 루이스 포토시",
  "San Martín": "산 마틴",
  SANLIURFA: "샨리우르파",
  "Santa Catarina": "산타 카타 리나",
  "Santa Cruz": "산타 크루즈",
  "Santa Fe": "산타페",
  Santander: "산탄데르",
  Santiago: "산티아고",
  "Santiago Del Estero": "산티아고 델 Estero",
  "Sao Paulo": "상파울로",
  "Saone (Haute)": "Saone (오트)",
  "Saone-et-Loire": "Saone에 루아르",
  SARATOV: "사라토프",
  Sarawak: "사라왁",
  Sarthe: "사르테",
  Sassari: "사사리",
  "Satu Mare": "사투 마레",
  Savoie: "사부아",
  "Savoie (Haute)": "사부아 (오트)",
  Savona: "사보나",
  SC: "사우스 캐롤라이나",
  Schaffhausen: "샤프 하우젠",
  "Schleswig-Holstein": "슐레스비히 홀스타인",
  Scotland: "스코틀랜드",
  SD: "사우스 다코타",
  Segovia: "세고비아",
  "Seine-et-Marne": "세느강 - 동부 표준시 - 마른",
  "Seine-Maritime": "세느강 - 해양",
  "Seine-Saint-Denis": "센 - 생드니",
  Select: "선택",
  Sergipe: "세르 지페",
  Sevilla: "세비야",
  "Sevres (Deux)": "Sevres (중기관총)",
  Shaanxi: "섬서성",
  Shandong: "산동",
  Shanghai: "상하이",
  Shanxi: "산서",
  Shetland: "쉐트랜드의 옛 이름",
  Sibiu: "시비우",
  Sichuan: "사천",
  Siena: "시에나",
  "SING BURI": "BURI를 불러",
  Singapore: "싱가포르",
  Sinop: "시놉",
  Siracusa: "시라쿠사",
  SIRNAK: "쉬르낙",
  SK: "서스캐처원",
  SK: "시킴",
  "Skåne Län": "스코네 란",
  SLASKIE: "슬라 스키",
  Sligo: "슬라이고",
  Slough: "허물",
  SMOLENSK: "스몰 렌 스크",
  "Södermanlands Län": "쇠데르만란드 란",
  "SOFIYA-GRAD": "SOFIYA-마치고",
  "Sogn og Fjordane F.": "소근 오 휘요라네 F.",
  Solothurn: "졸로투른",
  Somerset: "공중제비",
  Somme: "솜강",
  Sondrio: "손드리오",
  SONGKHLA: "송크라",
  Soria: "소리아",
  "SOUTH COTABATO": "남아 코타 바토",
  "South Glamorgan": "남쪽 Glamorgan",
  "South Humberside": "사우스 Humberside",
  "South Luzon": "사우스 루존",
  "South Mindanao": "남부 민다나오",
  "South Yorkshire": "사우스 요크셔",
  Southampton: "사우샘프턴",
  Southend: "사우스",
  Southern: "남부의",
  "SOUTHERN LEYTE": "남부 레이트",
  Southland: "남국",
  "Split-Dalmatia": "분할 - Dalmatia",
  "St. Gallen": "장크트갈렌",
  "St. Petersburg": "상트 페테르부르크",
  "Sta. Cruz Tenerife": "역. 크루즈 테네리페",
  "Stadt Zagreb": "슈타트 자그레브",
  "Stefan-Voda": "스테판 - Voda",
  "Stockholms Län": "스톡홀름 란",
  "Stockton-on-Tees": "스탁 턴 - 온 - 티셔츠",
  Styria: "스티 리아",
  Suceava: "수체 아바",
  Sucre: "수크레",
  Suffolk: "서포크",
  SUKHOTHAI: "수코타이",
  "Sulawesi Selatan Sou": "술라웨시 슬라탄 소우",
  "Sulawesi Tengah Cent": "술라웨시 Tengah의 센트",
  "Sulawesi Tenggara So": "술라웨시 Tenggara 자",
  "Sulawesi Utara North": "술라웨시 우타라 노스",
  "SULTAN KUDARAT": "술탄 KUDARAT",
  "Sumatera Barat West": "Sumatera Barat 웨스트",
  "Sumatera Selatan Sou": "Sumatera 슬라탄 소우",
  "Sumatera Utara North": "Sumatera 우타라 노스",
  "SURAT THANI": "SURAT 타니",
  "SURIGAO DEL NORTE": "SURIGAO DEL 노르테",
  SURIN: "수린",
  Surrey: "써리",
  Sussex: "서섹스",
  Sutherland: "서덜랜드",
  Switzerland: "스위스",
  Szczecin: "슈체친",
  Szeged: "세게드",
  Szolnok: "솔노크",
  Szombathely: "솜버트헤이",
  Tabasco: "타바스코",
  Tacna: "타크나",
  "Taichung City": "타이중시",
  "Tainan City": "타이난시",
  "Taipei City": "타이베이시",
  "Taitung County": "타이둥현",
  TAK: "얘기가",
  "Taoyuan City": "타오위안시",
  Taranaki: "타라 나키",
  Taranto: "타란토",
  Tarn: "제비 갈매기",
  "Tarn-et-Garonne": "탄 - 동부 표준시 - Garonne",
  Tarragona: "타라 고나",
  TAS: "타즈 마니아",
  TATARSTAN: "타타 르 스탄",
  Tekirdag: "테키르다그",
  "Tel Aviv": "텔아비브",
  "Telemark Fylke": "텔레 마크 Fylke",
  Teramo: "테라모",
  Terengganu: "테렝가누주",
  Terni: "테르니",
  "Territ.-de-Belfort": "Territ. 드 Belfort",
  Teruel: "테루엘",
  TG: "텔랑가나",
  "The Jewish Auton.are": "유대인 Auton.are",
  "The Nizhniy Novgorod": "Nizhniy 노브 고 로트",
  "The Taymir Auton.dis": "Taymir Auton.dis",
  Thurgau: "뚜르 가우",
  Thüringen: "튀링겐",
  Tianjin: "천진시",
  Ticino: "티치노",
  "Tierra Del Fuego": "티에라델푸에고",
  "Timor Timur East Tim": "티모르 티무르 이스트 팀",
  Tipperary: "티퍼러리",
  Tiraspol: "티라스폴",
  TN: "타밀 나두",
  TN: "테네시",
  Tocantins: "토칸틴스",
  Toledo: "톨레도",
  TOMSK: "톰스크",
  Torbay: "토베이",
  Tortola: "토르톨라",
  Trapani: "트라 파니",
  Trento: "트렌토",
  Treviso: "트레 비소",
  Trieste: "트리 에스테",
  "Troms Fylke": "트롬쇠 Fylke",
  Trujillo: "트루 질로",
  Tucuman: "투쿠만",
  TULA: "툴라",
  Tulcea: "툴체아",
  Tunceli: "툰셀리",
  Turin: "토리노",
  "Tuva Republic": "투바 공화국",
  TX: "텍사스",
  "Tyne and Wear": "Tyne 및 착용",
  Tyrol: "티롤",
  TYVA: "티바",
  "UBON RATCHATHANI": "우본 랏 차 타니",
  Udine: "우디네",
  "UDON THANI": "우동 타니",
  "Umm al Qaywayn": "음 알 Qaywayn",
  UP: "Uttar 프라 데시",
  "Upper Austria": "어퍼 오스트리아",
  "Uppsala Län": "웁살라 란",
  Uri: "열린우리당",
  "Ust-Ordinsky Buryat": "넣으면-Ordinsky Buryat",
  UT: "우타라칸드",
  UT: "유타",
  "UTHAI THANI": "UTHAI 타니",
  Utrecht: "위트 레흐트",
  VA: "버지니아의",
  "Val-d Oise": "발-D Oise",
  "Val-de-Marne": "발 드 마른",
  Valais: "발레",
  Valencia: "발렌시아",
  Valladolid: "바야돌 리드",
  "Valle del Cuaca": "발레 델 Cuaca",
  Valparaiso: "발파 라이 소",
  Van: "반",
  Varese: "바레세",
  Vargas: "바가스",
  "Värmlands Län": "베름란즈 란",
  Varna: "바르나",
  Vas: "중이야",
  Vaslui: "바슬루이",
  "Västerbottens Län": "베스테르보텐 란",
  "Västernorrlands Län": "베스테르노를란즈 란",
  "Västmanlands Län": "베스트 만 란드 란",
  "Västra Götalands Län": "베스 트라 고틀란즈 란",
  Vaucluse: "보클뤼즈",
  Vaud: "보",
  "Vejle amt": "바일레 AMT",
  Vendee: "사는 사람",
  Venice: "베니스",
  Vercelli: "베르 첼리",
  Verona: "베로나",
  "Vest-Agder Fylke": "베스트애그더 Fylke",
  "Vestfold Fylke": "베스트폴 Fylke",
  "Vestsjælland amt": "베스트셸란 AMT",
  Veszprem: "베스프렘",
  VI: "버진 군도, 미국",
  "Vibo Valentia": "비보 발렌시아",
  "Viborg amt": "비보르 AMT",
  VIC: "빅토리아",
  Vicenza: "비첸차",
  Vienna: "비엔나",
  Vienne: "비엔나",
  "Vienne (Haute)": "비엔나 (오트)",
  "VILA REAL": "빌라 리얼",
  "Virgin Gorda": "버진 Gorda",
  Viterbo: "비테르보",
  Vizcaya: "비즈카야",
  VLADIMIR: "블라디미르",
  Vladivostok: "블라디 보스 토크",
  VOLGOGRAD: "볼고그라드",
  VORONEZH: "보로네슈",
  Vosges: "보주",
  "Vostochno-Kazakhstan": "Vostochno - 카자흐스탄",
  VT: "버몬트",
  "Vukovar-Srijem": "부카보르-Srijem",
  WA: "워싱턴",
  WA: "웨스턴 오스트 레일 리아",
  Waikato: "와이 카토",
  Warwickshire: "워릭셔",
  Waterford: "워터 포드",
  WB: "웨스트 벵골",
  Wellington: "웰링턴",
  "West Coast": "서안",
  "West Glamorgan": "서쪽 Glamorgan",
  "West Lothian": "서쪽 Lothian",
  "West Midlands": "웨스트 미들랜드",
  "West Sussex": "웨스트 서섹스",
  "West Visayas": "서부 Visayas",
  "West Yorkshire": "웨스트 요크셔",
  "West-Vlaanderen": "웨스트 - Vlaanderen",
  "Western Cape": "웨스턴 케이프",
  "Western Isles": "서양 섬",
  "Western Mindanao": "웨스턴 민다나오",
  Wexford: "웩스포드",
  WI: "위스콘신",
  Wicklow: "위클로",
  Wiltshire: "윌트셔",
  "Windsor & Maidenhead": "윈저 & 술집에서",
  WV: "웨스트 버지니아",
  WY: "와이오밍",
  Xinjiang: "신강",
  Xizang: "시짱",
  "Yakutiya-Saha Rrepub": "Yakutiya - 사하구 Rrepub",
  Yakutsk: "야쿠츠크",
  "YAMALO-NENETS": "야말로 NENETS",
  YAROSLAV: "야로스라브",
  Yekaterinburg: "예카 테 린 부르크",
  "Yilan County": "이란현",
  York: "요크",
  Yorkshire: "요크셔",
  YT: "유콘",
  Yucatan: "유카탄",
  "Yunlin County": "윈린현",
  Yunnan: "운남",
  Yvelines: "이블린",
  "Zadar-Knin": "Zadar - Knin",
  "Zagorje Ob Savi": "Zagorje 오브 Savi",
  Zagreb: "자그레브",
  "ZAMBOANGA DEL NORTE": "ZAMBOANGA DEL 노르테",
  Zamora: "사모라",
  Zaragoza: "사라고사",
  Zhejiang: "절강",
  "Zielona Gora": "Zielona 고라",
  Zonguldak: "존굴닥",
  Zug: "추크",
  "Zuid-Holland": "Zuid-네덜란드",
  Zurich: "취리히",
  三重県: "三重 県",
  京都府: "京都 府",
  佐賀県: "佐贺 県",
  兵庫県: "兵 库 県",
  千葉県: "千叶 県",
  和歌山県: "和 歌 山 県",
  埼玉県: "埼 玉 県",
  大分県: "大分 県",
  大阪府: "大阪 府",
  奈良県: "奈良 県",
  富山県: "富山 県",
  山口県: "山口 県",
  山形県: "山形 県",
  山梨県: "山 梨 県",
  岐阜県: "岐阜 県",
  岡山県: "冈山 県",
  岩手県: "岩手 県",
  島根県: "岛 根 県",
  広島県: "広 島 県",
  徳島県: "徳 岛 県",
  新潟県: "新泻 県",
  東京都: "东京 都",
  栃木県: "栃 木 県",
  滋賀県: "滋 贺 県",
  熊本県: "熊 本 県",
  石川県: "石川 県",
  神奈川県: "神奈川 県",
  福井県: "福井 県",
  福岡県: "福冈 県",
  福島県: "福岛 県",
  秋田県: "秋田 県",
  群馬県: "群 马 県",
  茨城県: "茨城 県",
  長崎県: "长崎 県",
  長野県: "长野 県",
  青森県: "青森 県",
  静岡県: "静冈 県",
  香川県: "香 川 県",
  高知県: "高 知 県",
  鳥取県: "鸟取 県",
  鹿児島県: "鹿 児 岛 県",
};