// ##
//lang code =ru, form locale = ru_RU,  form language = Russian
var translateState = {
  AA: "Вооруженные силы Америки",
  AB: "Альберта",
  Aberdeenshire: "Абердиншир",
  "Abu Dhabi": "Абу-Даби",
  Acre: "Акр",
  Adana: "Адане",
  ADYGEA: "АДЫГЕЯ",
  AE: "Вооруженные силы Европы",
  "AGIN-BURYAT": "Агинский Бурятский",
  "AGUSAN DEL NORTE": "Агусан DEL NORTE",
  "AGUSAN DEL SUR": "Агусан DEL SUR",
  "AISEN DEL GENERAL CA": "Айсен дель Генеральная CA",
  Aisne: "Эна",
  Ajman: "Аджман",
  AK: "Аляска",
  AKLAN: "Аклан",
  Aksaray: "Аксарай",
  AL: "Алабама",
  "Al Fujayrah": "Фуджейра",
  Albacete: "Альбасете",
  Alexandria: "Александрия",
  Alicante: "Аликанте",
  Allier: "Алье",
  Almeria: "Альмерия",
  "Alpes (Hautes)": "Альпы (Hautes)",
  "Alpes (Hte-Provence)": "Альпы (Hte-Provence)",
  "Alpes-Maritimes": "Приморские Альпы",
  ALTAY: "АЛТАЙ",
  AN: "Андаманских островах / Никобарских",
  Ancash: "Анкаш",
  "Anenii Noi": "Анений Ной",
  "Ang Thong": "Анг стринги",
  Angus: "Ангус",
  Anhui: "Аньхой",
  Ankara: "Анкара",
  Antalya: "Анталия",
  Antrim: "Антрим",
  Antwerp: "Антверпен",
  Anzoategui: "Ансоатеги",
  Aosta: "Аоста",
  AP: "Андхра-Прадеш",
  AP: "Вооруженные Силы Тихоокеанского",
  Apure: "Апуре",
  Apurimac: "Апуримак",
  AR: "Арканзас",
  AR: "Аруначал-Прадеш",
  Aragua: "Арагуа",
  Arauca: "Араука",
  Araucania: "Араукания",
  Ardahan: "Ардахан",
  Ardennes: "Арденны",
  Arequipa: "Арекипа",
  Arezzo: "Ареццо",
  Argyll: "Аргайл",
  "Århus amt": "Орхус AMT",
  ARKHANGELSK: "АРХАНГЕЛЬСК",
  Artvin: "Артвин",
  AS: "Американское Самоа",
  AS: "Ассам",
  "Ascoli Piceno": "Асколи-Пичено",
  ASTRAKHAN: "АСТРАХАНЬ",
  Asturias: "Астурия",
  Aswan: "Асуан",
  ATHENS: "АФИНЫ",
  Auckland: "Окленд",
  Aude: "Од",
  Ave: "Пр.",
  Avellino: "Авеллино",
  Avila: "Авила",
  Avon: "Эйвон",
  Ayacucho: "Аякучо",
  Aydin: "Айдын",
  AZ: "Аризона",
  Bacau: "Бакэу",
  "Bacs-Kiskun": "Бач-Кишкун",
  Badajoz: "Бадахос",
  Baleares: "Балеарские острова",
  "Bali Bali": "Бали",
  Baluchistan: "Белуджистан",
  Bangkok: "Бангкок",
  Barcelona: "Барселона",
  Bari: "Бари",
  Barinas: "Баринас",
  Basarabeasca: "Басарабяска",
  "Basel (city)": "Базель (город)",
  "Basel (regional)": "Базель (региональных)",
  BASHKORTOSTAN: "БАШКОРТОСТАН",
  BASILAN: "Басилан",
  BATANGAS: "Батангас",
  "Bath&NthEstSomerset": "Ванна и NthEstSomerset",
  Batman: "Денщик",
  "Bay of Plenty": "Бухта Изобилия",
  Bayburt: "Байбурт",
  BC: "Британская Колумбия",
  Bedfordshire: "Бедфордшир",
  Beijing: "Пекин",
  Bekes: "Бекеш",
  Belfast: "Белфаст",
  BELGOROD: "БЕЛГОРОД",
  Belluno: "Беллуно",
  Bender: "Клещи",
  BENGAL: "Бенгальский",
  Bergamo: "Бергамо",
  Bergen: "Берген",
  Berlin: "Берлин",
  Bern: "Берн",
  Berwickshire: "Беруикшир",
  Bialystok: "Белосток",
  Bilecik: "Биледжик",
  BINGOL: "Бингель",
  "Bio-Bio": "Био-Био",
  "Bistrita-Nasaud": "Бистрица-Nasaud",
  Bitlis: "Битлис",
  Blackburn: "Блэкберн",
  Blackpool: "Блэкпул",
  Bogota: "Богота",
  BOHOL: "Бохол",
  Bolivar: "Боливар",
  Bologna: "Болонья",
  Bolu: "Болу",
  Bolzano: "Больцано",
  Borders: "Границы",
  "Bornholm amt": "Борнхольм AMT",
  "Borsod-Abauj-Zemplen": "Боршод-Абауй-Zemplen",
  "Bouches-du-Rhone": "Буш-дю-Рон",
  Bournemouth: "Борнмут",
  BR: "Бихар",
  "BRAGAN¦A": "Браганса",
  Brandenburg: "Бранденбургские",
  Brasov: "Брашов",
  Bratislava: "Братислава",
  Bremen: "Бремен",
  Brescia: "Брешия",
  BRESTKAYA: "Брестская",
  Briceni: "Бричень",
  "Brighton & Hove": "Брайтон и Хоув",
  Bristol: "Бристоль",
  "Brod-Posavina": "Брод-Посавская",
  BRYANSK: "БРЯНСКИЙ",
  Buckinghamshire: "Бакингэмшир",
  Budapest: "Будапешт",
  "Buenos Aires": "Буэнос-Айрес",
  Burdur: "Бурдур",
  Burgas: "Бургас",
  Burgenland: "Бургенланд",
  Burgos: "Бургос",
  Bursa: "Сумка",
  BURYATIYA: "БУРЯТИЯ",
  Bydgoszcz: "Быдгощ",
  CA: "Калифорния",
  Caceres: "Касерес",
  Cadiz: "Кадис",
  CAGAYAN: "Кагаян",
  Cagliari: "Кальяри",
  Cahul: "Кагул",
  Cainari: "Кэинарь",
  Cairo: "Каир",
  Calvados: "Кальвадос",
  "CAMARINES SUR": "Камаринес Sur",
  Cambridgeshire: "Кембриджшир",
  Camenca: "Каменка",
  Campeche: "Кампече",
  Cantabria: "Кантабрия",
  Cantal: "Канталь",
  Cantemir: "Кантемир",
  Canterbury: "Кентербери",
  Capetown: "Кейптаун",
  Caqueta: "Какета",
  Caracas: "Каракас",
  "Caras-Severin": "Караш-Северин",
  Caserta: "Казерта",
  "CASTELO BRANCO": "Каштелу-Бранку",
  Catamarca: "Катамарка",
  Catania: "Катания",
  Cauca: "Каука",
  "Ceadir-Lunga": "Чадыр-Лунга",
  Ceara: "Сеара",
  Central: "Центральный",
  "Central Luzon": "Центральный Лусон",
  CH: "Чандигарх",
  Chaco: "Чако",
  "Chai Nat": "Чайнат",
  "Chakassky Republic": "Chakassky Республики",
  "Changhua County": "Графство Чанхуа",
  "Chanti-Mansyjsky Aut": "КЬЯНТИ-Mansyjsky Aut",
  Charente: "Шарента",
  "Charente-Maritime": "Приморская Шаранта",
  "CHECHENO-INGUSHETIA": "Чечено-Ингушетия",
  CHECHNYA: "ЧЕЧНЯ",
  Chelm: "Хелм",
  CHELYABINSK: "ЧЕЛЯБИНСК",
  CHERKASKA: "Черкасская",
  CHERNIHIVSKA: "Черниговская",
  CHERNIVETSKA: "Черновицкая",
  Cheshire: "Чешир",
  Chiapas: "Чиапас",
  "Chiayi City": "Город Чиай",
  "Chiayi County": "Графство Чейи",
  Chisinau: "Кишинев",
  CHITA: "ЧИТА",
  "Chon Buri": "Чонбури",
  Chongqing: "Чунцин",
  CHUKOT: "Чукотский",
  "Chukotka Auton. dist": "Чукотка Auton. расстояние",
  CHUVASHIA: "ЧУВАШИИ",
  Cimislia: "Чимишлия",
  "Ciudad Real": "Сьюдад-Реаль",
  Clare: "Клэр",
  Cleveland: "Кливленд",
  Cluj: "Клуж",
  "Cntrl Mindanao": "Cntrl Минданао",
  CO: "Колорадо",
  Cojedes: "Кохедес",
  Como: "Комо",
  Comrat: "Комрат",
  Copenhagen: "Копенгаген",
  Cordoba: "Кордова",
  Cork: "Пробка",
  Cornwall: "Корнуолл",
  "Corse-du-Nord": "Corse-дю-Норд",
  "Corse-du-Sud": "Корсика Sud",
  "Cote-d Or": "Кот-д Или",
  "Cotes-d Armor": "Кот-д брони",
  "Cova da Beira": "Кова-да-Бейра",
  Cremona: "Кремона",
  Creuse: "Крез",
  Criuleni: "Криулень",
  Crotone: "Кротоне",
  CT: "Коннектикут",
  CT: "Чхаттисгарх",
  Cuenca: "Куэнка",
  Cumbria: "Камбрия",
  Cuzco: "Куско",
  Czestochowa: "Ченстохова",
  "D.O.M.T.O.M": "DOMTOM",
  DAGESTAN: "ДАГЕСТАН",
  "Dar-es-Salaam": "Дар-эс-Саламе",
  Darlington: "Дарлингтон",
  "DAVAO DEL NORTE": "Давао дель Норте",
  "DAVAO DEL SUR": "Давао дель-СЮР",
  DC: "Округ Колумбия",
  DD: "Даман и Диу",
  DE: "Делавэр",
  Debrecen: "Дебрецен",
  Denizli: "Денизли",
  Derbyshire: "Дербишир",
  "DI Aceh Aceh": "DI-Ачех провинции Ачех",
  "DI Yogyakarta Yogyak": "DI Джокьякарта Yogyak",
  "Distrito Especial": "Округ Особенной",
  "Distrito Federal": "Федеральный округ",
  Diyarbakir: "Диярбакыр",
  "DKI Jakarta Jakarta": "ДКИ Джакарта",
  DL: "Нью-Дели",
  DN: "Дадра и Нагар ЕСТЬ",
  DNIPROPETROVSKA: "Днепропетровская",
  DOLNOSLASKIE: "Dolnośląskie",
  Donduseni: "Дондюшаны",
  DONETSKA: "Донецкая",
  Dordogne: "Дордонь",
  Dorset: "Дорсет",
  Douro: "Дору",
  Down: "Вниз",
  DRAMAS: "ДРАМЫ",
  Drenthe: "Дренте",
  Drochia: "Дрокия",
  Drome: "Дром",
  Dubasari: "Дубэсарь",
  Dublin: "Дублин",
  "Dubrovnik-Neretva": "Дубровник-Неретва",
  "Dumfries a. Galloway": "Дамфрис. Малорослая",
  Dunaujvaros: "Дунауйварош",
  "East Lothian": "Восточный Лотиан",
  "East Riding": "Восточный райдинг",
  "East Sussex": "Восточный Суссекс",
  "Eastern Cape": "Восточный Кейп",
  "EASTERN SAMAR": "ВОСТОЧНО-SAMAR",
  "Eastern Visayas": "Восточная Visayas",
  Edinet: "Единец",
  Edirne: "Эдирне",
  Elblag: "Эльблонг",
  "Entre Douro e Vouga": "Entre Дору электронной Vouga",
  Erzincan: "Эрзинджан",
  Erzurum: "Эрзурум",
  Eskisehir: "Эскишехир",
  "Espirito Santo": "Эспириту-Санту",
  Essex: "Эссекс",
  "Estado de Mexico": "Эстадо де Мехико",
  Eure: "Эр",
  "Eure-et-Loir": "Эр и Луар",
  "Evensky Auton.distri": "Эвенском Auton.distri",
  EVREYSKAYA: "Еврейская",
  Falcon: "Сокол",
  Falesti: "Фэлешть",
  Fejer: "Фейер",
  Ferrara: "Феррара",
  Fife: "Дудка",
  "Finnmark Fylke": "Финнмарк Fylke",
  FL: "Флорида",
  Flevoland: "Флеволанд",
  Foggia: "Фоджа",
  Forli: "Форли",
  Formosa: "Тайвань",
  Fribourg: "Фрибург",
  Fujian: "Фуцзянь",
  "Fyn amt": "Фюн AMT",
  GA: "Гоа",
  GA: "Грузия",
  Galway: "Голуэй",
  Gansu: "Ганьсу",
  "Garonne (Haute)": "Гаронна (Haute)",
  Gaziantep: "Газиантеп",
  Gdansk: "Гданьск",
  Geneva: "Женева",
  Giresun: "Гиресун",
  GJ: "Гуджарат",
  Glodeni: "Глодень",
  Gloucestershire: "Глостершир",
  Goias: "Гояс",
  GORKOVSKAYA: "Горьковская",
  Granada: "Гранада",
  "Greater London": "Большой Лондон",
  "Greater Manchester": "Большой Манчестер",
  Grigoriopol: "Григориополь",
  Groningen: "Гронинген",
  Grosseto: "Гроссето",
  GU: "Гуам",
  Guadalajara: "Гвадалахара",
  Guainia: "Гуаниа",
  Guanajuato: "Гуанахуато",
  Guangdong: "Гуандун",
  Guangxi: "Гуанси",
  Guarico: "Гуарико",
  Guaviare: "Гуавиаре",
  Guerrero: "Герреро",
  Guizhou: "Гуйчжоу",
  GUMUSHANE: "Гюмюшхане",
  Gyor: "Дьер",
  "Gyor-Moson-Sopron": "Дьер-Мошон-Шопрон",
  Haifa: "Хайфа",
  Hainan: "Хайнань",
  Hainaut: "Эно",
  "Hajdu-Bihar": "Хайду-Бихар",
  Hakkari: "Хаккяри",
  Hamburg: "Гамбург",
  Hampshire: "Хэмпшир",
  Hanoi: "Ханой",
  Hatay: "Хатай",
  "HAUTE-CORSE": "Верхняя Корсика",
  "Hauts-de-Seine": "Hauts-де-Сен",
  "Hawke´s Bay": "Хокс-Бей",
  Hebei: "Хэбэй",
  Heilongjiang: "Хэйлунцзян",
  Henan: "Хэнань",
  Herault: "Эро",
  "Hereford and Worcs.": "Херефорд и Worcs.",
  Herefordshire: "Херефордшир",
  Hessen: "Гессен",
  HI: "Гавайи",
  Hidalgo: "Идальго",
  Highland: "Нагорье",
  "Highlands-Altay Rep.": "Нагорье-Алтай Респ",
  Hincesti: "Хынчешть",
  "Hors-France": "Hors-Франция",
  HP: "Химачал-Прадеш",
  HR: "Харьяна",
  "Hsinchu City": "город Синьчжу",
  "Hsinchu County": "Уезд Синьчжу",
  "Hualien County": "Округ Хуанян",
  Huancavelica: "Уанкавелика",
  HUANUCO: "Уануко",
  Hubei: "Хубэй",
  Huila: "Уила",
  Humberside: "Хамберсайд",
  Hunan: "Хунань",
  IA: "Айова",
  Ialoveni: "Яловень",
  Iasi: "Яссы",
  Ica: "Ика",
  Icel: "Ичел",
  ID: "Айдахо",
  IFUGAO: "Ифугао",
  Igdir: "Игдыр",
  IL: "Иллинойс",
  "ILHA DA GRACIOSA": "Илья да Грациоза",
  "ILHA DA MADEIRA": "Илья да Мадейра",
  "ILHA DE PORTO SANTO": "Илья-де Порту-Санту",
  "ILHA DE SANTA MARIA": "ILHA де Санта Мария",
  "ILHA DE SAO JORGE": "Илья-де-Сан-Хорхе",
  "ILHA DE SAO MIGUEL": "Илья-де Сан-Мигель",
  "ILHA DO CORVO": "ILHA DO Корво",
  "ILHA DO FAIAL": "ILHA DO Файал",
  "Ille-et-Vilaine": "Иль и Вилен",
  IN: "Индиана",
  "Indre-et-Loire": "Эндр и Луара",
  "Ingushetija Republic": "Ingushetija Республики",
  "Inverness-Shire": "Инвернесс-Шир",
  "Irian Jaya Irian Jay": "Ириан-Джая Ириан-Jay",
  Irkutsk: "Иркутск",
  Isere: "Изер",
  Islamabad: "Исламабад",
  "Isle Of Arran": "Остров Арран",
  "Isle Of Bute": "Остров Бьют",
  "Isle Of Gigha": "Остров Gigha",
  "Isle Of Iona": "Остров Ионы",
  "Isle Of Mull": "Малл",
  "Isle Of Rum": "Isle Of Ром",
  "Isle of Wight": "Остров Уайт",
  Isparta: "Испарта",
  Istanbul: "Стамбул",
  Istra: "Истра",
  "Itä-Suomi": "Ита-Суоми",
  "IVANO-FRANKIVSKA": "Ивано-Франковская",
  IVANOV: "ИВАНОВ",
  Izmir: "Измир",
  Jalisco: "Халиско",
  "Jasz-Nagykun-Szolnok": "Яс-Надькун-Szolnok",
  "Jawa Barat West Java": "Jawa Barat Западная Ява",
  "Jawa Tengah Central": "Jawa Tengah Центральной",
  "Jawa Timur East Java": "Jawa Timur Восточная Ява",
  Jerusalem: "Иерусалим",
  JH: "Джаркханд",
  Jiangsu: "Цзянсу",
  Jiangxi: "Цзянси",
  Jilin: "Цзилинь",
  JK: "Джамму и Кашмир",
  Johannesburg: "Йоханнесбург",
  "Jost Van Dyke": "Йост-Ван-Дейк",
  JUNIN: "Хунин",
  KA: "Карнатака",
  "KABARDINO-BALKARIA": "В Кабардино-Балкарии",
  "KAHRAMAN MARAS": "Kahraman МАРАС",
  "Kalimantan Barat Wes": "Калимантан Барат Wes",
  "Kalimantan Selatan S": "Калимантан Selatan S",
  "Kalimantan Tengah Ce": "Калимантан Tengah Ce",
  "Kalimantan Timur Eas": "Калимантан Тимур Eas",
  KALINGA: "Калинга",
  KALININGRAD: "КАЛИНИНГРАД",
  KALININSKAYA: "КАЛИНИНСКАЯ",
  "Kalmar Län": "Kalmar Lan",
  KALMYKIYA: "Калмыкия",
  KALUGA: "КАЛУГА",
  KALUZHSKAYA: "Калужская",
  "Kamphaeng Phet": "Кампхэнгпкет",
  Kanchanaburi: "Канчанабури",
  "Kaohsiung City": "Город Каохсиунг",
  KARABUK: "Карабук",
  "KARACHAY-CHERKESSIA": "Карачаево-Черкесия",
  Karaman: "Караман",
  KARELIA: "КАРЕЛИЯ",
  Kars: "Карс",
  Kashmir: "Кашмир",
  Katowice: "Катовице",
  Kavan: "Кавана",
  Kayseri: "Кайсери",
  Kedah: "Кедах",
  "Keelung City": "Килунг Сити",
  KEMEROV: "Кемеров",
  Kent: "Кент",
  Kerry: "Керри",
  Khabarovsk: "Хабаровск",
  KHAKASSIA: "ХАКАСИЯ",
  KHARKIVSKA: "Харьковская",
  KHERSONSKA: "Херсонская",
  KHMELNYTSKA: "Хмельницкая",
  "Khon Kaen": "Кхонкэн",
  Khyber: "Хайбер",
  KILIS: "Килис",
  Kilkenny: "Килкенни",
  "Kingston-Upon-Hull": "Кингстон-апон-Халл",
  "Kinmen County": "Округ Кинмен",
  Kirikkale: "Кырыккале",
  Kirklareli: "Кыркларели",
  KIROV: "КИРОВ",
  KIROVOGRADSKAYA: "Кировоградская",
  KL: "Керала",
  "København amt": "Копенгаген AMT",
  Kocevje: "Кочевье",
  "Komarom-Esztergom": "Комаром-Эстергом",
  KOMI: "КОМИ",
  "Komy Permjats.Aut.di": "Коми Permjats.Aut.di",
  Konin: "Конин",
  Konya: "Конья",
  Koper: "Копер",
  "Koprivnica-Krizevci": "Koprivnica-Крижевацкая",
  KOSTROM: "Кострома",
  Krabi: "Краби",
  Krakow: "Краков",
  KRASNODAR: "КРАСНОДАР",
  KRASNOYARSK: "КРАСНОЯРСК",
  KS: "Канзас",
  "Kuala-Lumpur": "Куала-Лумпур",
  KURGAN: "КУРГАН",
  KURSK: "КУРСК",
  "Kwazulu/Natal": "Квазулу / Натал",
  KY: "Кентукки",
  KYYIV: "Киев",
  KYYIVSKA: "Киевская",
  LA: "Луизиана",
  "La Coruña": "Ла-Корунья",
  "La Guajira": "Гуахира",
  "La Libertad": "Ла-Либертад",
  "La Pampa": "Ла-Пампа",
  "La Rioja": "Ла-Риоха",
  "La Spezia": "Ла Специя",
  Labuan: "Лабуан",
  LAD: "Ладакх",
  "LANAO DEL NORTE": "Ланао-дель-NORTE",
  "LANAO DEL SUR": "Ланао DEL SUR",
  Lancashire: "Ланкашир",
  "Las Palmas": "Лас-Пальмас",
  LD: "Лакшадвип",
  Lecce: "Лечче",
  Lecco: "Лекко",
  Legnica: "Легница",
  "Leicester City": "Лестер Сити",
  Leicestershire: "Лестершир",
  LENINGRADSKAYA: "ЛЕНИНГРАДСКАЯ",
  Leon: "Леон",
  Leova: "Леова",
  Lerida: "Лерида",
  LEYTE: "Лейте",
  "Lianjiang County": "Графство Ляньцзян",
  Liaoning: "Ляонин",
  Liege: "Сеньор",
  "Lika-Senj": "Лика-Сень",
  Lillehammer: "Лиллехаммер",
  Limerick: "Лимерик",
  Lincolnshire: "Линкольншир",
  LIPETSK: "ЛИПЕЦК",
  Litija: "Лития",
  Livorno: "Ливорно",
  "Ljubljana-Bezigrad": "Любляна-Bezigrad",
  "Ljubljana-Center": "Любляна-центр",
  "Ljubljana-Moste-Polj": "Любляна-Мосте-Polj",
  "Ljubljana-Siska": "Любляна-Siska",
  "Ljubljana-Vic-Rudnik": "Любляна-Vic-Рудник",
  Lodi: "Лоди",
  LODZKIE: "Łódzkie",
  "Loir-et-Cher": "Луар и Шер",
  Loire: "Луара",
  "Loire (Haute)": "Луара (Haute)",
  "Loire-Atlantique": "Атлантическая Луара",
  London: "Лондон",
  Londonderry: "Лондондерри",
  "Lop Buri": "Лопбури",
  Loreto: "Лорето",
  "Los Lagos": "Лос-Лагос",
  Lot: "Много",
  "Lot-et-Garonne": "Лот и Гаронна",
  Lovech: "Ловеч",
  "Lower Austria": "Нижняя Австрия",
  Lozere: "Лозер",
  LUBELSKIE: "ЛЮБЛИНСКОГО ВОЕВОДСТВА",
  Lublin: "Люблин",
  Lucca: "Лукка",
  Lucerne: "Люцерна",
  Lugo: "Луго",
  LUHANSKA: "Луганская",
  Luton: "Лутон",
  Luxembourg: "Люксембург",
  LVIVSKA: "Львовская",
  MA: "Массачусетс",
  "MADRE DE DIOS": "Мадре-де-DIOS",
  Madrid: "Мадрид",
  MAGADAN: "МАГАДАН",
  MAGUINDANAO: "Магинданао",
  "Maha Sarakham": "Махасаракхам",
  "Maine-et-Loire": "Мэн и Луара",
  Malaga: "Малага",
  Malatya: "Малатья",
  "Maluku Maluku": "Малуку Малуку",
  "Malvinas/Falkland Is": "Мальвинских / Фолклендских ли",
  Manche: "Манш",
  Manisa: "Маниса",
  Mardin: "Мардин",
  "MARI EL": "МАРИЙ ЭЛ",
  Maribor: "Марибор",
  "Marijskaya Republic": "Марийской Республике",
  "Marne (Haute)": "Марна (Haute)",
  Matera: "Матера",
  "Mato Grosso": "Мату-Гросу",
  "Mato Grosso do Sul": "Мату-Гросу-ду-Сул",
  Mayo: "Майонез",
  MB: "Манитоба",
  MD: "Мэриленд",
  ME: "Мэн",
  Meath: "Мит",
  "Mecklenburg-Vorpommern": "Мекленбург-Передняя Померания",
  "Médio Tejo": "Medio Tejo",
  Melaka: "Малакка",
  Merseyside: "Мерсисайд",
  Messina: "Мессина",
  MESSINIAS: "Мессинияс",
  Meta: "Мета",
  Metlika: "Метлика",
  "Meurthe-et-Moselle": "Мерт и Мозель",
  Meuse: "Мез",
  MH: "Махараштра",
  MI: "Мичиган",
  "Miaoli County": "Округ Миаоли",
  Michoacan: "Мичоакан",
  Middlesbrough: "Мидлсбро",
  "Milton Keynes": "Милтон Кейнс",
  "Minas Gerais": "Минас-Жерайс",
  "MINDORO OCCIDENTAL": "Миндоро OCCIDENTAL",
  "MINDORO ORIENTAL": "Миндоро ORIENTAL",
  Miranda: "Миранда",
  "MISAMIS ORIENTAL": "Восточный Мисамис",
  Miskolc: "Мишкольц",
  ML: "Мегхалая",
  MN: "Манипура",
  MN: "Миннесота",
  MO: "Миссури",
  Modena: "Модена",
  Monagas: "Монагас",
  Montana: "Монтана",
  Montevideo: "Монтевидео",
  MORDOVIYA: "Мордовия",
  "Møre og Romsdal F.": "Мере-ог-Румсдал F.",
  Morelos: "Морелос",
  Moscow: "Москва",
  Moselle: "Мозельвейн",
  MOSKVA: "Москва",
  MP: "Мадхья-Прадеш",
  MS: "Миссисипи",
  Mugla: "Мугла",
  Murcia: "Мурсия",
  Mures: "Муреш",
  Murmansk: "Мурманск",
  "Murska Sobota": "Мурска Собота",
  MYKOLAYIVSKA: "Николаевская",
  MZ: "Мизорам",
  "Nakhon Nayok": "Накхоннайок",
  "Nakhon Pathom": "Накхонпатхом",
  "Nakhon Ratchasima": "Накхонратчасиме",
  "Nakhon Sawan": "Накхон Саван",
  "Nakhon Si Thammarat": "Накхонситхаммарат",
  Namur: "Намюр",
  Nan: "Бабушка",
  "Nantou County": "Графство Нанту",
  Naples: "Неаполь",
  "NATIONAL CAPITAL REG": "Национальный столичный REG",
  NB: "Нью-Брансуик",
  NC: "Северная Каролина",
  ND: "Северная Дакота",
  NE: "Небраска",
  Neamt: "Нямц",
  "Negeri Sembilan": "Негри Сембилан",
  "NEGROS OCCIDENTAL": "Западный Негрос",
  "NEGROS ORIENTAL": "Восточный Негрос",
  NENETS: "НЕНЕЦКОГО",
  Neuchatel: "Невшатель",
  "New TaipeiCity": "Новый Тайбэй Сити",
  "New Territories": "Новые Территории",
  Newbury: "Ньюбери",
  "Newry and Mourne": "Ньюри и Морн",
  NH: "Нью-Гемпшир",
  Nidwalden: "Нидвальден",
  Nigde: "Нигде",
  Ningxia: "Нинся",
  Nisporeni: "Ниспорень",
  NIZHEGORODSKAYA: "НИЖЕГОРОДСКАЯ",
  NJ: "Нью-Джерси",
  NL: "Нагаленд",
  NL: "Ньюфаундленд",
  NM: "Нью-Мексико",
  "Nong Bua Lamphu": "Нонгбуалампху",
  "Nong Khai": "Нонгкай",
  "Noord-Brabant": "Северный Брабант",
  "Noord-Holland": "Северная Голландия",
  "Nord-Trøndelag Fylk": "Нур-Тренделаг Fylk",
  "Nordjylland amt": "Северная Ютландия AMT",
  "Nordrhein-Westfalen": "Северный Рейн-Вестфалия",
  Norfolk: "Норфолк",
  "Norte de Santander": "Норте-де-Сантандер",
  "NORTH COTABATO": "Северный Котабато",
  "North Humberside": "Северная Humberside",
  "North Lincolnshire": "Северный Линкольншир",
  "North Somerset": "Северный Сомерсет",
  "North Yorkshire": "Северный Йоркшир",
  "North-Osetiya Republ": "Северо-Осетинского Republ",
  "North-West": "Северо-Запад",
  Northamptonshire: "Нортгемптоншир",
  Northern: "Северный",
  "Northern Cape": "Северный Кейп",
  "Northern Mindanao": "Северный Минданао",
  "Northern Province": "Северная провинция",
  "NORTHERN SAMAR": "СЕВЕРНЫЙ SAMAR",
  Northland: "Север",
  Northumberland: "Нортумберленд",
  Nottinghamshire: "Ноттингемшир",
  "Nova Gorica": "Нова-Горица",
  Novara: "Новара",
  NOVGOROD: "НОВГОРОДЕ",
  NOVOSIBIRSK: "НОВОСИБИРСК",
  "Nowy Sacz": "Новы-Сонч",
  NSW: "Новый Южный Уэльс",
  NT: "Северные территории",
  NT: "Северо-западные территории",
  "NthEast Lincolnshire": "NthEast Линкольншир",
  NU: "Нунавут",
  "NUEVA ECIJA": "Нуэва-Эсиха",
  "Nuevo Leon": "Нуэво-Леон",
  "Nusa Tenggara Barat": "Малых Зондских островах Барат",
  "Nusa Tenggara Timur": "Малых Зондских островах Тимур",
  NV: "Невада",
  NY: "Нью-Йорк",
  Obwalden: "Обвальден",
  Ocnita: "Окница",
  ODESKA: "Одесская",
  OH: "Огайо",
  Oise: "Уаз",
  OK: "Оклахома",
  Olsztyn: "Ольштын",
  Olt: "Олт",
  OMSK: "ОМСК",
  ON: "Онтарио",
  "Oost-Vlaanderen": "Восточная Фландрия",
  OPOLSKIE: "Опольском",
  OR: "Орегон",
  "Örebro Län": "Эребру Län",
  OREL: "ОРЕЛ",
  ORENBURG: "ОРЕНБУРГ",
  Orense: "Оренсе",
  Orhei: "Орхей",
  Orkney: "Оркнейские",
  ORLOVSKAYA: "Орловская",
  "Osijek-Baranja": "Осиек-Баранья",
  Oslo: "Осло",
  Ostroleka: "Остроленка",
  Otago: "Отаго",
  Oulu: "Оулу",
  Oxfordshire: "Оксфордшир",
  PA: "Пенсильвания",
  Pahang: "Паханг",
  PALAWAN: "Палаван",
  Palermo: "Палермо",
  PANGASINAN: "Пангасинан",
  Paraiba: "Параиба",
  Paris: "Париж",
  Parma: "Парма",
  "Pas-de-Calais": "Па-де-Кале",
  Pasco: "Паско",
  "Pathum Thani": "Патхумтхани",
  PB: "Пенджаб",
  PE: "Остров Принца Эдуарда",
  Pecs: "Печ",
  "Penghu County": "Графство Пенгху",
  PENZA: "ПЕНЗА",
  PERM: "ПЕРМЬ",
  Pernambuco: "Пернамбуку",
  Persekutuan: "Персекутуан",
  Perugia: "Перуджа",
  Pesaro: "Пезаро",
  Pescara: "Пескара",
  Pest: "Вредитель",
  Peterborough: "Питерборо",
  Phatthalung: "Пхаттхалунг",
  Phichit: "Пхичит",
  "PHRA NAKHON SI AYUTT": "Пхра Накхон Си AYUTT",
  Phuket: "Пхукет",
  Piacenza: "Пьяченца",
  Piaui: "Пиауи",
  "Pingtung County": "Графство Пингтунг",
  "Pinhal Interior N.": "Pinhal внутренних N.",
  "Pinhal Interior Sul": "Pinhal внутренних Sul",
  Piran: "Пиран",
  Pisa: "Пиза",
  Plock: "Плоцк",
  Plymouth: "Плимут",
  POLTAVSKA: "Полтавская",
  Pontevedra: "Понтеведра",
  Poole: "Пул",
  Pordenone: "Порденоне",
  PORTALEGRE: "Порталегре",
  Portsmouth: "Портсмут",
  Poznan: "Познань",
  PR: "Пуэрто-Рико",
  "Prachin Buri": "Прачинбури",
  "PRACHUAP KHIRI KHAN": "Прачуапкхирикхан",
  Prahova: "Прахова",
  Prato: "Прато",
  "Primorje-Gorski Kot.": "Приморье-Горски Кот.",
  PRIMORSKIY: "ПРИМОРСКИЙ",
  Przemysl: "Пшемысль",
  PSKOV: "ПСКОВ",
  Puebla: "Пуэбла",
  "Pulau Pinang": "Пулау-Пинанг",
  Puno: "Пуно",
  Putumayo: "Путумайо",
  "Puy-de-Dôme": "Пюи-де-Дом",
  PW: "Палау",
  "Pyrenees (Hautes)": "Пиренеи (Hautes)",
  "Pyrenees-Atlantiques": "Пиренеи Атлантические",
  "Pyrenees-Orientales": "Восточные Пиренеи",
  QC: "Квебек",
  Qinghai: "Цинхай",
  QLD: "Квинсленд",
  Queretaro: "Керетаро",
  Quito: "Кито",
  "Ra's al Khaymah": "Рас-эль-Хайма",
  "Radlje Ob Dravi": "Radlje Обь Dravi",
  Radom: "Радом",
  Ragusa: "Рагуза",
  RANONG: "Ранонг",
  Ravenna: "Равенна",
  Reading: "Чтение",
  "Redcar and Cleveland": "Редкар и Кливленд",
  "Region Metropolitana": "Столичная область",
  "Rep di San Marino": "Вес ди Сан-Марино",
  Réunion: "Реюньон",
  Rezina: "Резина",
  Rhone: "Рона",
  RI: "Род-Айленд",
  Ribnita: "Рыбница",
  Rimini: "Римини",
  "Rio De Janeiro": "Рио-де-Жанейро",
  "Rio Grande de Norte": "Рио-Гранде-де-Норте",
  "Rio Grande do Sul": "Риу-Гранди-ду-Сул",
  "Rio Negro": "Рио-Негро",
  Riscani: "Рышкановка",
  RIVNENSKA: "Ровенская",
  RIZAL: "Ризал",
  Rize: "Ризе",
  RJ: "Раджастан",
  Rome: "Рим",
  Rondonia: "Рондония",
  Roraima: "Рорайма",
  ROSTOV: "РОСТОВ",
  Rovigo: "Ровиго",
  Ruse: "Хитрость",
  RYAZAN: "РЯЗАНЬ",
  Rzeszow: "Жешув",
  SA: "Южная Австралия",
  "Sa Kaeo": "Сакэу",
  Saarland: "Саар",
  "Sachsen-Anhalt": "Саксония-Анхальт",
  SAKHA: "САХА",
  SAKHALIN: "САХАЛИН",
  "SAKON NAKHON": "Саконнакхон",
  Salamanca: "Саламанка",
  Salta: "Сальта",
  Salzburg: "Зальцбург",
  SAMARA: "САМАРА",
  SAMOU: "Саму",
  Samsun: "Самсун",
  "SAMUT PRAKAN": "Самутпракан",
  "San Anders de Provi:": "Сан - Андерс де Provi:",
  "San Juan": "Сан - Хуан",
  "San Luis": "Сан - Луис",
  "San Luis Potosi": "Сан - Луис-Потоси",
  "San Martín": "Сан - Мартин",
  SANLIURFA: "Шанлиурфа",
  "Santa Catarina": "Санта-Катарина",
  "Santa Cruz": "Санта-Крус",
  SANTAREM: "Сантарен",
  Santiago: "Сантьяго",
  "Santiago Del Estero": "Сантьяго-дель-Эстеро",
  "Sao Paulo": "Сан-Паулу",
  "Saone (Haute)": "Сона (Haute)",
  "Saone-et-Loire": "Сона и Луара",
  SARANGANI: "Сарангани",
  SARATOV: "САРАТОВ",
  "Satu Mare": "Сату-Маре",
  Savoie: "Савойя",
  "Savoie (Haute)": "Савойя (Haute)",
  Savona: "Савона",
  SC: "Южная Каролина",
  Schaffhausen: "Шаффхаузен",
  "Schleswig-Holstein": "Шлезвиг-Гольштейн",
  Scotland: "Шотландия",
  SD: "Южная Дакота",
  "Seine-et-Marne": "Сена и Марна",
  Select: "Выбрать",
  Sergipe: "Сержипи",
  "Severo-Kazakhstansk": "Северо-Kazakhstansk",
  "SEVERO-OSETINSKAYA": "Северо-Осетинская",
  Sevilla: "Севилья",
  "Sevres (Deux)": "Севр (Deux)",
  Shaanxi: "Шэньси",
  Shandong: "Шаньдун",
  Shanghai: "Шанхай",
  Shanxi: "Шаньси",
  Sharjah: "Шарджа",
  Shetland: "Шетланд",
  Shropshire: "Шропшир",
  Sibenik: "Шибеник",
  Sibiu: "Сибиу",
  Sichuan: "Сычуань",
  Siena: "Сиена",
  Sieradz: "Серадз",
  Siirt: "Сиирт",
  "SING BURI": "Сингбури",
  Singapore: "Сингапур",
  Singerei: "Сынжерей",
  Sinop: "Синоп",
  SIRNAK: "Ширнаке",
  "Sisak-Moslavina": "Сисак-Мославинская",
  Sivas: "Сивас",
  SK: "Саскачеван",
  SK: "Сикким",
  "Skåne Län": "Сконе",
  Skierniewice: "Скерневице",
  SLASKIE: "Силезское",
  Slobozia: "Слободзея",
  Slough: "Омут",
  "Slovenska Bistrica": "Словенска Быстрица",
  Slupsk: "Слупске",
  SMOLENSK: "СМОЛЕНСК",
  "Södermanlands Län": "Sodermanlands Län",
  Sofiya: "София",
  "Sogn og Fjordane F.": "Согн-ог-Фьюране F.",
  Soldanesti: "Шолдэнешть",
  Somerset: "Прыжок кувырком",
  Somme: "Сомма",
  Sonora: "Сонора",
  Sopron: "Шопрон",
  "Sør-Trøndelag Fylk": "Сер-Тренделаг Fylk",
  Soria: "Сория",
  Soroca: "Сорока",
  "SOUTH COTABATO": "ЮЖНО COTABATO",
  "South Glamorgan": "Южная Glamorgan",
  "South Humberside": "Южная Humberside",
  "South Luzon": "Южный Лусон",
  "South Mindanao": "Южный Минданао",
  "South Yorkshire": "Южный Йоркшир",
  Southern: "Южный",
  "SOUTHERN LEYTE": "Южный Лейте",
  Southland: "Область на юге",
  "Split-Dalmatia": "Сплит-Далмация",
  "St. Gallen": "Санкт-Галлен",
  "St. Petersburg": "Санкт-Петербург",
  "Sta. Cruz Tenerife": "Sta. Крус, Тенерифе",
  Staffordshire: "Стаффордширский",
  STAVROPOL: "СТАВРОПОЛЬ",
  "Stefan-Voda": "Штефан-Водэ",
  "Sth. Gloucestershire": "Sth. Глостершир",
  "Stockholms Län": "Стокгольм",
  "Stockton-on-Tees": "Стоктон-он-Тис",
  Stredocesky: "Центральная Богемия",
  Styria: "Земля Штирия",
  Suceava: "Сучава",
  Sucre: "Сукре",
  Suffolk: "Суффолк",
  "Sulawesi Selatan Sou": "Сулавеси Selatan Sou",
  "Sulawesi Tengah Cent": "Сулавеси Tengah Cent",
  "Sulawesi Tenggara So": "Так Сулавеси Тенгара",
  "Sulawesi Utara North": "Сулавеси Utara Северной",
  "SULTAN KUDARAT": "Султан Кударат",
  "Sumatera Barat West": "Суматра Барат Запад",
  "Sumatera Selatan Sou": "Суматра Selatan Sou",
  "Sumatera Utara North": "Суматра Utara Северной",
  SUMSKA: "Сумской",
  "SUPHAN BURI": "Супханбури",
  "SURAT THANI": "Сурат Тхани",
  SURIN: "Сурин",
  Surrey: "Легкий двухместный экипаж",
  Sutherland: "Сазерленд",
  Suwalki: "Сувалки",
  SVERDLOV: "СВЕРДЛОВА",
  SWIETOKRZYSKIE: "Свентокшишское",
  Switzerland: "Швейцария",
  "Szabolcs-Szat.-Bereg": "Сабольч-Szat.-Берег",
  Szczecin: "Щецин",
  Szeged: "Сегед",
  Szekesfehervar: "Секешфехервар",
  Tabasco: "Табаско",
  Tachira: "Тачира",
  "Taichung City": "город Тайчжун",
  "Tainan City": "Город Тайнан",
  "Taipei City": "Тайбэй Сити",
  "Taitung County": "Округ Тайтунг",
  Tamaulipas: "Тамаулипас",
  TAMBOV: "ТАМБОВСКОЙ",
  "Taoyuan City": "Таоюань Сити",
  Taraclia: "Тараклии",
  Taranaki: "Таранаки",
  Taranto: "Таранто",
  Tarn: "Каровое озеро",
  "Tarn-et-Garonne": "Тарн и Гаронна",
  Tarragona: "Таррагона",
  TAS: "Тасмания",
  Tatabanya: "Татабанья",
  TATARSTAN: "ТАТАРСТАН",
  "TAWI-TAWI": "Тави-Тави",
  "Tel Aviv": "Тель-Авив",
  "Telemark Fylke": "Телемарк Fylke",
  Telenesti: "Теленешть",
  Terni: "Терни",
  TERNOPILSKA: "Тернопольская",
  "Territ.-de-Belfort": "Territ.-де-Белфорт",
  TG: "Телангана",
  "The Jewish Auton.are": "Еврейская Auton.are",
  "The Nizhniy Novgorod": "Нижний Новгород",
  "The Taymir Auton.dis": "Таймыр Auton.dis",
  Thurgau: "Тургау",
  Tianjin: "Тяньцзинь",
  Ticino: "Тичино",
  "Timor Timur East Tim": "Тимор Восточный Тимур Тим",
  Tiraspol: "Тирасполь",
  TN: "Тамил Наду",
  TN: "Теннесси",
  Tokat: "Токат",
  Toledo: "Толедо",
  TOLIMA: "Толима",
  TOMSK: "ТОМСК",
  Tortola: "Тортола",
  Torun: "Торунь",
  TR: "Трипура",
  Trabzon: "Трабзон",
  Transvaal: "Трансвааль",
  Trapani: "Трапани",
  Trieste: "Триест",
  Trujillo: "Трухильо",
  Tucuman: "Тукуман",
  TULA: "ТУЛЬСКАЯ",
  TULSKAYA: "ТУЛЬСКАЯ",
  Tunceli: "Тунджели",
  Turin: "Турин",
  "Tuva Republic": "Республика Тыва",
  TVER: "ТВЕРЬ",
  TX: "Техас",
  "Tyne and Wear": "Тайн и Уир",
  Tyrol: "Тироль",
  TYUMEN: "ТЮМЕНЬ",
  TYVA: "ТЫВА",
  "UBON RATCHATHANI": "Убонратчатхани",
  Ucayali: "Укаяли",
  Udine: "Удине",
  UDMURTIA: "УДМУРТИИ",
  "UDON THANI": "Удон-Тхани",
  ULYANOVSK: "УЛЬЯНОВСК",
  "Umm al Qaywayn": "Умм аль Кувейн",
  Ungheni: "Унгень",
  UP: "Уттар-Прадеш",
  "Upper Austria": "Верхняя Австрия",
  "Ust-Ordinsky Buryat": "Усть-Ордынский бурятский",
  UT: "Уттаракханд",
  UT: "Юта",
  "UTHAI THANI": "Утхайтхани",
  VA: "Виргиния",
  "Val-d Oise": "Валь-д Уаз",
  "Val-de-Marne": "Валь-де-Марн",
  Valais: "Вале",
  Valencia: "Валенсия",
  Valladolid: "Вальядолид",
  "Valle del Cuaca": "Валье-дель-Cuaca",
  Valparaiso: "Вальпараисо",
  Van: "Фургон",
  Varese: "Варезе",
  Vargas: "Варгас",
  Varna: "Варна",
  Vaslui: "Васлуй",
  "Västerbottens Län": "Вестерботтен",
  "Västernorrlands Län": "Вестерноррланд",
  "Västra Götalands Län": "Вестра Геталанд Län",
  Vaucluse: "Воклюз",
  Vaud: "Во",
  Vaupes: "Ваупес",
  "Vejle amt": "Вайле AMT",
  Vendee: "Покупатель",
  Venice: "Венеция",
  Vercelli: "Верчелли",
  Verona: "Верона",
  "Vestsjælland amt": "Vestsjaelland AMT",
  VI: "Виргинские острова, США",
  "VIANA DO CASTELO": "Виана-ду-Каштелу",
  "Viborg amt": "Выборг AMT",
  VIC: "Виктория",
  Vienna: "Вена",
  "Vienne (Haute)": "Вьенна (Haute)",
  "VILA REAL": "Вила-Реал",
  VINNYTSKA: "Винницкая",
  "Virgin Gorda": "Верджин-Горда",
  Viterbo: "Витербо",
  VLADIMIR: "ВЛАДИМИР",
  Vladivostok: "Владивосток",
  VOLGOGRAD: "ВОЛГОГРАД",
  VOLOGOD: "Вологодская",
  VOLYNSKA: "Волынская",
  Vorarlberg: "Форарльберг",
  VORONEZH: "ВОРОНЕЖ",
  "Vostochno-Kazakhstan": "Восточно-Казахстан",
  Vrancea: "Вранча",
  VT: "Вермонт",
  "Vukovar-Srijem": "Вуковар-Срема",
  VULCANESTI: "Вулканешты",
  VULCANESTI: "Вулканешты",
  WA: "Вашингтон",
  WA: "Западная Австралия",
  Warrington: "Уоррингтон",
  Warwickshire: "Уорикшир",
  WB: "Западная Бенгалия",
  Wellington: "Веллингтон",
  "West Glamorgan": "Запад Glamorgan",
  "West Lothian": "Западный Лотиан",
  "West Midlands": "Уэст-Мидлендс",
  "West Sussex": "Западный Суссекс",
  "West Visayas": "Запад Visayas",
  "West Yorkshire": "Западный Йоркшир",
  "West-Vlaanderen": "Западная Фландрия",
  "Western Isles": "Западные острова",
  "Western Mindanao": "Западные Минданао",
  WI: "Висконсин",
  Wilayah: "Вилайят",
  Wiltshire: "Графство Уилтшир",
  "Windsor & Maidenhead": "Виндзор и Maidenhead",
  Worcestershire: "Вустершир",
  Wroclaw: "Вроцлав",
  WV: "Западная Виргиния",
  WY: "Вайоминг",
  Xinjiang: "Синьцзян",
  "Yakutiya-Saha Rrepub": "Якутия-Саха Rrepub",
  Yakutsk: "Якутск",
  Yalova: "Ялова",
  "YAMALO-NENETS": "ЯМАЛО-НЕНЕЦКОГО",
  YAROSLAV: "ЯРОСЛАВ",
  Yekaterinburg: "Екатеринбург",
  "Yilan County": "Округ Илан",
  York: "Йорк",
  Yorkshire: "Йоркшир",
  Yozgat: "Йозгат",
  YT: "Юкон",
  Yucatan: "Юкатан",
  "Yunlin County": "Графство Юнлин",
  Yunnan: "Юньнань",
  "Zadar-Knin": "Задар-Книн",
  "Zagorje Ob Savi": "Загорье Ob Savi",
  Zagreb: "Загреб",
  ZAKARPATSKA: "Закарпатская",
  Zalaegerszeg: "Залаэгерсег",
  ZAMBALES: "Замбалес",
  "ZAMBOANGA DEL NORTE": "Замбоанга дель NORTE",
  "ZAMBOANGA DEL SUR": "Замбоанга дель Сур",
  "Zapadno-Kazakhst": "Западно-Kazakhst",
  ZAPORIZKA: "Запорожская",
  Zaragoza: "Сарагоса",
  Zhejiang: "Чжэцзян",
  ZHITOMIRSKAYA: "Житомирская",
  "Zielona Gora": "Зелена-Гура",
  Zonguldak: "Зонгулдак",
  "Zuid-Holland": "Южная Голландия",
  Zulia: "Зулия",
  Zurich: "Цюрих",
  三重県: "三重 県",
  京都府: "京都 府",
  佐賀県: "佐贺 県",
  兵庫県: "兵 库 県",
  千葉県: "千叶 県",
  和歌山県: "和 歌 山 県",
  埼玉県: "埼 玉 県",
  大分県: "大分 県",
  大阪府: "大阪 府",
  奈良県: "奈良 県",
  富山県: "富山 県",
  山口県: "山口 県",
  山形県: "山形 県",
  山梨県: "山 梨 県",
  岐阜県: "岐阜 県",
  岡山県: "冈山 県",
  岩手県: "岩手 県",
  島根県: "岛 根 県",
  広島県: "広 島 県",
  徳島県: "徳 岛 県",
  新潟県: "新泻 県",
  東京都: "东京 都",
  栃木県: "栃 木 県",
  滋賀県: "滋 贺 県",
  熊本県: "熊 本 県",
  石川県: "石川 県",
  神奈川県: "神奈川 県",
  福井県: "福井 県",
  福岡県: "福冈 県",
  福島県: "福岛 県",
  秋田県: "秋田 県",
  群馬県: "群 马 県",
  茨城県: "茨城 県",
  長崎県: "长崎 県",
  長野県: "长野 県",
  青森県: "青森 県",
  静岡県: "静冈 県",
  香川県: "香 川 県",
  高知県: "高 知 県",
  鳥取県: "鸟取 県",
  鹿児島県: "鹿 児 岛 県",
};