const features = [
  {
    tcid: '0',
    name: '@marketo full template (redirect)',
    path: ['/drafts/nala/blocks/marketo/full'],
    tags: '@marketo @marketoFullRedirect @marketoRedirect @smoke @regression',
    type: 'redirect',
    formType: 'full',
  },
  {
    tcid: '1',
    name: '@marketo expanded template (redirect)',
    path: ['/drafts/nala/blocks/marketo/expanded'],
    tags: '@marketo @marketoExpandedRedirect @marketoRedirect @smoke @regression',
    type: 'redirect',
    formType: 'expanded',
  },
  {
    tcid: '2',
    name: '@marketo essential template (redirect)',
    path: ['/drafts/nala/blocks/marketo/essential'],
    tags: '@marketo @marketoEssentialRedirect @marketoRedirect @smoke @regression',
    type: 'redirect',
    formType: 'essential',
  },
  {
    tcid: '3',
    name: '@marketo full template (message)',
    path: ['/drafts/nala/blocks/marketo/full-message'],
    tags: '@marketo @marketoFullMessage @marketoMessage @smoke @regression',
    type: 'message',
    formType: 'full',
  },
  {
    tcid: '4',
    name: '@marketo expanded template (message)',
    path: ['/drafts/nala/blocks/marketo/expanded-message'],
    tags: '@marketo @marketoExpandedMessage @marketoMessage @smoke @regression',
    type: 'message',
    formType: 'expanded',
  },
  {
    tcid: '5',
    name: '@marketo essential template (message)',
    path: ['/drafts/nala/blocks/marketo/essential-message'],
    tags: '@marketo @marketoEssentialMessage @marketoMessage @smoke @regression',
    type: 'message',
    formType: 'essential',
  },
  {
    tcid: '6',
    name: '@marketo show/hide post form submission',
    path: ['/drafts/nala/blocks/marketo/show-hide'],
    tags: '@marketo @marketoShowHide @smoke @regression',
    type: 'showHide',
    formType: 'essential',
  },
  {
    tcid: '7',
    name: '@marketo form off param',
    path: ['/drafts/nala/blocks/marketo/show-hide'],
    tags: '@marketo @marketoShowHide @marketoFormOff @smoke @regression',
    type: 'formOff',
    formType: 'essential',
  },
  {
    tcid: '8',
    name: '@marketo multi-step 3 template (redirect)',
    path: ['/drafts/nala/blocks/marketo/marketo-3-step-redirect'],
    tags: '@marketo @marketoMultiStep @marketoMultiStep3 @marketoMultiStepRedirect @smoke @regression',
    type: 'redirect',
    formType: 'multi-step',
    totalSteps: 3,
  },
  {
    tcid: '9',
    name: '@marketo multi-step 3 template (message)',
    path: ['/drafts/nala/blocks/marketo/marketo-3-step-message'],
    tags: '@marketo @marketoMultiStep @marketoMultiStep3 @marketoMultiStepMessage @smoke @regression',
    type: 'message',
    formType: 'multi-step',
    totalSteps: 3,
  },
  {
    tcid: '10',
    name: '@marketo multi-step 2 template (redirect)',
    path: ['/drafts/nala/blocks/marketo/marketo-2-step-redirect'],
    tags: '@marketo @marketoMultiStep @marketoMultiStep2 @marketoMultiStepRedirect @smoke @regression',
    type: 'redirect',
    formType: 'multi-step',
    totalSteps: 2,
  },
  {
    tcid: '11',
    name: '@marketo multi-step 2 template (message)',
    path: ['/drafts/nala/blocks/marketo/marketo-2-step-message'],
    tags: '@marketo @marketoMultiStep @marketoMultiStep2 @marketoMultiStepMessage @smoke @regression',
    type: 'message',
    formType: 'multi-step',
    totalSteps: 2,
  },
  {
    tcid: '12',
    name: '@marketo CDN routing — mkto/ path assertion',
    path: ['/drafts/nala/blocks/marketo/essential'],
    tags: '@marketo @marketoCdnRouting @regression',
    type: 'cdnRouting',
    formType: 'essential',
  },
  {
    tcid: '13',
    name: '@marketo flex template respects authored field visibility',
    path: ['/drafts/nala/blocks/marketo/full'],
    tags: '@marketo @marketoFieldVisibility @regression',
    type: 'fieldVisibility',
    formType: 'full',
  },
  {
    tcid: '14',
    name: '@marketo POI auto-hides products via flat field_filters',
    path: ['/drafts/nala/blocks/marketo/full'],
    tags: '@marketo @marketoFieldFilters @regression',
    type: 'poiAutoHide',
    formType: 'full',
  },
  {
    tcid: '15',
    name: '@marketo category filters read the flat field_filters path',
    path: ['/drafts/nala/blocks/marketo/full'],
    tags: '@marketo @marketoFieldFilters @regression',
    type: 'categoryFilters',
    formType: 'full',
  },
  {
    tcid: '16',
    name: '@marketo program id — template default (Path A)',
    path: ['/drafts/nala/blocks/marketo/programid-template'],
    tags: '@marketo @marketoProgramId @marketoProgramIdTemplate @regression',
    type: 'programId',
    formType: 'expanded',
    expectedProgramId: '92816',
    expectedSetBy: 'template',
  },
  {
    tcid: '17',
    name: '@marketo program id — template overrides authored (Path B, current behavior)',
    path: ['/drafts/nala/blocks/marketo/programid-authored'],
    tags: '@marketo @marketoProgramId @marketoProgramIdAuthored @regression',
    type: 'programId',
    formType: 'expanded',
    expectedProgramId: '92816',
    expectedSetBy: 'template',
  },
  {
    tcid: '18',
    name: '@marketo program id — authored passthrough on empty-default template',
    path: ['/drafts/nala/blocks/marketo/programid-passthrough'],
    tags: '@marketo @marketoProgramId @marketoProgramIdPassthrough @regression',
    type: 'programId',
    formType: 'expanded',
    expectedProgramId: '99999',
    expectedSetBy: 'authored',
  },
  {
    tcid: '19',
    name: '@marketo /ie/ locale privacy link',
    path: ['/ie/drafts/nala/blocks/marketo/full'],
    tags: '@marketo @marketoPrivacyLocale @regression',
    type: 'privacyLocale',
    formType: 'full',
    locale: 'ie',
    countryLabel: 'Ireland',
  },
  {
    tcid: '20',
    name: '@marketo /jp/ locale form translation',
    path: ['/jp/drafts/nala/blocks/marketo/essential'],
    tags: '@marketo @marketoLocaleTranslation @regression',
    type: 'localeTranslation',
    formType: 'essential',
    locale: 'jp',
    expectedSubmitText: '送信',
  },
  {
    tcid: '21',
    name: '@marketo field visibility — essential all-hidden',
    path: ['/drafts/denli/blocks/marketo/field-pref-test/essential-all-hidden'],
    tags: '@marketo @marketoFieldVisibility @regression',
    type: 'fieldVisibility',
    formType: 'essential',
    expectedFields: {
      name: 'hidden',
      phone: 'hidden',
      company: 'hidden',
      website: 'hidden',
      postcode: 'hidden',
      company_size: 'hidden',
      comments: 'hidden',
      demo: 'hidden',
    },
  },
  {
    tcid: '22',
    name: '@marketo field visibility — essential show-all',
    path: ['/drafts/denli/blocks/marketo/field-pref-test/essential-show-all'],
    tags: '@marketo @marketoFieldVisibility @regression',
    type: 'fieldVisibility',
    formType: 'essential',
    expectedFields: {
      name: 'required',
      phone: 'visible',
      company: 'required',
      website: 'visible',
      postcode: 'visible',
      company_size: 'visible',
      comments: 'visible',
      demo: 'visible',
    },
  },
  {
    tcid: '23',
    name: '@marketo field visibility — expanded all-hidden',
    path: ['/drafts/denli/blocks/marketo/field-pref-test/expanded-all-hidden'],
    tags: '@marketo @marketoFieldVisibility @regression',
    type: 'fieldVisibility',
    formType: 'expanded',
    expectedFields: {
      name: 'hidden',
      phone: 'hidden',
      company: 'hidden',
      website: 'hidden',
      postcode: 'hidden',
      company_size: 'hidden',
      comments: 'hidden',
      demo: 'hidden',
    },
  },
  {
    tcid: '24',
    name: '@marketo field visibility — expanded show-all',
    path: ['/drafts/denli/blocks/marketo/field-pref-test/expanded-show-all'],
    tags: '@marketo @marketoFieldVisibility @regression',
    type: 'fieldVisibility',
    formType: 'expanded',
    expectedFields: {
      name: 'required',
      phone: 'visible',
      company: 'required',
      website: 'visible',
      postcode: 'visible',
      company_size: 'visible',
      comments: 'visible',
      demo: 'visible',
    },
  },
  {
    tcid: '25',
    name: '@marketo field visibility — full all-hidden',
    path: ['/drafts/denli/blocks/marketo/field-pref-test/full-all-hidden'],
    tags: '@marketo @marketoFieldVisibility @regression',
    type: 'fieldVisibility',
    formType: 'full',
    expectedFields: {
      name: 'hidden',
      phone: 'hidden',
      company: 'hidden',
      website: 'hidden',
      postcode: 'hidden',
      company_size: 'hidden',
      comments: 'hidden',
      demo: 'hidden',
    },
  },
  {
    tcid: '26',
    name: '@marketo field visibility — full show-all',
    path: ['/drafts/denli/blocks/marketo/field-pref-test/full-show-all'],
    tags: '@marketo @marketoFieldVisibility @regression',
    type: 'fieldVisibility',
    formType: 'full',
    expectedFields: {
      name: 'required',
      phone: 'visible',
      company: 'required',
      website: 'visible',
      postcode: 'visible',
      company_size: 'visible',
      comments: 'visible',
      demo: 'visible',
    },
  },
  {
    tcid: '27',
    name: '@marketo field visibility — expanded dx mixed config',
    path: ['/drafts/denli/blocks/marketo/field-pref-test/expanded-dx'],
    tags: '@marketo @marketoFieldVisibility @regression',
    type: 'fieldVisibility',
    formType: 'expanded',
    expectedFields: {
      name: 'required',
      phone: 'required',
      company: 'required',
      website: 'visible',
      postcode: 'visible',
      company_size: 'visible',
      comments: 'visible',
      demo: 'visible',
    },
  },
  {
    tcid: '28',
    name: '@marketo field visibility — full dme mixed config',
    path: ['/drafts/denli/blocks/marketo/field-pref-test/full-dme'],
    tags: '@marketo @marketoFieldVisibility @regression',
    type: 'fieldVisibility',
    formType: 'full',
    expectedFields: {
      name: 'required',
      phone: 'visible',
      company: 'visible',
      website: 'visible',
      postcode: 'required',
      company_size: 'required',
      comments: 'visible',
      demo: 'hidden',
    },
  },
];

export default features;
