const features = [
  {
    tcid: '0',
    name: '@marketo full template (redirect)',
    path: ['/drafts/nala/blocks/marketo/full'],
    tags: '@marketo @marketoFullRedirect @marketoRedirect @smoke @regression',
    type: 'redirect',
    formType: 'full',
  },
  {
    tcid: '1',
    name: '@marketo expanded template (redirect)',
    path: ['/drafts/nala/blocks/marketo/expanded'],
    tags: '@marketo @marketoExpandedRedirect @marketoRedirect @smoke @regression',
    type: 'redirect',
    formType: 'expanded',
  },
  {
    tcid: '2',
    name: '@marketo essential template (redirect)',
    path: ['/drafts/nala/blocks/marketo/essential'],
    tags: '@marketo @marketoEssentialRedirect @marketoRedirect @smoke @regression',
    type: 'redirect',
    formType: 'essential',
  },
  {
    tcid: '3',
    name: '@marketo full template (message)',
    path: ['/drafts/nala/blocks/marketo/full-message'],
    tags: '@marketo @marketoFullMessage @marketoMessage @smoke @regression',
    type: 'message',
    formType: 'full',
  },
  {
    tcid: '4',
    name: '@marketo expanded template (message)',
    path: ['/drafts/nala/blocks/marketo/expanded-message'],
    tags: '@marketo @marketoExpandedMessage @marketoMessage @smoke @regression',
    type: 'message',
    formType: 'expanded',
  },
  {
    tcid: '5',
    name: '@marketo essential template (message)',
    path: ['/drafts/nala/blocks/marketo/essential-message'],
    tags: '@marketo @marketoEssentialMessage @marketoMessage @smoke @regression',
    type: 'message',
    formType: 'essential',
  },
  {
    tcid: '6',
    name: '@marketo show/hide post form submission',
    path: ['/drafts/nala/blocks/marketo/show-hide'],
    tags: '@marketo @marketoShowHide @smoke @regression',
    type: 'showHide',
    formType: 'essential',
  },
  {
    tcid: '7',
    name: '@marketo form off param',
    path: ['/drafts/nala/blocks/marketo/show-hide'],
    tags: '@marketo @marketoShowHide @marketoFormOff @smoke @regression',
    type: 'formOff',
    formType: 'essential',
  },
  {
    tcid: '8',
    name: '@marketo multi-step 3 template (redirect)',
    path: ['/drafts/nala/blocks/marketo/marketo-3-step-redirect'],
    tags: '@marketo @marketoMultiStep @marketoMultiStep3 @marketoMultiStepRedirect @smoke @regression',
    type: 'redirect',
    formType: 'multi-step',
    totalSteps: 3,
  },
  {
    tcid: '9',
    name: '@marketo multi-step 3 template (message)',
    path: ['/drafts/nala/blocks/marketo/marketo-3-step-message'],
    tags: '@marketo @marketoMultiStep @marketoMultiStep3 @marketoMultiStepMessage @smoke @regression',
    type: 'message',
    formType: 'multi-step',
    totalSteps: 3,
  },
  {
    tcid: '10',
    name: '@marketo multi-step 2 template (redirect)',
    path: ['/drafts/nala/blocks/marketo/marketo-2-step-redirect'],
    tags: '@marketo @marketoMultiStep @marketoMultiStep2 @marketoMultiStepRedirect @smoke @regression',
    type: 'redirect',
    formType: 'multi-step',
    totalSteps: 2,
  },
  {
    tcid: '11',
    name: '@marketo multi-step 2 template (message)',
    path: ['/drafts/nala/blocks/marketo/marketo-2-step-message'],
    tags: '@marketo @marketoMultiStep @marketoMultiStep2 @marketoMultiStepMessage @smoke @regression',
    type: 'message',
    formType: 'multi-step',
    totalSteps: 2,
  },
];

export default features;
