/* eslint-disable camelcase */
/* eslint-disable max-len */
/* eslint-disable no-restricted-syntax */
// Template Rules

import { mkfC } from './marketo_form_setup_rules.js';

// Auto-complete fields constant
export const AUTO_COMPLETE_FIELDS = [
  'Email',
  'FirstName',
  'LastName',
  'Phone',
  'mktoFormsJobTitle',
  'mktoFormsCompany',
  'Country',
  'State',
  'PostalCode',
];

// Template rules array
export const TEMPLATE_RULES = [
  {
    request_for_information: {
      formVersion: [
        '1723:MCZ Staging (1723)',
      ],
      purpose: ['request_for_information:Request for Information (request_for_information)'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['required:Make Required (required)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['required:Make Required (required)'],
        postcode: ['required:Make Required (required)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['Functional Area-DX:DX Specific Options (Functional Area-DX)'],
        products: ['POI-Dxonly:DX Products (POI-Dxonly)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['DX:DX Specific Roles (DX)'],
      },
      auto_complete: AUTO_COMPLETE_FIELDS,
      enrichment_fields: [],
    },
  },
  {
    trial: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['trial_download:Trial Download (trial_download)'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['required:Make Required (required)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['required:Make Required (required)'],
        postcode: ['required:Make Required (required)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['Functional Area-DX:DX Specific Options (Functional Area-DX)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['DX:DX Specific Roles (DX)'],
      },
      auto_complete: AUTO_COMPLETE_FIELDS,
      enrichment_fields: [],
    },
  },
  {
    content_evaluate: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['whitepaper_form:Whitepaper Download'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['required:Make Required (required)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['required:Make Required (required)'],
        postcode: ['required:Make Required (required)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['Functional Area-DX:DX Specific Options (Functional Area-DX)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['DX:DX Specific Roles (DX)'],
      },
      auto_complete: AUTO_COMPLETE_FIELDS,
      enrichment_fields: [],
    },
  },
  {
    webinar_virtual: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['strategy_webinar:Strategy Webinar (strategy_webinar)'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['required:Make Required (required)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['required:Make Required (required)'],
        postcode: ['required:Make Required (required)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['Functional Area-DX:DX Specific Options (Functional Area-DX)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['DX:DX Specific Roles (DX)'],
      },
      auto_complete: AUTO_COMPLETE_FIELDS,
      enrichment_fields: [],
    },
  },
  {
    strategy_webinar: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['strategy_webinar:Strategy Webinar (strategy_webinar)'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['required:Make Required (required)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['required:Make Required (required)'],
        postcode: ['required:Make Required (required)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['Functional Area-DX:DX Specific Options (Functional Area-DX)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['DX:DX Specific Roles (DX)'],
      },
      auto_complete: AUTO_COMPLETE_FIELDS,
      enrichment_fields: [],
    },
  },
  {
    content_explore: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['whitepaper_form:Whitepaper Download'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['hidden:Hide Field (hidden)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['hidden:Hide Field (hidden)'],
        postcode: ['hidden:Hide Field (hidden)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['Functional Area-DX:DX Specific Options (Functional Area-DX)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['DX:DX Specific Roles (DX)'],
      },
      auto_complete: AUTO_COMPLETE_FIELDS,
      enrichment_fields: [],
    },
  },
  {
    content_discover: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['whitepaper_form:Whitepaper Download'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['hidden:Hide Field (hidden)'],
        phone: ['hidden:Hide Field (hidden)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['hidden:Hide Field (hidden)'],
        postcode: ['hidden:Hide Field (hidden)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['hidden:Hide Field (hidden)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['hidden:Hide Field (hidden)'],
      },
      auto_complete: AUTO_COMPLETE_FIELDS,
      enrichment_fields: [],
    },
  },
  {
    subscribe: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['subscribe:Subscribe'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['hidden:Hide Field (hidden)'],
        phone: ['hidden:Hide Field (hidden)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['hidden:Hide Field (hidden)'],
        postcode: ['hidden:Hide Field (hidden)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['hidden:Hide Field (hidden)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['hidden:Hide Field (hidden)'],
      },
      auto_complete: AUTO_COMPLETE_FIELDS,
      enrichment_fields: [],
    },
  },
  {
    flex_contact: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['request_for_information:Request for Information (request_for_information)'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['required:Make Required (required)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['required:Make Required (required)'],
        postcode: ['required:Make Required (required)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['Functional Area-DX:DX Specific Options (Functional Area-DX)'],
        products: ['POI-Dxonly:DX Products (POI-Dxonly)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['DX:DX Specific Roles (DX)'],
      },
      auto_complete: AUTO_COMPLETE_FIELDS,
      enrichment_fields: [],
    },
  },
  {
    flex_event: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['strategy_webinar:Strategy Webinar (strategy_webinar)'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['hidden:Hide Field (hidden)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['hidden:Hide Field (hidden)'],
        postcode: ['hidden:Hide Field (hidden)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['Functional Area-DX:DX Specific Options (Functional Area-DX)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['DX:DX Specific Roles (DX)'],
      },
      auto_complete: AUTO_COMPLETE_FIELDS,
      enrichment_fields: [],
    },
  },
  {
    flex_content: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['whitepaper_form:Whitepaper Download'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['hidden:Hide Field (hidden)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['hidden:Hide Field (hidden)'],
        postcode: ['hidden:Hide Field (hidden)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['hidden:Hide Field (hidden)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['hidden:Hide Field (hidden)'],
      },
      auto_complete: AUTO_COMPLETE_FIELDS,
      enrichment_fields: [],
    },
  },
  {
    dme_flex_contact: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['request_for_information:Request for Information (request_for_information)'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['required:Make Required (required)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['required:Make Required (required)'],
        postcode: ['required:Make Required (required)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['Functional Area-DMe:DMe Specific Options (Functional Area-DMe)'],
        products: ['POI-DMe:DMe Products (POI-DMe)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['DMe:DMe Specific Roles (DMe)'],
      },
    },
  },
  {
    dme_flex_event: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['strategy_webinar:Strategy Webinar (strategy_webinar)'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['hidden:Hide Field (hidden)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['hidden:Hide Field (hidden)'],
        postcode: ['hidden:Hide Field (hidden)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['Functional Area-DMe:DMe Specific Options (Functional Area-DMe)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['DMe:DMe Specific Roles (DMe)'],
      },
    },
  },
  {
    dme_flex_content: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['whitepaper_form:Whitepaper Download'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['hidden:Hide Field (hidden)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['hidden:Hide Field (hidden)'],
        postcode: ['hidden:Hide Field (hidden)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['hidden:Hide Field (hidden)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['hidden:Hide Field (hidden)'],
      },
    },
  },
  {
    comb_flex_contact: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['request_for_information:Request for Information (request_for_information)'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['required:Make Required (required)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['required:Make Required (required)'],
        postcode: ['required:Make Required (required)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['Functional Area-Combined:DMe & DX Combined Options (Functional Area-Combined)'],
        products: ['POI-Combined:DMe & DX Combined Products (POI-Combined)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['Combined:DMe & DX Combined Roles (Combined)'],
      },
    },
  },
  {
    comb_flex_event: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['strategy_webinar:Strategy Webinar (strategy_webinar)'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['hidden:Hide Field (hidden)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['hidden:Hide Field (hidden)'],
        postcode: ['hidden:Hide Field (hidden)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['Functional Area-Combined:DMe & DX Combined Options (Functional Area-Combined)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['Combined:DMe & DX Combined Roles (Combined)'],
      },
    },
  },
  {
    comb_flex_content: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['whitepaper_form:Whitepaper Download'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['hidden:Hide Field (hidden)'],
        company: ['required:Make Required (required)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['hidden:Hide Field (hidden)'],
        postcode: ['hidden:Hide Field (hidden)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['hidden:Hide Field (hidden)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['hidden:Hide Field (hidden)'],
      },
    },
  },
  {
    subscription: {
      formVersion: ['1723:MCZ Staging (1723)'],
      purpose: ['subscription:Subscription'],
      formSuccessType: ['redirect:redirect (redirect)'],
      field_visibility: {
        name: ['required:Make Required (required)'],
        phone: ['hidden:Hide Field (hidden)'],
        company: ['hidden:Hide Field (hidden)'],
        website: ['hidden:Hide Field (hidden)'],
        state: ['hidden:Hide Field (hidden)'],
        postcode: ['hidden:Hide Field (hidden)'],
        company_size: ['hidden:Hide Field (hidden)'],
        comments: ['hidden:Hide Field (hidden)'],
        demo: ['hidden:Hide Field (hidden)'],
      },
      field_filters: {
        functional_area: ['hidden:Hide Field (hidden)'],
        products: ['hidden:Hide Field (hidden)'],
        industry: ['hidden:Hide Field (hidden)'],
        job_role: ['hidden:Hide Field (hidden)'],
      },
      auto_complete: AUTO_COMPLETE_FIELDS,
      enrichment_fields: [],
    },
  },
];

export default function init() {
  window.templateRules = TEMPLATE_RULES;
  mkfC.log('Template Rules - Loaded');
}
